### ISSUE TITLE
Add fenom support

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/fred#10]
Hi. Please add support fenom.

Example PR https://github.com/Sterc/FormIt/pull/89

**Comment by seobeltg** [comment]
Hello
Our site use Fenom
but for some reason Fred can recognize build Fenom:
{$.....} inside tag
for example - interpret: %7B%24...%7D
but outside the tag ({$.....}) it`s ok


how can I help us?

**Comment by rthrash** [comment]
Hi @seobeltg and @Ibochkarev,

Would either of you be able to help coordinate a fenom support Pull Request once 1.0 is released?

Thanks,

**Comment by rthrash** [comment]
Closing for now as we do not have the bandwidth to tackle this ourselves. That said we welcome contributions to meals this happen. Please feel free to reopen in the future.
