### ISSUE TITLE
Image picker preview needs max-height. Tall images go off the edge of the screen.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#103]
Once the image picker is open, it's not possible to click any of the buttons off the edge of the screen.
Please see screenshot:

![screenshot_2019-01-21 menu - sanwa-jo japanese restaurant](https://user-images.githubusercontent.com/5160368/51457023-b91eb300-1d8a-11e9-8ba0-c7db9005988e.png)

**Comment by digitalpenguin** [comment]
My temporary way to fix this for now is:
```
.fred .fred--modal label {
    max-height:400px;
    overflow:hidden;
}
```

Not the greatest way as it hides the bottom part of the image but it allows it to function for now!

**Comment by matdave** [comment]
This has been fixed by adding overflow, since we don't know how many attributes could be added to the modal.
