### ISSUE TITLE
Disable edit on hover unless sidebar open

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#104]
Hi, would be great if you could disable fred or make it treat a page and its elements as un-editable UNLESS the Fred sidebar has been opened by the editor.

Were getting complaints from Fred editors that they can't view/read pages like standard users as the hover effects on editable elements take over when they are just browsing or reading articles on the site. Also hyperlinks don't work as when they click on them fred thinks they want to edit the text element.

Thanks

**Comment by theboxer** [comment]
You can disable fred from the sidebar which lets you browse the site without fred.

![image](https://user-images.githubusercontent.com/845220/51481524-5af6cd80-1d94-11e9-8039-f7b56fc5c053.png)

**Comment by davidpede** [comment]
Perfect - thank you.

Could this be set this as default via sys setting?

**Comment by theboxer** [comment]
Nope
