### ISSUE TITLE
Tagger type setting improvement

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#106]
I've got a tagger setting set like so:
```
{
      "name": "tagger",
      "label": "Category Tags",
      "type": "tagger",
      "group": "1",
      "hideInput": false,
      "autoTag": true
}
```
However the user can't add new tags, can only select existing ones assigned to group 1. I have the 'Allow new tags from field' box ticked for the group in manager cmp but no good.

Would be great if this could be added.

Thanks

**Comment by theboxer** [comment]
What's the use case of adding new tags from element settings?

**Comment by theboxer** [comment]
@davidpede ping

**Comment by davidpede** [comment]
Would be useful for jquery/js filtering. You could be adding people profiles or images to a gallery as elements and then filtering on the tags. Like the Isotope filter example here: https://isotope.metafizzy.co/

Frustrating for the user if they can't add tags to the element in the same way they can in the 'Settings > Tags' window.
