### ISSUE TITLE
Feature Req: specify a blueprint to use when creating a Resource

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#107]
I'm trying to use the default element setting shown here: https://modxcms.github.io/fred/themer/cmp/themes/#default-element

It doesn't seem to work. My setup is as:

Default element setting value: `5|test`

My Template:
```
<!doctype html>
<html lang="en">
<head>
    <base href="[[!++site_url]]"/>
</head>
<body class="sidebar-right-visible">
    <div data-fred-dropzone="content">
        [[*content]]
    </div>
    <!-- Footer -->
    [[$footer]]
    <!-- /page footer -->
</body>
</html>
```
Element (ID 5):
```
<div data-fred-name="test"></div>
```
Element 5 doesn't appear on a newly created resource with no elements. Is there an issue or am I using this incorrectly?

Thanks

**Comment by theboxer** [comment]
The default element is used when you are converting already create resource to a fred resource. It will have no effect when you create new fred resource from scratch.

If you want to have some initial elements for new resources, create them from a blueprint.

**Comment by davidpede** [comment]
Ok thanks for confirming. Is there a way to specify a blueprint to use when creating a resource without the user having to select one?

**Comment by theboxer** [comment]
nope, but it's a great idea.

**Comment by rthrash** [comment]
Going to edit the title and turn this into a feature request
