### ISSUE TITLE
Add data-fred-editable attr instead of directly using contenteditable

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#112]
Using the example below - `contenteditable="false"` has no effect, user can still change the image.

```
<img data-fred-name="test_image" contenteditable="false" src="https://via.placeholder.com/400x200">
```

**Comment by theboxer** [comment]
Why are you using data-fred-name when you don't want to change the image?

**Comment by davidpede** [comment]
I'll explain the reasoning in another issue and link back as its related to something else. I'd still say this is a bug as `<p data-fred-name="test" contenteditable="false">default text</div>` behaves as expected.

**Comment by rthrash** [comment]
Very curious about the false use case @davidpede … can you share the details? Thanks!
