### ISSUE TITLE
Add a credits documentation page

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#126]
Need to give credit to the folks that we built on top of including Dragula and the other libraries for sliders, color pickers, etc.

**Comment by theboxer** [comment]
"choices.js": "^3.0.4",
    "dragula": "^3.7.2",
    "flatpickr": "^4.5.2",
    "hoverintent": "^2.1.0",
    "html2canvas": "^1.0.0-alpha.12",
    "isomorphic-fetch": "^2.2.1",
    "jssha": "^2.3.1",
    "mousetrap": "^1.6.2",
    "nouislider": "^11.1.0",
    "promise-cancel": "^2.0.1",
    "twig": "^1.12.0",
    "lodash": ">=4.17.5"
