### ISSUE TITLE
Resource permissions issue

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#132]
I'm trying restrict which resources appear in the 'Parent' drop down menu in the 'Create Page' window.

I have the following usergroups: Administrators and Editors.

As a test I setup a resource group in MODX and restricted it to the Administrators group in web context. Then added it to the Editors group with 'Load Only' policy in web context.

The Editors can't view resources in the resource group, in web context, which is correct. However the protected resources still appear the 'Parent' drop down menu in the 'Create Page' window.

Ultimately I want to use 'list' or 'add_children' permissions to hide resources from 'Parent' drop down menu but allow Editors to view and edit the resources with FRED.

Is this possible or is FRED ignoring the permissions?

**Comment by theboxer** [comment]
Can you try to edit this file: `core/components/fred/model/fred/src/Endpoint/Ajax/GetResources.php` and replace the foreach on line 100 with this one:
```
foreach ($resourcesIterator as $resource) {
            if (!$resource->checkPolicy('list')) continue;
            
            $data[] = [
                'id' => $resource->id,
                'value' => (string)$resource->id,
                'pagetitle' => $resource->pagetitle,
                'customProperties' => [
                    'url' => $this->modx->makeUrl($resource->id, $context, '', 'abs')
                ]
            ];
        }
```

And see if it resolves the issue you are having?

**Comment by davidpede** [comment]
Thanks for this but it seems that the parent list is populated via `GetResourceTree`. I'm working on a pr to resolve so hopefully you can check it.

**Comment by davidpede** [comment]
#138 partly solves this issue for now. I'd still like to add a `add_children` policy check for resources listed in the parent select but this involves quite a bite more work.

Would require a separate ajax endpoint like `getParents` and some refactoring to the create page panel. Are you open to a pr involving this?

**Comment by theboxer** [comment]
Yes, I'm open to the PR for improving this. Thank you for your work on it.
