### ISSUE TITLE
"remote" option doesn't periodically re-render element

### ISSUE THREAD

**Issue by oskarmaxa** [modxcms/fred#139]
According to the docs (link below), the **remote** option should cause an element's content to be fetched via AJAX and re-rendered every 200 ms. In my case, all it does is turn on parsing of MODX tags (e.g. snippets) in the element markup, but no additional requests are made and no visible re-rendering occurs.

Is the feature incomplete or am I missing something?

https://modxcms.github.io/fred/themer/options/settings/

**Comment by theboxer** [comment]
The docs are wrong about this. The remote render happens when you drop the element for the first time and when you are changing the element settings (through the change of element settings it re-renders the element every 200ms).
