### ISSUE TITLE
Force pasting as plain text into non-RTE text elements.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#146]
Currently if copy and pasting text into an editable text element, the styles are pasted too.
This should be set to paste as plain text or at least provide an option to set it that way.

I understand I can force plain text pasting in a text element that has RTE enabled but it's currently not possible on a field without the RTE enabled.

**Comment by digitalpenguin** [comment]
As a work-around I've enabled the RTE on these elements and using an RTE config of:
```
{
  "plugins": "paste",
  "paste_as_text": true,
  "selection_toolbar": false,
  "insert_toolbar": false
}
```
This forces plain text pasting and hides the toolbars. Thanks to @donshakespeare for the tip ;)

**Comment by matdave** [comment]
Another option would be to try pasting while holding the Shift button. This is a paste and match styles/ paste as plain text option that is supported in most browsers.

**Comment by rthrash** [comment]
Possible Solution, but don't know if it would mess up already-formatted text: https://stackoverflow.com/questions/51758564/paste-fix-for-contenteditable

This is a tricky one with a slippery-slope…

**Comment by donShakespeare** [comment]
If ya want to have complete control over contenteditable .... use TinyMCE as the editor, and use my markdown plugin or similar idea and take utter dominance of what goes in that field .... textarea on roids
https://github.com/donShakespeare/twExoticMarkdownEditor

This plugin locks out all visual html, dragged/pasted inserted, whatever!

**Comment by digitalpenguin** [comment]
Ultimately, I think what would be most useful would be allow formatting such as paragraphs, lists, headings etc to be pasted.
But don't allow font type and font size to be pasted. I'm having trouble imagining a situation where you would actually want some external font to be pasted in ignoring your css.
Especially since once it's pasted into a regular text field you can't change it.

**Comment by donShakespeare** [comment]
Your ordinary TinyMCE editor has this setting that will control even the junk dragged/pasted in
https://www.tiny.cloud/docs/configure/content-filtering/#valid_elements
