### ISSUE TITLE
Feature Requests: RTE and elFinder

### ISSUE THREAD

**Issue by EkoOne** [modxcms/fred#147]
I realize some (or all) of these requests may not be feasible or even possible with Fred, or perhaps they are of no interest to you. Fair enough. Consider them modest suggestions based in large part on my extensive use of @donshakespeare 's highly customizable TinymceWrapper (TW) and Responsive FileManager (RFM) Extras.

- Ability to override the default Fred stylesheet (assets/components/fred/web/fred.css) and define the path to a custom ’sheet via a Property Set or System setting.

- Ability to override the default elFinder configuration file via a Property Set. For example, put the default config. in a Chunk which the user would duplicate and customize and then define in a custom Property Set.

- Option to use and configure other file managers such as Responsive FileManager.

- Ability to assign different TinyMCE and file manager configurations to a specific user-group.

- Option to create custom elFinder (upload) folders for each user based on a profile (extended?) field etc. if/when necessary as opposed to one shared folder for everyone. Bonus points if folder name can be hashed. * _I can do all of this with TW/RFM and it's fantastic._

- This one is problematic (but not surprising) so I'm throwin' it out there just so you're aware of it. The Ace editor can't be used with Fred and TinymceWrapper at the same time. TW ships with Ace and CodeMirror and you define one of them in the TW pset. I happen to use Ace with TW in the back-end and I can confirm it creates problems with Fred and vice-versa.

There's more but that's enough for now. Really impressed with Fred so far, you've done an amazing job!

Thanks

**Comment by rthrash** [comment]
Thanks @EkoOne! Looks like you might have six different issues in this one. ;)

> Ability to override the default Fred stylesheet (assets/components/fred/web/fred.css) and define the path to a custom ’sheet via a Property Set or System setting.

Use case? Specific suggestions for improvements?

> Ability to override the default elFinder configuration file via a Property Set. For example, put the default config. in a Chunk which the user would duplicate and customize and then define in a custom Property Set.

We won't be using chunks for configurations. Overridable configs should be doable, I think today even. Probably should open this one as a separate issue.

> Option to use and configure other file managers such as Responsive FileManager.

Definitely should be doable via a plugin in the future.

> Ability to assign different TinyMCE and file manager configurations to a specific user-group.

That definitely belongs as a separate issue. Huge implications on the ACLs initiative that is about to start.

> Option to create custom elFinder (upload) folders for each user based on a profile (extended?) field etc. if/when necessary as opposed to one shared folder for everyone. Bonus points if folder name can be hashed. * _I can do all of this with TW/RFM and it's fantastic._

This is a great idea and seriously useful. Don did a very cool thing with this. :) Please open another issue for this one also. May not happen immediately, but it definitely needs detailed specs/scope of how it should work.

> This one is problematic (but not surprising) so I'm throwin' it out there just so you're aware of it. The Ace editor can't be used with Fred and TinymceWrapper at the same time. TW ships with Ace and CodeMirror and you define one of them in the TW pset. I happen to use Ace with TW in the back-end and I can confirm it creates problems with Fred and vice-versa.

Unfortunately, probably not something we'll tackle. We've noticed this ourselves, too.

**Comment by EkoOne** [comment]
Yeah, sorry, Ryan, I don't use github much. I will open as separate requests.

Thanks

**Comment by rthrash** [comment]
Thanks! Closing this one for the new issues.
