### ISSUE TITLE
Feature Request: Alternate Fred CSS

### ISSUE THREAD

**Issue by EkoOne** [modxcms/fred#148]
Ability to override the default Fred stylesheet (assets/components/fred/web/fred.css) and define the path to a custom ’sheet via a Property Set or System setting.

**Use-case:** A client wants Fred to better match the look of their site, e.g. color palette, fonts etc. Or maybe they just prefer a different look. I have a couple clients who have _very_ specific ideas on how they want things to look and I can envision them wanting a different appearance.

**Comment by rthrash** [comment]
Completely understand your suggestion, but we won't support this for the foreseeable future, as we will be iterating, improving and changing things a lot. This would then introduce breaking changes that would impair progress, so let's wait until after 2.0 to bring this up again.
