### ISSUE TITLE
Menu overlap at 1366x768

### ISSUE THREAD

**Issue by alienbuild** [modxcms/fred#15]
The additional of 'blueprints' in the menu has caused a menu overlap for 1366x768 resolutions.

![1366x768](https://user-images.githubusercontent.com/32590877/43020258-5621c5fe-8c57-11e8-9163-13f2188ea70c.jpg)

**Comment by matdave** [comment]
This was fixed in commit c890becd3055aabd782b460fb37a02c6939b4727
