### ISSUE TITLE
Feature Request: User group configurations

### ISSUE THREAD

**Issue by EkoOne** [modxcms/fred#150]
Ability to assign different TinyMCE and file manager configurations to specific user groups.

**Comment by theboxer** [comment]
I think I'm going to be against this feature request. Currently the usage of rte & specific config is element based - for specific elements you can choose to use specific configs, so it fits your content needs for the frontend. 

Mixing up user / user groups to this flow would cause issues with different users looking/editing the same content. How should Fred & RTE act, when one user can't use `strong` tag and another one can? 

I hope we'll be able to get more granular ACLs to Fred, so you can revoke specific users / user groups from editing specific elements, which might partially work for you.

@rthrash Do you have different opinion on this one? If no, please close this issue, thank you.

**Comment by EkoOne** [comment]
My thinking was simply this… say you want to give Admins access to certain TinyMCE tools/plugins like code or advanced image or whatever, or external plugins (definition list etc.) but you don't want Members to have access to the same tools.

If that kind of fine-tuning is already available in Fred, great, then I need to explore more. But if not then I think it would be useful.

**Comment by rthrash** [comment]
The existing ACLs on media sources should handle the file manager requirements for the different user groups. Have you explored that @EkoOne ?

**Comment by EkoOne** [comment]
@rthrash I have not looked into that yet but I will. Have just recently returned to Fred (and MODX) after a lengthy hiatus.

Thanks
