### ISSUE TITLE
Feature Request: Custom upload folders

### ISSUE THREAD

**Issue by EkoOne** [modxcms/fred#151]
Option to create custom elFinder (and other file manager) upload  folders for each user based on the user profile (extended?) field etc. if/when necessary as opposed to one shared folder for everyone. Bonus points if folder name can be hashed.

_I can do all of this with TW/RFM and it's fantastic._

**Comment by theboxer** [comment]
There is no `shared upload folder`. You set up an access to media sources that users can use, they can create folders there and upload files to any folder in the media source (unless the media source is set as read only).

If you want to have user specific folders for uploads, I suppose that'd have to be a separate media source, with some special settings for Fred, to generate the user folder and make it as a root folder for the media source...

**Comment by EkoOne** [comment]
Correct, the second half of your reply is basically what I'm suggesting.

To be more clear... the purpose is to *not* allow users access to other users’ folders. Yes, there would be one parent folder that contains all user folders, which is where the Media Source points to (the parent), but each user's personal folder would only be visible to them, no one else, because elFinder (or whatever file manager plugin is available, Resposnsive FileManager etc.) would be manually configured to only point to the folder of whomever is signed-in.

As I mentioned I've done precisely this a few times with @donshakespeare 's TW and RFM (and ClassExtender). And as far as I know the exact same thing is possible with Don's elFinder/TW (I haven't tried) so I assumed the process would be more or less similar for Fred/elFinder.
