### ISSUE TITLE
GPM Install and FredRTETinyMCE not working

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#152]
Hi,

I'm using Fred and FredRTETinyMCE via forks of their repos and installed with gpm. I cannot get TinyMCE to load in frontend.

I've got:

- Fred setting `fred.rte` set to `TinyMCE`
- Element code: `<div data-fred-name="text" data-fred-rte="true">Click Here to Edit</div>`

No errors in modx log or console. All gpm paths/urls are correct.

Is there a specific way to get this working?

**Comment by matdave** [comment]
Can you check the plugin and see what event it is set to fire on?

**Comment by davidpede** [comment]
Just found the cause - system events `FredBeforeRender` and `FredElementFormRender` were missing completely. I've manually created and it works fine.

I guess gmp install doesn't create the events?

**Comment by davidpede** [comment]
Hmm it is meant too https://github.com/modxcms/fred/blob/master/_build/resolvers/resolve.customevents.php

I don't know why in my case it didn't

**Comment by matdave** [comment]
This sounds more like a GPM bug than a Fred Bug. I have seen GPM fail to create custom plugin events, which is why I asked.

**Comment by theboxer** [comment]
Yeah, GPM doesn't have a way how to install custom events or trigger resolvers.
