### ISSUE TITLE
Feature Request: Fred Introtext TV

### ISSUE THREAD

**Issue by EkoOne** [modxcms/fred#153]
I think I know the answer but hey, I'll ask anyway.

I use TinymceWrapper to transform the introtext field into rich-text and the Fred TV is (understandably) plain-text which means they display the raw HTML. Not a big deal for the code savvy, but clients could easily muck things up.

Is there a way to make Fred's introtext TV rich-text friendly on-demand? Perhaps an enable/disable setting?

**Comment by theboxer** [comment]
It's not possible ATM, but it should be doable.

We'll just need to figure out how to select the RTE for specific field & specify a config.

I'll leave the issue here, so we can elaborate on it, when it'll become a priority.
