### ISSUE TITLE
Add blueprint select to Fred enabled resources in the manager.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#156]
Currently if you have a page that needs TVs, creating a page involves flipping between the manager and Fred. This can be a convoluted and confusing process for clients.

Since Fred can't edit TVs yet ( I know it's on the roadmap ) a "Select Fred Blueprint" field and even a "Default Fred Blueprint" (for resources with a certain parent) when creating resources in the manager would help to fix the workflow.

That way, a page could be created in the manager (say, using collections), appropriate fields/TVs filled out, then they could switch to Fred and the blueprint is already there and they can immediately edit the content.

**Comment by rthrash** [comment]
I _think_ you may be able to workaround TV editing in a semi-hacky way by using a `data-fred-render="false"` attribute with a TV-editing block. 

https://modxcms.github.io/fred/themer/elements/attributes/#data-fred-render

Note: this would only support text and textarea at this time. You would use the TV names for the `data-fred-target="tv_tvName"`. Make sure to prefix any TV names with the `tv_` prefix.

**Comment by digitalpenguin** [comment]
Hmmm nice idea however it's mainly needed for things like date-pickers for sorting events and preview images for article listing etc.

Previously I was able to get data-fred-target working with standard resource fields but had no luck with TVs (I was using the tv_ prefix).
I'll have another go at it on the next project coming up.

**Comment by digitalpenguin** [comment]
Closing this because there's already an issue for the same thing.  Sorry! :P
#107
