### ISSUE TITLE
Allow Fred elements and OptionSet to be static

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#157]
Hi All,

I am aware about issue #74 that points to possible usage of Snippets as anchor for Fred elements and this would allow to have static Fred elements that are important on a multi-user development environment using subversion / git.

Do you know if this addition is under consideration?
Having everything in the database can be tricky for work sync.

Thanks in advance for this great extra!
Cheers

**Comment by theboxer** [comment]
#74 doesn't aim to use Snippets as anchor for Fred elements, or to make fred elements static.

For multi user development you'll need a shared instance and it will work mostly fine. If you'd like to go with git approach and local instances you can you Gitify (you can read more about it here: https://modxcms.github.io/fred/collab/gitify/).

We're also considering doing a theme export/import (that would work similarly as gitify, but out of the box).

**Comment by JANogueira** [comment]
Sorry, I mean chunks and not snippets. My bad.
