### ISSUE TITLE
Quick update deletes the element's options overrides

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#159]
Quite a big bug here:

1. Add some settings to an elements Option Override panel
2. Save element
3. From the Elements grid, right click on the element and click 'Quick Update Element' and then 'Save and Close'
4. Now update the element and view Option Override panel - it's empty

Just lost quite a lot of settings on a dev site quick updating the descriptions. A right pain

**Comment by theboxer** [comment]
ugh
