### ISSUE TITLE
Problems with element toolbar buttons

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#160]
Have an odd issue where buttons in the element toolbar only work when clicked on at the very lower edge:

![2019-02-27_15-22-45](https://user-images.githubusercontent.com/825106/53501522-3d5c0880-3aa4-11e9-96aa-1ec951c69d1a.gif)

I can only replicate this 80% of the time which makes it very hard to debug. Not sure if it's custom css overriding Fred styles or not, can anyone else reproduce?

**Comment by davidpede** [comment]
Another example:

![2019-02-27_15-33-27](https://user-images.githubusercontent.com/825106/53502042-29fd6d00-3aa5-11e9-8dff-be8ebf7b9b22.gif)

All btns for the image elements work fine, the duplicate btn on text is now fine (but not in prev example) but the delete btn isn't right in both examples.

**Comment by matdave** [comment]
Looks like it is just when you hit the very top of the hit box for the button, can you confirm?  Is that a flex container using data-fred-block-class?

**Comment by davidpede** [comment]
No sometimes the button does nothing unless the very bottom edge is clicked. It varies tbh, I've tried to demo above.

I'm wondering if its when they overlay the element above causing it but its not consistent.

Yes - both elements in demos above have bootstrap flex column classes applied like:
```
<div data-fred-block-class="col-{{ col }}">
  <div data-fred-name="text" data-fred-rte="true">Lorem ipsum</div>
</div>
```

**Comment by digitalpenguin** [comment]
I can replicate this with a row flex container. It's not just duplicating though, dropping an element in sometimes just disappears.

**Comment by matdave** [comment]
I am pretty sure this is a browser rendering issue causing a reduction in the hitbox area with an absolutely position toolbar outside a flex flowed container.  We are working on a solution to move the toolbar outside of the div but the main dilemma is to still get the drag trigger to work. That would eliminate a lot of CSS conflict, though. We'll leave this open as we investigate.

**Comment by davidpede** [comment]
> I can replicate this with a row flex container. It's not just duplicating though, dropping an element in sometimes just disappears.

Not sure if a separate issue but were also experiencing disappearing elements **after** saving the page. 1. User builds a layout
2. Saves the page
3. Hits F5 or disables FRED
4. Random elements have disappeared
Seems to be *some* duplicated elements that vanish but not all and not every time so very hard to debug.

**Comment by davidpede** [comment]
Seems that the transitions on the buttons are causing issues with when js registers a click. I've removed them and behavior is way better. Any chance @matdave @digitalpenguin you could test pr and see if improved your end?

**Comment by matdave** [comment]
Can you check out the latest CSS. I've increased the hitbox of the toolbar and the transitions are now on a pseudo element instead of the button itself.

**Comment by davidpede** [comment]
Just tested and yes tons better now - thank you!
