### ISSUE TITLE
Importing option set to overrides doesn't work

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#162]
I have an element option override set to:
```
{
  "remote": true,
  "settings": [
    {
      "name": "id",
      "label": "YouTube ID",
      "type": "text",
      "value": ""
    },
    {
      "fred-import": "flex_col-12_options_part"
    }
  ]
}
```
The `flex_col-12_options_part` setting is missing from the elements options in frontend. If I add the setting manually to the override it works.

**Comment by theboxer** [comment]
Can you post the content of the `flex_col-12_options_part` option set as well please?

**Comment by davidpede** [comment]
> Can you post the content of the `flex_col-12_options_part` option set as well please?

```
{
  "name": "col",
  "label": "Block Width (12 is 100% wide)",
  "type": "slider",
  "min": 1,
  "max": 12,
  "step": 1,
  "value": 12
}
```
