### ISSUE TITLE
Elements don't always save in frontent

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#163]
Experiencing disappearing elements **after** saving the page.

![2019-02-28_13-11-16](https://user-images.githubusercontent.com/825106/53568790-c03f9a80-3b5a-11e9-959f-b65b4b42dd45.gif)

1. User builds a layout
2. Saves the page
3. Hits F5 or disables FRED
4. Random elements have disappeared

Seems to be linked to _some_ duplicated elements - but not all and not every time so very hard to debug.

**Comment by digitalpenguin** [comment]
Is it only happening when using flexbox, or has it happened with other containers too?

**Comment by davidpede** [comment]
Just done some tests with a floated element instead of flexbox an I can't replicate the issue:
```
<div style="width:200px;float:left;" data-fred-name="text" data-fred-rte="true">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet justo sit amet augue imperdiet aliquet vitae sed enim. Curabitur nec sem ex. Aenean suscipit ultrices sapien eu euismod. In sit amet massa elit.</p>
</div>
```
I guess* its related to flexbox

**Comment by davidpede** [comment]
Nested dropzones and element settings seems to be the cause of this. There's a very specific process to replicate this bug:
1. In a tpl set a dropzone like:
```
<div class="outer-dropzone" data-fred-dropzone="content" style="min-height: 250px;">
    [[*content]]
</div>
```
2. create two elements, one wrapper el with a nested dropzone:
```
<div class="row" data-fred-dropzone="row" style="min-height:250px"></div>
```
and another column el with a setting:
```
<div data-fred-block-class="col-{{ col }}" data-fred-name="text" data-fred-rte="true">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet justo sit amet augue imperdiet aliquet vitae sed enim. Curabitur nec sem ex. Aenean suscipit ultrices sapien eu euismod. In sit amet massa elit.</p>
</div>
//setting
{
  "remote": true,
  "settings": [
    {
      "name": "col",
      "label": "Block Width (12 is 100% wide)",
      "type": "slider",
      "min": 1,
      "max": 12,
      "step": 1,
      "value": 12
    }
  ]
}
```
3. in the frontend drag the wrapper el into main dropzone
4. drag column el into nested wrapper dropzone
5. save and reload page
6. now change the column el setting and apply
7. duplicate the column el a couple of times
8. save and reload
9. the duplicated column els have vanished
10. duplicate again but DON'T change the column el setting. This time it works.

**Comment by davidpede** [comment]
Vid to demo the above - can anyone else replicate this?
![2019-03-12_13-47-57](https://user-images.githubusercontent.com/825106/54205084-8d3bc600-44cd-11e9-88b1-6ff579dd9cfc.gif)

**Comment by theboxer** [comment]
Awesome, I managed to replicate it. I'll look into it, thank you.

Btw. is there a specific reason why you use `remote: true` on this element, or is that just for demonstration?

**Comment by davidpede** [comment]
Glad you can replicate! Remote was just for demo, doesn't seem to effect the bug either way
