### ISSUE TITLE
Feature Request: Autosave

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#167]
As the title says, is it possible to implement a auto save feature which would trigger each X amount of time or on each change.

**Comment by rthrash** [comment]
That can be really dicey, as it can save partially completed pages in a bad state. I'm not a fan of autosave for this reason. Is there a specific problem you're trying to solve other than just forgetting to save?

**Comment by theboxer** [comment]
Autosave is not fast task as it has to generate all the HTML (call render endpoints if you use remote elements), so triggering that every second or so won't work really well. Also I agree with Ryan's point, as if you'll be working on live page, it would save incomplete changes and make them visible for everyone.
