### ISSUE TITLE
Screenshots in documantion are not shown

### ISSUE THREAD

**Issue by Zidcov** [modxcms/fred#170]
Unfortunately, screenshots in documantion are not shown. 
For example, Element Creation 3PC Screenshot

**Comment by rthrash** [comment]
Do you have a list of pages where you think Screenshots would help a lot? We should be able to get more screenshots into the docs.

**Comment by neiltipton** [comment]
I think the point being made is that the screenshots that are already embedded in pages are not showing - you just see the broken image link icon.  Examples on this page: https://modxcms.github.io/fred/themer/themes/

**Comment by Zidcov** [comment]
Yes, that's what I meant.
![image](https://user-images.githubusercontent.com/12915348/54384323-ff1a3800-46a4-11e9-8446-1bc18c8581e4.png)

**Comment by Zidcov** [comment]
Should I close this task? I've wrote it just for you information.

**Comment by rthrash** [comment]
Screenshots now updated and will be published with 1.1 release, soon.
