### ISSUE TITLE
I can't to start with Getting Started. I've got HTTP ERROR 500

### ISSUE THREAD

**Issue by Zidcov** [modxcms/fred#172]
I've tried Getting Started guid from the page https://modxcms.github.io/fred/getting_started/ .
I don't understand what is wrong.
1) I've installed packages
![image](https://user-images.githubusercontent.com/12915348/54151707-7a34e180-444c-11e9-9bab-a259cfded157.png)
2) I've created blank page document and used One Page Theme
![image](https://user-images.githubusercontent.com/12915348/54152108-7bb2d980-444d-11e9-83c6-706c1b9ccb6e.png)

And after Open in Fred or View I've got error 500 page

**Comment by rthrash** [comment]
Can you share information about your server software and PHP version? Also are there any errors logged in the console?

**Comment by Zidcov** [comment]
error log
[2019-03-10 23:33:19] (ERROR in xPDO::getService @ /home/a/alexzry8/test.infonuts.ru/public_html/core/xpdo/xpdo.class.php : 1234) modRestClient::__construct is deprecated since version 2.3.0. Use the modRest classes instead.

Parameters:
ОS: Ubuntu Server Edition
Apache:2.4.10
MySQL:5.7.21-20-beget
PHP: 7.0

**Comment by rthrash** [comment]
Fred requires PHP 7.1.3 or later in order to work, required by some of the Symphony libs. Can you update your PHP version to see if the 500 errors go away? 

I'll update the docs for the next release to reflect this.

**Comment by Zidcov** [comment]
Yes, after updating PHP version it is work. Thank you!
