### ISSUE TITLE
Why a page created with Fred isn't loading (opening)?

### ISSUE THREAD

**Issue by Zidcov** [modxcms/fred#175]
1) I've created a page with Fred
2) Saved it on Front end
3) Then the page don't load (open).
![image](https://user-images.githubusercontent.com/12915348/54390620-08f76780-46b4-11e9-84eb-077e489de25c.png)

But preview show the page
![image](https://user-images.githubusercontent.com/12915348/54390739-452ac800-46b4-11e9-89f8-42a5aa7b5dfd.png)

Information:
I use fenom as template engine in chunks.
The main template assigned to fred is next
![image](https://user-images.githubusercontent.com/12915348/54393323-eb79cc00-46ba-11e9-8912-b730dfbcaec7.png)

ОS: Ubuntu Server Edition
Apache:2.4.10
MySQL:5.7.21-20-beget
PHP: 7.2

I thought the problem is in the cache.
What I've tried to do.
I delated HTML markup created with Fred. For this I change template to default
![image](https://user-images.githubusercontent.com/12915348/54392086-c2a40780-46b7-11e9-9c64-328e94bad1e9.png)
And after double saving I tested page - it shown well.
But after return template to Fred template HTML murkup return back end the result  like I didn't delete content.
![image](https://user-images.githubusercontent.com/12915348/54392672-51fdea80-46b9-11e9-9962-35ca2bfadf98.png)

Why? I cleaned ceche too.
And the page don't whant to load still.

Browser Consol log
![image](https://user-images.githubusercontent.com/12915348/54392748-7659c700-46b9-11e9-8f8a-728f3f213be1.png)
MODX hasn't any logs

**Comment by matdave** [comment]
Have you recently updated Fred from an early beta build? Also, content.js is not a part of Fred, so it's possible that is playing a part in blocking Fred from working. What is content.js trying to do at line 328?

**Comment by Zidcov** [comment]
@matdave yes I have  fred-1.0.0-pl version.
about js - I see next
![image](https://user-images.githubusercontent.com/12915348/54395335-9b9e0380-46c0-11e9-9570-2fa31eb71b64.png)
Unfortunately I don't understend js

**Comment by rthrash** [comment]
Also, Fenom is not currently supported. We do have an open issue looking for someone with Fenom experience to help change that.

**Comment by Zidcov** [comment]
So, I will test it without fenom and write here
