### ISSUE TITLE
Some elements are repeated outside dropzone when rendered in Fred 

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#176]
It's only happening on one page and I haven't been able to work out what is causing it yet.

Everything works fine when logged out but when editing with Fred the bottom few elements in the dropzone are repeated once and using the browser inspector it shows they're rendered as sections outside the fred dropzone.

I'm able to give access to a site where it's occurring if you like.

**Comment by theboxer** [comment]
I'd prefer steps to replicate if you can figure them out, so I can debug it in my local env...

**Comment by digitalpenguin** [comment]
It seems to be to do with an iframe in an element. If I add it to the page, the elements below are rendered twice on load.
You can see the extra elements for a split-second just before the Fred wheel starts spinning and then the normal elements (including the ones already there) are loaded with the Fred dropzone.

**Comment by digitalpenguin** [comment]
Ugh - the iframe had an invalid character in the closing tag. (The code had been emailed).
My apologies - closing.

**Comment by theboxer** [comment]
No problem :) Glad that you figured that out
