### ISSUE TITLE
Pagination links not generated correctly while Fred active

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#177]
I'm using pdoPage in a blog listing element like this:
```
<div class="blog-listing" style="margin-top:{{margin_top}}px; margin-bottom:{{margin_bottom}}px;">
    [[!pdoPage?
        &parents=`19`
        &tpl=`blog_post_preview`
        &includeTVs=`listing_image`
        &processTVs=`listing_image`
        &where=`[[!TaggerGetResourcesWhere]]`
    ]]
</div>
<div class="pagination-nav">
    <ul class="d-flex justify-content-center">[[+page.nav]]</ul>
</div>
```

All works as expected when logged out of Fred.
When logged in, the pagination links are not generated correctly. It's just the base URL with the parameter on the end. e.g. example.com/?page=2 instead of the full path to the current page.

This could be related to the bug with the tagger links doing the same thing that was fixed.

**Comment by rthrash** [comment]
Fred doesn’t currently have any idea of what Fenom is, see #10. This could be in play, maybe?

**Comment by digitalpenguin** [comment]
I have fenom deactivated on this install - just using defaults. The same occurs if I swap it out with getPage too it seems.
Last time when @theboxer fixed the Tagger links, it was just a dev environment and only had three posts there so pagination hadn't come into play yet.

**Comment by theboxer** [comment]
@digitalpenguin could you please try changes from this commit if it'll solve the issue for you?
https://github.com/modxcms/fred/commit/12c474d484934232f06d4c7ba59c045eec4d0ae3

**Comment by digitalpenguin** [comment]
@theboxer Sorry to say it didn't fix the problem. After applying the changes I also deleted everything in the cache folder just in case; but no good.

**Comment by digitalpenguin** [comment]
I should note I applied the changes to 1.0.0-pl though, not the alpha, if that would make a difference.

**Comment by theboxer** [comment]
Can you check against getPage instead of pdoPage?

**Comment by theboxer** [comment]
Btw. I tried it with pdoPage and it also works fine...
This is the href value for the page link: `fred/?page=3&fred=1`

**Comment by digitalpenguin** [comment]
For me it adds the parameters correctly e.g. `?page=2` but it doesn't generate the URI.
So, if the resource were at the top level it would work, but the page where I have it is about two levels so it needs `example.com/path/here/?page=2` but it's only currently showing `example.com/?page=2`.

**Comment by theboxer** [comment]
I tried it again with child resource (even though the previous one wasn't site_start) and it works as expected. The link looks like this: `fred/child.html?page=2`

**Comment by digitalpenguin** [comment]
Unfortunately I'm still unable to get it to work. 
Is it possible it's because I applied the changes to 1.0.0-pl rather than the latest build?
Is there anything you recommend I look for in terms of debugging it?

**Comment by theboxer** [comment]
Could you try to test it against 1.1.0-alpha2 version that's here in github? I'm not sure why it works for me and not for you :/

**Comment by digitalpenguin** [comment]
Thanks I'll give it a go as soon as I can. (I'll need to put a copy of the site on a dev server first.)

**Comment by rthrash** [comment]
Any luck @digitalpenguin ?

**Comment by digitalpenguin** [comment]
Sorry I just realised the 1.1 build I tried to download was an older one and thus the link didn't exist anymore.
Did you have any luck with the dev account I sent through? 
I can install the later build from https://github.com/modxcms/fred/tree/master/_packages if you think that would be helpful?

**Comment by theboxer** [comment]
Hmm, I think I didn't get the credentials or I lost them... anyways, if you can try to install there the latest alpha build and try it again and let us know, that would be perfect.

**Comment by digitalpenguin** [comment]
Fixed with alpha3. Thanks a bunch @theboxer  :100: 

So it seems it was more than that single commit needed. Closing!
