### ISSUE TITLE
Toggle Type is not initialised to false

### ISSUE THREAD

**Issue by Zeroth007** [modxcms/fred#18]
I am trying to use the good practice of using a published settings for all Fred Chunks by using
data-fred-render="{{published}}" in the outermost div of the Chunk.

I am using a toggle in the options:
{ "settings":[
        {
            "name": "published",
            "label": "Published",
            "type": "toggle",
            "value": false
        }]}

But the published value is not initialised at false so the div still shows up outside of Fred.
I am finding that I have to manually set the toggle to on, then set if to off for the false value to be set.

**Comment by theboxer** [comment]
Hello,
it does set the default to false, but you're trying to output boolean false, which will always output as empty string. Adjust your element's template to use `data-fred-render="{{published ? "true" : "false"}}"`
