### ISSUE TITLE
Export and Import Elements and Option Sets

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#180]
While it's possible to collaborate on Themes using Gitify, it's a bit cumbersome to set up, and intimidating if you've never used it… 

Perhaps there could be a folder/structure for collaborating on Themes just using a simple repo and straightforward git push/pull commands. Perhaps it would have something like the following structure:

```
export-import/
  theme-name.json 
  assets/
  elements/
    category-names/
       element-names.html 
  option-sets/
    option-set-names.json
```

This would enable you to check out the theme in and work on it directly in an IDE or text editor. The `theme-name.json` file would have any metadata necessary for mapping things on an import.

**Comment by DESIGNfromWITHIN** [comment]
Yes would love this.

**Comment by JANogueira** [comment]
Also asked for this on the #157
