### ISSUE TITLE
Fred broken in IE11

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#184]
Fred js file doesn't work when enabled in frontend using Internet Explorer 11. Shows the following in the console:
```
SCRIPT5009: 'Promise' is undefined
File: fred.min.js, Line: 6825, Column: 25
```
IE11 doesn't support promises, needs a polyfill

Ver: 1.1.0-alpha2, IE11 on Windows 7

**Comment by theboxer** [comment]
Does the 1.0.0 version work in IE11?

**Comment by davidpede** [comment]
Just replaced my `fred.min.js` file with version 1 and appears not:
```
SCRIPT5009: 'Promise' is undefined
File: fred.min.js, Line: 6896, Column: 25
```

**Comment by davidpede** [comment]
The intention is to support IE11 right? Sure I read that somewhere when it was announced

**Comment by theboxer** [comment]
I'm just adding the https://www.npmjs.com/package/promise-polyfill, could you test it when I push that please?

**Comment by davidpede** [comment]
Sure

**Comment by theboxer** [comment]
I've sent you the file through slack, might be better to test it before I push it here :)

**Comment by davidpede** [comment]
Yep I'll msg there

**Comment by theboxer** [comment]
I wasn't able to resolve this in reasonable timeframe, so IE11 will stay in the unsupported browsers list for now.

**Comment by rthrash** [comment]
Hi @davidpede we made the tough call to only support modern browsers, and will be in the next update to the docs:

- Chrome 29 or later
- Firefox 28 or later
- Safari 9.0 or later
- Microsoft Edge
