### ISSUE TITLE
Parse error when I try FRED on localhost

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#188]
When vieuwing the homepage after setting FRED up I get this error:

`Parse error: syntax error, unexpected ':', expecting ';' or '{' in D:\Programs\wamp\www\anyshop.local\modx\core\components\fred\model\vendor\symfony\dom-crawler\Crawler.php on line 969`
Using Fred 1.0.0-pl

**Comment by theboxer** [comment]
Never experienced that, check out the Symfony's dom-crawler requirements or try the fred 1.0.0-alpha2.

**Comment by DESIGNfromWITHIN** [comment]
Updating to 1.0.0-alpha2 fixed it... thx
