### ISSUE TITLE
Specify or Exclude Fred Plugins by Element

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#198]
Proposed Docs/Spec below:

## Limiting Plugins for Elements

By default, all Toolbar Plugins will register for every Element. To specify the order and/or omit some plugins, modify an Element’s [Option Set](/themer/options/settings.md) setting to either include or exclude specific Fred Plugins with a  `plugins-include` or `plugins-exclude` attribute. 

**Note:** The plugins are unique names of the class created for the plugins. As a general rule, this should match the plugin name used for the MODX Package Provider. 

If a `plugins-include` attribute is included, it will ignore any `plugins-exclude` lines. To include only specific Plugins for an Element, use a `plugins-include` Options setting:

```json
{
  "plugins-include": ["gallery","mapmarker"],  
  "settings": [
    {
        …
    }
  ]
}
```

To exclude one or more specific Plugins on an Element, use a `plugins-exclude` option:

```json
{
  "plugins-exclude": ["fredfontawesome5iconeditor"],  
  "settings": [
    {
        …
    }
  ]
}
```

To prevent all Plugins from registering on an Element completely, specify an empty array for a `plugins-include` option:

```json
{
  "plugins-include": [],  
  "settings": [
    {
        …
    }
  ]
}
```

**Comment by theboxer** [comment]
Resolved in d641bcf627f3011eb893f9b6f43be0b6da757b35.
