### ISSUE TITLE
Alpha3 - Dialog pop-up asking if you're sure you want to leave the page

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#199]
Just testing out Alpha3 and I've noticed that whenever attempting to follow a link, a pop-up appears asking if you're sure in case you haven't saved. 
This happens every time even if nothing has been edited.

Is this a bug or a feature?
If a feature, is it technically possible to limit it to only happening if something has been changed and not saved yet? ( I understand that might be a tall order )
If not, perhaps a system setting to disable it?

**Comment by theboxer** [comment]
@digitalpenguin can you try the commit referenced in this issue if it will make better?

**Comment by digitalpenguin** [comment]
Working nicely with those changes. Cheers!
