### ISSUE TITLE
Feature Request: Fred element "OnElementSelect" event

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#202]
Hi All,

Sorry if I am not able to explain clearly the current point, but i am not a native English speaker. Please ask for more details if needed.

Here is the situation:
I am creating a form builder using Fred with multiple tabs (using fieldset block for each tab/step). So far so good.
The challenge I found is related with select boxes. Due to the render nature of this element, it is not possible to drag elements into it.

To workaround this situation, I created a block for the select field type, another block for the option field to be inserted inside the select element.
Then on the select field type block, I created an option set just to change the `select` into a `div` to allow dragging the `option` into the `div`. Once finished, I will have to switch back to `select` again.
Every option that I drag into the div needs to be selected so the block menu appears.
Then I will have to click on the configuration button to be able to change the text and the value, if the objective is to have different info on the visible text and value option attribute for the `option` tag.

This works properly, but I believe this can be simplified.

Here is a raw example (Assuming that there is already a block added with the form itself.

**select block**:
```
        <div class="col-lg-8 mx-auto text-center">
            <h5 class="section-heading" contenteditable="true" data-fred-name="field-head">Change field caption name</h5>
            
            <{{selectbox}} data-fred-dropzone="form-select" style="min-height:15px;background-color:#dddddd">
              
            </{{selectbox}}>
        </div>
```
**optionset for the above block**:
```
{
  "settings": [
    {
      "name": "selectbox",
      "label": "Select field mode",
      "type": "select",
      "options": {
        "select": "View Mode",
        "div": "Edit Mode"
      },
      "value": "select"
    }
  ]
}
```

**option block**:
`<option value="{{ select_text }}">{{ select_text }}</option>`

**optionset for the above block**:
```
{
  "settings": [
    {
      "name": "select_text",
      "label": "Option Text",
      "type": "text",
      "value": "Change me"
    }
  ]
}

```

Here is my suggestion:
- It would be very interesting to have a way to trigger an event like "OnElementSelect" where it can apply a change to allow type switch on this event trigger (or any other kind of change for a use case like this);
- For the option tags, maybe have a quick way to change value and text inside `option` tag like happens today with image alt and title attributes;

Sorry if I am double posting this, but I couldn't find anything similar to this on the improvements list.

Thanks in advance for your feedback and many thanks for this fantastic plugin.
J.Nogueira

**Comment by rthrash** [comment]
Hi @JANogueira and thanks for providing so much info. I look forward to seeing your form builder when you finish. 

Can you capture a screen recording of what you're trying to accomplish? I think that may help us understand what you're trying to accomplish better. Thanks!

P.S. Any plans to share your form builder when it _is_ done?

**Comment by theboxer** [comment]
I'm not sure I understand what you are requesting. Don't get when the OnElementSelect even should fire.

Also from the scenario you are describing and task you are trying to complete, I'd say that toolbar or maybe sidebar plugin would be a better fit, instead of adjusting the element tag for different scenarios...

**Comment by matdave** [comment]
Alternatively, for your select box option set, you could have a comma separated field which you pass to a snippet that builds all your available options out.  E.g. 
```
<select>[[buildOptions?options=`{{ options }}`]]</select>
```

**Comment by JANogueira** [comment]
Hi All,

here is the video with the situation I am trying to explain:
[![](http://img.youtube.com/vi/4YDBY_AfjkI/0.jpg)](http://www.youtube.com/watch?v=4YDBY_AfjkI "")
