### ISSUE TITLE
Skip & Exit Nested Drop Zones

### ISSUE THREAD

**Issue by matdave** [modxcms/fred#203]
The current behavior of the down/up arrow is to enter a nested dropzone, which can be tedious on complex designs. I propose we have a secondary function key, cntrl/cmd + click that allows you to skip an element with a nested drop zone and quickly exit a nested drop zone if currently within one.

**Comment by digitalpenguin** [comment]
What do you think about having the up and down arrows ignore nesting and only stay at the same level?
The element could be dragged into another element for nesting if needed. 
At the moment elements can disappear from view if using something like tabs where parts are hidden.

**Comment by sottwell** [comment]
That would be nice, but I can see how it could be difficult to arrange, there are so many possible permutations. You could want to move an element out of a dropzone, move an element into a dropzone, move an element across a dropzone staying in its own level....
