### ISSUE TITLE
Include Client Config Groups and Settings in a Fred package

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#205]
I think it will be crucial to have pre configured theme for Fred.
This means Context Settings and of course better Client Config.

Can I somehow include Client Config settings and default values?
And have the Client Config fields not be overwritten by theme updates if the user changed them?

**Comment by rthrash** [comment]
Internal discussion for this would be for system settings under a namespace with a specific key, e.g., `fred.themename.*` will get bundled at build and ship with the themes. Fred theme will also create the namespace when you add a Theme in the Manager 3PC. A UI for editing the values for the front end will need to be developed.

**Comment by DESIGNfromWITHIN** [comment]
that would be perfect, will adjust my settings.

Any ETA on this possible?
I am thinking of moving settings to a *settings* resource first so that I can het the theme live soon....

**Comment by rthrash** [comment]
Check out the last commit, Menno. Docs forthcoming.

**Comment by DESIGNfromWITHIN** [comment]
Thx, just not sure how to use it... Will wait for the next build and docs.
