### ISSUE TITLE
I you have a image in a element and remove the image you cant get it back

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#206]
I you have a image in a element, and fill it with a placeholder image it shows on frontend.
If you now replace the image with a new one it works.

Now remove the image (empty img path) the image section filed is gone and you cant get it back...

`<img src="http://via.placeholder.com/900x900" data-fred-name="hero_image" data-fred-media-source="Uploads"> `

**Comment by rthrash** [comment]
@DESIGNfromWITHIN did you click the folder icon next to the image input? That loads the image picker, too.

**Comment by rthrash** [comment]
Hi @DESIGNfromWITHIN were you able to test the folder icon, or is there another way to reproduce this?

**Comment by rthrash** [comment]
Closing this issue due to lack of feedback. Please reopen if the issue still remains. Thanks!
