### ISSUE TITLE
Missing delete icon in toolbar for "Fred Editor" user.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#207]
A client of mine has an account that uses the Fred Editor policy. It looks like the delete element icon is missing from the toolbar when they hover over it.
I've switched them to the Fred Admin policy for the web context for now which works. I'm assuming it's a certain permission which is blocking it. 
It's not immediately clear which one though. Any ideas?

**Comment by theboxer** [comment]
Sorry, seems like this bit is missing from the docs. The permission you want to allow on the non-mgr context is `fred_element_delete`

**Comment by rthrash** [comment]
Will add a new policy specifically for front end use and add this.

**Comment by theboxer** [comment]
Added `fred_element_front_end_delete` policy.
