### ISSUE TITLE
Feature Request: Fred Sidebar Plugin, give Elements an onClick = options

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#209]
As title says,

Would be useful for a and buttons tags, but I could see this being useful for more types of tags.

**Comment by kars-springbok** [comment]
Well currently in Elements.js there is:
`export const a = (content, title = '', href = '', classes = [], onClick = null) => {`

And I really like the way you can provide the content, title etc.

It would be really good to do just: 
`const aTag = pluginTools.ui.els.a('content', 'title', 'href', 'class', 'onClickEvent()');`

**Comment by kars-springbok** [comment]
It could be that it is already implemented, however I didn't get it to work. so I'm unsure what the onClick = null does in the Elements.js

**Comment by matdave** [comment]
Anchors and Button tags already have click functions, it just needs to be formatted as 
```
 const aTag = pluginTools.ui.els.a('content', 'title', 'href', 'class',() => { this.onClickEvent(); });
```

**Comment by matdave** [comment]
onClickEvent
