### ISSUE TITLE
Feature Request: Fred Sidebar Plugin, ability to give sidebar Title a class

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#210]
Would be really useful in order to style Fred a bit better. 

1 Tab could have a different Title styling compared to another tab for example.

**Comment by kars-springbok** [comment]
```
static title = 'Title Tab';
static titleClass = 'specialTab__className';

static icon = 'icon';
static expandable = true;
```

Just a simple static variable will do. Maybe even extent it towards it having more values? So people can even change the tag from h3 to h4, or just a p tag and use it as a description about the tab.

**Comment by theboxer** [comment]
The answer is mostly same as for the #211, we're trying to keep the sidebar plugins feel & look same for everyone, so no, there probably won't be a custom class for a title.
