### ISSUE TITLE
Feature Request: Fred Sidebar Plugin, ability to add a Description

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#212]
We have static title = TITLE NAME

However it would be really useful to have a set parameter to insert a description in. Instead of having to write a function, generating a field and appending it to the fields and render it.

**Comment by theboxer** [comment]
None of the current sidebar items don't have description -> fred itself doesn't support it right now, so that's why it's not available in plugins as well. Once Fred will support it, it'll get available for plugins.
