### ISSUE TITLE
Feature Request: SidebarPlugin | Allow the use of all tools used by Elements.js

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#219]
Would be great to be able to mimic all the functions from the core code. 

Such as: drake, hoverintent etc. This would allow us to create our own sidebars including a more advanced Elements sidebar, and allows us to add an additional layer on top of the default Elements, but in our own Sidebar Plugin.

**Comment by theboxer** [comment]
Added few more libs like: hoverintent, Choices, flatpickr, ColorPicker and noUiSlider.

Drake however won't go there, if you have a need for advanced features for elements, feel free to submit a PR to the core.
