### ISSUE TITLE
Error: No fingerprint was provided.

### ISSUE THREAD

**Issue by reikotec** [modxcms/fred#22]
I have the Issue that when I want to change the Template of a Ressource from a Fred to a Non-Fred Template, MODX says "Error: No fingerprint was provided."  I tried by updating normally and per Quick-Change. 

_**Once a Fred Ressource always a Fred Ressource...**_

Is that a bug, or how can I fix this problem?

**Comment by theboxer** [comment]
Could you try and adjust Fred's plugin and add following code after this line: https://github.com/modxcms/fred/blob/master/core/components/fred/elements/plugins/Fred.php#L215
```php
$templates = array_map('trim', $templates);
$templates = array_flip($templates);
if (!isset($templates[$resource->template])) return;
```

Please let me know if it solved the issue for you and it will be included in next release.

**Comment by reikotec** [comment]
I'm sorry, still the same Problem. :(

I guess the Problem is that Fred is still loaded when it's not a Fred Page.

**Comment by theboxer** [comment]
I'm not sure I understand, there's no chance fred could be loaded when it's not a Fred Page. If you still see Fred on frontend, it means you are still using fred's template on the resource.

When you apply the code above, you should get rid of the `Error: No fingerprint was provided.` error and change template successfully. At least it worked in my env.

If it still doesn't work for you, you can create me a user and email me creds to john@modx.com and I'll take a look at it when I'll have a moment.

**Comment by reikotec** [comment]
If it helps, I also get the `Error:  Code: 0 communication failure undefined` when saving a Fred Page in the Backend / Manager.

**Comment by rthrash** [comment]
Hi @reikotec—please create a sudo Manager user for john@modx.com and email him the credentials to investigate. Thanks!

**Comment by reikotec** [comment]
I created a user at our test system. Enjoy! :)

**Comment by theboxer** [comment]
No issue there, switched the template on your test Resource to the non-fred one without an issue -- after updating the fred's plugin as instructed here.

**Comment by reikotec** [comment]
Oh, i am such an Idiot.
Edited the Code in core/components/fred/elements/plugins/Fred.php instead of directly in the Plugin. _\*facepalm\*_

Sorry for your time and **thank you very much! You safed my day!**

**Comment by theboxer** [comment]
lol, no problem :) The fix will be included in the next build as well.
