### ISSUE TITLE
Update overall Fred styling

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#223]
Update the styles to be more in line with the upcoming MODX3 Manager:

- [x] Get rid of blue everywhere in favor of white panels/Element settings (blue sidebar to MODX3 blue color)
- [x] Put Element names in a pill (omit if the Element is too narrow)
- [x] Move the plethora of toolbar icons, which are less frequently used, to a tooltip menu. Clicking the cog/gear icon will still trigger Element setting but hovering it will reveal the tooltip menu.
- [x] Move the create page button to header row
- [x] Move the create blueprint button to header row … and deal with blueprint category creation… 
- [x] Make text headers, labels and inputs line up vertically and improve the visual hierarchy of section headers, labels, and inputs
- [x] Fix the preview viewport heights
- [x] Update sidebar action button styles to emphasize save action (ghost buttons for preview/cancel)
- [x] Blueprint icon to solid version
- [x] Tagger review
- [x] Collections review
- [x] FA Icon picker review
- [x] Image picker review
- [x] choices line-height and general styling review (Blueprints > Create, Tagger)
- [x] image-group alignment and review
- [x] remove slide-in for Element toolbars with consistent styling for name/controls pills

**Comment by rthrash** [comment]
Safari no longer creates flyouts when clicking on groups or advanced settings "tabs". Work going on in the `styles` branch.

**Comment by rthrash** [comment]
Responsive previews are full-height for the phone/tablet screens. The height on the iframes style attributes set by code like `this.iframe.style.height = '480px';` in index.js is getting overridden by the `.fred .fred--content-preview iframe ` height calculation/style:

```
iframe {
    -webkit-transition: height 240ms ease, width 240ms ease, margin 240ms ease;
    -moz-transition: height 240ms ease, width 240ms ease, margin 240ms ease;
    -o-transition: height 240ms ease, width 240ms ease, margin 240ms ease;
    transition: height 240ms ease, width 240ms ease, margin 240ms ease;
    -webkit-transform: translate3d(0, 0, 0);
    position: relative;
    background-color: #FFF;
    width: 100%;
    height: calc(100% - 51px) !important;
    display: block;
    margin: 51px auto 0;
  }
```

**Comment by rthrash** [comment]
Collections needs new icon-mask treatment, and possibly moving tabulator into the core Fred distro? Overrides for tabulator CSS are now in `_utility.scss`. Also, the "New Page" button needs to go into top row/header.

**Comment by rthrash** [comment]
Collections:

- [ ] Add a wrapper around the buttons and position them in the head
- [ ] Add `fred--btn-small` to the button
- [ ] For cancel, make it "or [cancel]()" text/link

<img width="512" alt="MODX Revolution 2019-06-05 13-27-57" src="https://user-images.githubusercontent.com/234237/58980363-c4043e00-8795-11e9-86c3-7f3c29bc8e21.png">

**Comment by matdave** [comment]
@theboxer can you refactor the Blueprints to work more like the Create Page system? I didn't realize how differently written they were, which is making it kind of difficult to turn the "Create Blueprint" into a (+) like the Create Page system.

**Comment by rthrash** [comment]
Finalized with John's commit, earlier, so closing.
