### ISSUE TITLE
Feature Request - Placeholder Groups

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#224]
Say you have an element where you have a lot of potential class names that are added via placeholders. It could be good to group the output of all the placeholders into a single "group placeholder".
For example, here's a Bootstrap4 alert:
```
<div class="alert {{alert_type}} {{margin}} {{mx}} {{my}} {{mt}} {{mr}} {{mb}} {{ml}} {{border}} {{bt}} {{br}} {{bb}} {{bl}}" role="alert" data-fred-name="alert">
  A simple primary alert—check it out!
</div>
```
There are a whole heap of placeholders yet it's really just margins and borders. Most of these placeholders wouldn't have values most of the time.

With a group placholder, the element markup would be something like:
```
<div class="alert {{classes_placeholder}}" role="alert" data-fred-name="alert">
  A simple primary alert—check it out!
</div>
```
My line of thinking is it keeps the markup cleaner for an end user who might buy a theme made with Fred and wants to change some of it.

What do people think? It's just an idea and there may of course be far better ways of dealing with it.

**Comment by theboxer** [comment]
I'm probably not a fan of the grouped approach.
- In the template you can see on the first look what settings are beeing used
- The grouped approach would most likely require a PHP logic to construct the variable, which would mean you'd have to render all elements through XHR request, which IMO is unnecessary

**Comment by rthrash** [comment]
I get where you’re coming from, but tend to err on the side of not at this time. There are a lot of other areas that need attention before this.

I do wonder, however, what the processing order is? If Snippets or Chunks are processed first then there’s a solution there.

**Comment by digitalpenguin** [comment]
Yeah fair points! I'll close this one for now. :)
