### ISSUE TITLE
Feature Request: Saving TVs

### ISSUE THREAD

**Issue by reikotec** [modxcms/fred#23]
I'm not sure if it's possible or already planned that Template Variables can also saved via Fred (maybe via `data-fred-target`). In my most Templates I'm using a Header-Image and on Parent Pages the Header-Image are used as Thumbnails. It would be great if I haven't to edit the TVs seperate in the Manager.

Example in Fred: You can simply click on the Header-Image and edit it like the other Images in Fred. But the Image Path is saved in the TV.

**Comment by theboxer** [comment]
Hello @reikotec,

this is planned feature, but thank you for requesting it here, so we know it's also wanted from others :)

**Comment by theboxer** [comment]
Will be included in next release.
