### ISSUE TITLE
fred_element_front_end_delete only works when user is sudo

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#235]
Hi,

I am using fred 1.1.0 beta2 and created a new user group with Fred Editor permissions.
This permission model has the fred_element_front_end_delete that was implemented on 1.1.0 (#207), but the user never "sees" the delete button.

No matter if I apply Fred (Admin), or assign the user to Admin group + Fred (Admin).
The user will only see the delete button on fred element bar Only when the user is set as sudo.

**Comment by digitalpenguin** [comment]
I don't think it's limited to sudo. I could get the delete option to appear if the user was set to the Fred Admin policy too.
Referenced issue: ##207

**Comment by JANogueira** [comment]
Strange, I couldn't. And I tested with a lot of different configurations, including set the user to admin group and Fred admin.
Not even like this I managed to have the delete button appearing.
Only after setting the user as sudo.

**Comment by JANogueira** [comment]
Just to be sure, made another test today:
Installed fresh modx 2.7.1, installed fred 1.0.0 along with all dependencies and installed 1.1.0 beta2 (package upload and install).
Now here are the steps that I used to reproduce the problem:
1 - Went to ACLs, created a new user role with authority of 9998;
2 - Created new user group: context: Manager policy: Fred Admin;
3 - Created the user and assigned to the group and role.
4 - Went to the frontend, fred loaded, everything works, except the Delete block button;

**Comment by digitalpenguin** [comment]
What about if you add the Fred Admin policy to a user group on the web context?

**Comment by JANogueira** [comment]
@digitalpenguin , sorry about my previous comment.
The correct info regarding point 2 should be:
2 - Created new user group: context: Web; policy: Fred Admin;

Sorry for the typo (Corrected the post)

**Comment by theboxer** [comment]
@JANogueira please apply the change in the commit above to resolve the issue. Thank you for noticing it :)

**Comment by JANogueira** [comment]
Excellent! Many thanks!!
This came at very good time.

Cheers

**Comment by JANogueira** [comment]
Hi John,

Applied the change, but no go unfortunately.
The javascript still delivers this option set as 0
![Capture](https://user-images.githubusercontent.com/22750391/58964237-793ef200-87a6-11e9-9a1d-77c8a7a4249f.PNG)

Searched for the old wrong string, but nothing was found.
By checking the permission map, fred_element_front_end_delete is selected (true).

I already cleared browser cache, but still remains the same problem. Value delivered to the browser as 0.

**Comment by JANogueira** [comment]
Hi again John,

Please disregard my last comment.
Remembered now that the plugin is not mapped to the static file.

By changing this on the plugin itself solved the problem (of course! :D )
![image](https://user-images.githubusercontent.com/22750391/58964876-8b6d6000-87a7-11e9-8af1-620812df0d1b.png)

Cheers and many thanks once again!

**Comment by theboxer** [comment]
hah, glad you sorted it out :)
