### ISSUE TITLE
Allow lexicon call on Option Sets

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#241]
Hi,

I am not sure if this already exists or is in the works, but I couldn't find it. Here is my suggestion:
It would be very interesting to have a way to use lexicon calls on fred option sets for labels.

Here is the main idea for this proposal:
A site with 3 different languages (based on contexts: French, Spanish and English) and the content update will be made by a localized teams (Spanish variant updated by Spanish people, French variant updated by French people, etc).
The French content updater might not speak/understand English or the Spanish content updater might not speak English as well.

By having the possibility of using lexicon calls on option sets will help to widen the use cases for Fred.

**Comment by theboxer** [comment]
Hello,

this is actually already possible. You can use the lexicon key as the label, for example: `"label": "fred.fe.element_settings"` will output `Element Settings`.

You just have to make sure that the lexicons are loaded on the front page. To load lexicons you can either use [FredBeforeRender](https://github.com/modxcms/fred/blob/master/docs/developer/modx_events.md#lexicons) event or do it on your own.

**Comment by JANogueira** [comment]
Many thanks John.
Cheers

**Comment by JANogueira** [comment]
Hi John,

This actually works if we are using Fred lexicon files from fred folder on core/components/fred/lexicon.
How can I use translations from my project from different namespace without touching Fred files?

I have my structure like this:
/assets/themes/project_name/lexicon/en/fred.inc.php

Of course using different folders for the remaining languages (french, portuguese, etc).
The themes folder is the default fred folder.

Can we have Fred looking into default theme under the folder lexicon for the fred.inc.php or similar in order to append custom lexicons?

Thanks in advance.

**Comment by theboxer** [comment]
You want to use different translations for Fred itself, or just translations for your site?

**Comment by JANogueira** [comment]
For the site itself for my own option sets (labels)

**Comment by theboxer** [comment]
You'll have to create a plugin to load your lexicons. Fred can't do that for you, as Fred won't initialise for most of your users/visitors.

**Comment by JANogueira** [comment]
Oh but the idea is to have only for the content editors for the element option left menu

**Comment by theboxer** [comment]
In that case you need a plugin anyways :) But you'll need to hook it up on `FredBeforeRender ` event. And add lexicons you want to load as described here: https://github.com/modxcms/fred/blob/master/docs/developer/modx_events.md

**Comment by JANogueira** [comment]
Many thanks again John. I will give it a try.
Cheers

**Comment by JANogueira** [comment]
Hi John,

Just to let you know that worked like a charm! I can now use my own translations for the labels of each optionset.
Here is the plugin code that allowed me to load custom fred lexicons for the optionsets:

```

<?php
/*
 * Plugin to be used with FredBeforeRender in order to load custom lexicons
 * This example was taken from the documentation:
 * https://github.com/modxcms/fred/blob/master/docs/developer/modx_events.md#fredbeforerender
*/
 
$lexicons = ['theme_namespace:fred'];

$modx->event->_output = [
    'lexicons' => $lexicons
];

```

The optionset part;
```

{
  "remote": true,
  "settings": [
      ...
    {
      "name": "bigheader_background_image",
      "label": "fred.bigheader_background_image",
      "type": "image",
      "mediaSource": "Project",
      "value": "{{theme_dir}}images/home/image_banner.png"
    },
      ...
  ]
}

```

And the lexicon file:
```

<?php
/**
 *
 * @package Project_name lexicon for Fred optionsets
 * @language pt
 */



$_lang['fred.bigheader_background_image'] = 'Imagem de fundo';


```

Unfortunately I couldn't make it work on other kind of labels, like these select options labels:
```

    {
      "name": "bigheader_titles_box_bkgd",
      "label": "fred.titles_box_color",
      "type": "select",
      "options": {
        "banner-home-blue": "fred.bigheader_background_color_blue",
        "banner-home-grey": "Grey",
        "banner-home-darkgrey": "Dark Grey"
      },
      "value": "banner-home-blue"
    }

```

Do you think I can suggest this as an improvement for the Fred 1.1.0 pl milestone for select, colorswatch, etc?

Many thanks in advance

**Comment by theboxer** [comment]
I'll take a look at these.

Btw. I'd recommend using your theme as a prefix and not fred, to avoid potentially overwriting fred lexicons - `your_theme.fred.bigheader_background_color_blue` or `your_theme.bigheader_background_color_blue` instead of `fred.bigheader_background_color_blue`

**Comment by JANogueira** [comment]
Thank you for the tip. I'll follow your tips.
Many thanks once again!
