### ISSUE TITLE
Site tree panel unusable

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#245]
Experiencing some problems with the site tree panel.

The hitzone of parent resources is very buggy. The first sibling is fine but following sibling parents are not working UNTIL the first is expanded. Can't expand them and can only open the edit panel by clicking the far right:

![2019-06-17_10-16-52](https://user-images.githubusercontent.com/825106/59593251-7ff43000-90e9-11e9-8f16-2479c83ec94b.gif)

Also the buttons seem to overlap slightly and titles are not centered - padding to small on bottem edge.

Using Chrome & latest master branch as of today

**Comment by rthrash** [comment]
Hi @davidpede, thanks for the reports. Can you update to the latest-latest `master` branch (as of a few minutes ago) and force-clear your cached CSS/JS to see if these are still reproducible?

**Comment by rthrash** [comment]
Also for reference, you'll need to `npm run build` to create the latest CSS and JS.

**Comment by davidpede** [comment]
No difference @rthrash I'm afraid

**Comment by davidpede** [comment]
FYI I've found the cause - will send pr later
