### ISSUE TITLE
Element settings button not working

### ISSUE THREAD

**Issue by davidpede** [modxcms/fred#246]
In the frontend, clicking the settings buttons in nested elements closes the hover transition instead of opening the settings panel:

![2019-06-17_10-30-51](https://user-images.githubusercontent.com/825106/59594241-6358f780-90eb-11e9-81dd-1f613107c918.gif)

Using Chrome & latest master branch as of today

**Comment by davidpede** [comment]
More strange behavior

![2019-06-17_10-36-30](https://user-images.githubusercontent.com/825106/59594515-e2e6c680-90eb-11e9-8439-3f265d7eb859.gif)

**Comment by theboxer** [comment]
This is for sure not beta2

**Comment by davidpede** [comment]
> This is for sure not beta2

Arg sorry your right - its latest master branch as of today

**Comment by rthrash** [comment]
Hi David, thanks for the reports. Can you update to the latest-latest `master` branch (as of a few minutes ago) and force-clear your cached CSS/JS to see if these are still reproducible?

**Comment by davidpede** [comment]
No difference @rthrash except a slight opacity change on the buttons. Behavior above is still happening

**Comment by rthrash** [comment]
Hi @davidpede, having trouble reproducing this behavior. Can you supply your Dropzone and Elements templates so we can investigate further? We're considering this the last blocker to beta4 release. Appreciate your digging into this with us. :)

**Comment by rthrash** [comment]
Also, which browser are you using?

**Comment by davidpede** [comment]
Using latest Chrome. This problem feels very similar to: https://github.com/modxcms/fred/issues/160

Elements in demos above have bootstrap flex column classes applied like:
```
<div data-fred-block-class="col-{{ col }} mb-3" data-fred-name="text" data-fred-rte="true">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet justo sit amet augue imperdiet aliquet vitae sed enim. Curabitur nec sem ex. Aenean suscipit ultrices sapien eu euismod. In sit amet massa elit.</p>
</div>
```
Dropzone in Tpl like:
```
<!-- Page content -->
<div class="page-content container-fluid">
    <div class="row">
        <!-- Main sidebar -->
        [[$sideBarLeft]]
        <!-- /main sidebar -->
        <!-- Main content -->
        <div class="col-9">
            <div class="outer-dropzone" data-fred-dropzone="content" style="min-height: 250px;">
                [[*content]]
            </div>
        </div>
    </div>
    <!-- /main content -->
</div>
<!-- /page content -->
```

**Comment by davidpede** [comment]
@rthrash TBH I'm struggling to reproduce this consistently now, certainly happening a lot less with latest master branch.

Seems to occur occasionally on layouts with lots of small elements where the settings cog overlays other elements - and when quickly clicking on the cogs. Might be the state hasn't caught up as the slide in transition hasn't quite finished. It never happens when the cog is inside its own element boundary so could be the overlay is causing problem.

Doesn't feel bad enough to block beta-4. No one else has reported it so maybe close this and if still an issue for our users then I'll try work it out and report back here.

**Comment by davidpede** [comment]
@rthrash found how to reproduce, its when you click on editable text. With an element like this:
```
<div data-fred-block-class="col-{{ col }} mb-3" data-fred-name="text" data-fred-rte="true">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet justo sit amet augue imperdiet aliquet vitae sed enim. Curabitur nec sem ex. Aenean suscipit ultrices sapien eu euismod. In sit amet massa elit.</p>
</div>
```
1. hover over the element
2. click its setting cog
3. works fine

Now try:

1. hover over the element
2. click/select the editable text
3. click its setting cog
4. closes the toolbar buttons instead of opening settings

![2019-06-21_10-47-06](https://user-images.githubusercontent.com/825106/59914597-9b757880-9412-11e9-808c-41191bc72306.gif)

Can you reproduce?

**Comment by rthrash** [comment]
Hi @davidpede we'll work on this one for a future bug release. Thanks for doing the research on repeating it.
