### ISSUE TITLE
TinyMCE toolbar only appears for the first element on a page.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#248]
In 1.1-beta2 the TinyMCE toolbar will only appear for the first element in a dropzone.
If I add a second element or duplicate the first, the toolbar does not appear when text is highlighted in the added elements.

My markup for the element is:
```
<div data-fred-block-class="team-block">
    <div class="team-text">
        <div class="name">
            <h3 data-fred-name="team-member-name">Team Member's Name</h3>
        </div>
        <a class="read-more-link" data-toggle="collapse" href="#team" role="button" aria-expanded="false" aria-controls="team"></a>
        <div class="text collapse" id="team" data-fred-name="team-member-text" data-fred-rte="true">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur molestie magna risus, sed dictum libero aliquet fermentum. Nullam nec elementum metus, ac scelerisque neque. Aenean accumsan at nisi id gravida. Integer in nisi mauris. Sed dapibus urna sit amet ex auctor.</p>
            <ul>
                <li>Nulla euismod ornare nunc</li>
                <li>Venenatis accumsan ligula placerat vitae.</li>
                <li>Donec semper sit amet</li>
                <li>Sed lacinia sem ac odio</li>
                <li>Ut quam leo</li>
                <li>Ringilla non tempus sed</li>
                <li>Consectetur eu nisi</li>
            </ul>
        </div>
    </div>
    <div class="head-shot">
        <img src="/assets/themes/site/images/therapists/teammember.jpg" data-fred-name="portrait" title="Team Member's Name" alt="Team Member's Name" data-fred-image-mediasource="Content" data-fred-attrs="alt,title" />
    </div>
</div>
```
Update:
If I have two of the elements in the dropzone, and then I reorder them so the first element is at the bottom and the second element is at the top, then the first element at the bottom is the only one where the TinyMCE toolbar works.
However, if I save the page and then reload, then the element which is now at the top is the only element where the toolbar works again.

**Comment by digitalpenguin** [comment]
It is because of the id attribute on the same div.
The reason there's an id is because I was using some javascript to add an index integer to the end of the id "team" on load. 

Everything works if I remove the id value and just leave the id attribute blank. e.g. `id=""`
I refactored the js to account for it.

If this is expected behaviour, feel free to close. Thanks!

**Comment by theboxer** [comment]
you can't have elements with duplicate ids on the page, so yes, it's expected behaviour.

**Comment by digitalpenguin** [comment]
OK no problem! 
I'll write up a forum post about how to get around this issue when ids are required in the element.
