### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Sparker232** [modxcms/fred#251]
I'm trying to install the latest commit into my MODX project. I've cloned the project and installed with `npm install`. Am I missing a step somewhere?

Thanks

**Comment by matdave** [comment]
Have you followed the prerequisites from the Readme? https://github.com/modxcms/fred#prerequisites-for-developing-for-fred

**Comment by rthrash** [comment]
Thank you for taking the time to file an issue, but we're going to close this due to lack of response and not being able to reproduce. Please reopen it if the full instructions don't make it work (or get the latest build sometime tomorrow from here: https://github.com/modxcms/fred/releases)
