### ISSUE TITLE
.fred--toolbar-plugins overflowing viewport

### ISSUE THREAD

**Issue by alienbuild** [modxcms/fred#253]
### Subject of the issue
When clicking the settings icon on an element the .fred--toolbar-plugins menu can appear out of the viewport, without awareness of the viewport boundaries.

### Your environment
PHP 7.1
MODX 3 (clean install)

### Steps to reproduce
Create an empty template with just a dropzone, a small h1 element and drop it in. Proceed to hover over the element.

### Expected behaviour
Menu to respond to the viewport ie: show the menu under the cursor if the menu will overflow above and visa versa.

### Actual behaviour
Menu appears off screen.

![menu-overflow](https://user-images.githubusercontent.com/32590877/60042199-0fcf4680-96b5-11e9-9c90-a02144d2003c.jpg)

**Comment by matdave** [comment]
We've adjusted toolbar behavior.
