### ISSUE TITLE
Error creating partial blueprint

### ISSUE THREAD

**Issue by alienbuild** [modxcms/fred#254]
## Subject of the issue
Loading screen hangs when attempting to save partial blueprint from element.

## Your environment
PHP 7.1
MODX 3 (clean install)

## Steps to reproduce
Create a small element such as a `h1` and place it into the dropzone. Click the settings icon and click to create a partial blue print. Fill out a name and save.

## Observed behaviour
Nothing happens and console throws errors. Screenshot attached.

![partial-blueprint-error](https://user-images.githubusercontent.com/32590877/60045871-d8b16300-96bd-11e9-98a7-f2f4e0c15bd6.jpg)

**Comment by theboxer** [comment]
Blueprint category is a required param. I'll fix it to show a proper error, but you have to create a blueprint category first.
