### ISSUE TITLE
[Fred Documentation] Elements attributes data-fred-class description not accurate

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#259]
Hi,

I found that the data-fred-class description is reporting exactly the opposite of what is actually happening when using it.
https://github.com/modxcms/fred/blob/master/docs/themer/elements/attributes.md#data-fred-class

The description has a missing _not_:
Where it reads:

> The value of this attribute will be added to class for this element only when Fred is loaded.

should be:

> The value of this attribute will be added to class for this element only when Fred is **not** loaded.

**Comment by rthrash** [comment]
Thanks for the catch. Fixed in a pending commit.
