### ISSUE TITLE
Screenshots sometimes are blank or almost empty

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#261]
With the 1.1.0-beta4, screenshots sometimes are blank or almost empty.
No errors or other issues but can't get good screenshots for any element except the hero (first one)

**Comment by matdave** [comment]
does this mostly happen on elements that are recently placed, or does it persist after a page reload? I've had this happen a few times, but just had been chalking it up to the limits of the 3PC screenshot tool with handling complex CSS.

**Comment by DESIGNfromWITHIN** [comment]
Its not too complex and cached is empty and refreshed...
Not a huge issue making screenshots anyway.

**Comment by theboxer** [comment]
Making screenshots relies on `html2canvas` lib. We can't do anything about it not generating a screenshot for you. Unfortunately it has it's own limitations.
