### ISSUE TITLE
Fred as a Orchestrator/Composer package – Feature Proposal

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/fred#263]
At my company we are looking to convert a number of custom themes to Fred. As we have been using Composer and Blend Migrations as much as possible. The goal would be to have both Fred as a composer package and keep Fred as a traditional MODX extra. The composer package would extend Orchestrator and it allows a way to install Fred via composer and build some automation features for CLI users.

> Note I am the author of [Orchestrator]( https://github.com/LippertComponents/Orchestrator) and if this proposal seems worthwhile to the project I would like to complete this as a PR it in the next few weeks.

### My PR will have:

1. Move the core/components/fred/model/composer.json file to be at the root of the project. Rename the name to have a value of modx/fred – should use lower case see: https://packagist.org/about#naming-your-package
2. Optional but I would really like to make the classed psr-4 https://www.php-fig.org/psr/psr-4/ with namespace MODX/Fred. Review if core/components/fred/ can be moved to src/.
3. Create /src/database/migrations directory and create an install migration for v1.1
This will allow the project to be installed and updated via command line tools and allow easy deployments from dev to staging to production environments. 
4. Create CLI commands for Fred like Build

### Fred Maintainers 
1. Fred will need to Submit project to https://packagist.org/
~~2. Fred will need to change how releases/tags are done, they should just be the PHP files as they are and a compiled JS/CSS finished version. Maybe the MODX packaged release can be tagged like `modx-1.1.0` and composer packages like `v1.1.0`~~

## Potential other issues or related work
1. I plan to have better updated docs for Orchestrator in the near future
2. Git-Package-Management may need some adjustments
3. Future composer tagged releases of Fred, 
If a Fred release has any DB changes then that release will need a new update Blend migration. These are generally quick and easy to create.

What I am looking for before I begin this coding this PR is some feedback from Fred creators and maintainers if this PR would be accepted or strongly considered assuming it meets quality expectations.

**Comment by rthrash** [comment]
Hi Josh. Let's set up a call to discuss this as it has fairly major implications on maintaining/developing Fred moving forward.

**Comment by rthrash** [comment]
What updates to GPM would you foresee?

**Comment by jgulledge19** [comment]
@rthrash I am closing this as I now will not be able to commit the time needed to complete. But I did add a way to install and require MODX Transport Packages via Orchestrator and Blend Migrations. I don't have great notes on this yet. See change log for limited docs: https://github.com/LippertComponents/Orchestrator/blob/master/CHANGELOG.md. I hope to rewrite the readme for the project soon as much of the info is not needed.

**Comment by jgulledge19** [comment]
FYI I added lots of docs for Orchestrator and also how to install Fred via command line or require via a Migration: https://lippertcomponents.github.io/Orchestrator/modx-extras.html
