### ISSUE TITLE
{{theme_dir}} parse on Fred elements

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#265]
Hi All,

Current Setup:
Modx 2.7.1-pl
Fred 1.1.0 rc

This improvement requests follows a bit the logic of #71 where the main idea is to add a bit more functionality: allow to use `{{theme_dir}}` on the Fred elements code.

Example:

```

<div class="col-12 col-lg-6{% if pane_image_show == false %} d-none{% endif %}" data-fred-render="{% if pane_image_show %}true{% else %}false{% endif %}">
	<img src="{{theme_dir}}images/image_brand.png" class="img-fluid d-block mx-auto mx-lg-0" alt="" />
</div>

```

This way you can expand theme portability by stopping the usage of `[[+assets_dir]]` respecting Fred logic.

Thanks in advance.

**Comment by matdave** [comment]
Looks like this needs to make it into the docs.  The twig element `{{template.theme_dir}}` is available and I believe it does what you are discussing.

**Comment by JANogueira** [comment]
ok perfect! many thanks. It works.

Sorry for this, but it is not easy to do a search into the current github docs folder.
Hope that new fred 1.1.0 comes soon so we can have updated documentation :)

Cheers and many thanks again.
