### ISSUE TITLE
data-fred-min-height does not work anymore

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#267]
Min height does not work anymore.
**Fred 1.1.0-rc**

Dev tools shows this crossed out, **Invalid property value**:

`*[data-fred-min-height] {min-height: attr(data-fred-min-height length);`

`<div data-fred-editable="true" data-fred-dropzone="two_col_two" data-fred-min-height="500px"></div>`

![fred](https://user-images.githubusercontent.com/725851/60806956-afe0a180-a184-11e9-820e-a438f281e3b5.png)

**Comment by theboxer** [comment]
Where did you found that `data-fred-min-height` property is available for use?

**Comment by DESIGNfromWITHIN** [comment]
https://modxcms.github.io/fred/themer/templates/

**Comment by DESIGNfromWITHIN** [comment]
Also drop areas without any min height simply dont work now...
There is now visible drop area shown at all.

**Comment by DESIGNfromWITHIN** [comment]
**Row one drop area** element

```
<section id="{{section_id}}">
	<div class="container">
		<div class="row">
		    <div class="offset-md-12 col-md-12">
		    	<div class="{{vertical_align}}">
		        	<div data-fred-editable="true" data-fred-dropzone="two_col_one">
		        	</div>
			</div>
		    </div>
		</div>
	</div>
</section>
```

![fred2](https://user-images.githubusercontent.com/725851/60808025-9b51d880-a187-11e9-9b19-e3a451c69581.jpg)

**Comment by DESIGNfromWITHIN** [comment]
Ok somehow the width of empty nested dropzones is 0px....

**Comment by DESIGNfromWITHIN** [comment]
Sorry for the spam, I think it has to do with my use of the **d-flex** class and Bootstrap 4 based flexbox...

If I remove it the drop area works.
