### ISSUE TITLE
Error building theme

### ISSUE THREAD

**Issue by alienbuild** [modxcms/fred#274]
I'm trying to build a theme but after clicking the build button I'm getting stuck on the loading screen. MODX console throws the following error:
```
Could not load class: xPDOScriptVehicle from transport.mysql.xpdoscriptvehicle.
```
I'm using FRED 1.1.0-rc and MODX 2.7.1 - PHP 7.1
Checking the core/packages folder I can see that the .zip is not being output but the folder for my theme is.

**Comment by theboxer** [comment]
I can't reproduce this issue. Tried fresh MODX cloud with Fred 1.1.0-rc and build a theme without an issue...

**Comment by alienbuild** [comment]
Thank you for trying. Is there anything in my theme that could be causing the issue? I saw there was a previous issue with a capital letter in the theme name or something similar ?

**Comment by theboxer** [comment]
I think this error shouldn't be caused by anything in the theme, but I could be wrong... Is there a chance where you could try and build the theme in modx cloud?

**Comment by alienbuild** [comment]
I don't have MODX cloud unfortunately but I'm certain that there is something in my theme that FRED doesn't like. It builds fine using a duplicate of the default theme or a new theme made with just one simple element.

**Comment by theboxer** [comment]
Can you give me an access to your site? (If so, email: john@modx.com)

**Comment by alienbuild** [comment]
Deleted a node init + script when preparing to send the files to @theboxer. Since deleting these files I'm now able to build the theme successfully.
