### ISSUE TITLE
data-fred-link-type limitation

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#282]
Hi,

While following these instructions in order to build a carousel, I found a limitation:
https://github.com/modxcms/fred/blob/9bb3b56daa9e92a337b4baeb2a02d04e86f311a7/docs/themer/elements/js_events.md

This works perfectly well. The problem is when I want to have a button and create a page link for it.
Since there is no way to use data-fred-link-type and data-fred-link-page on a similar way as an img with data-fred-name to have a popup to allow these changes, it is a real challenge to have links on the various sliders out of a RTE.

The idea is to be able to have something like this:
```
<a class="d-inline-block text-center font-weight-bold px-3 py-2 mt-4 view-bigger-map" href="" data-fred-link-type="page"  data-fred-link-page="[[!*id]]" data-fred-name="slider_link_{{i}}">
[[!%frontend.view_bigger_map? &language=`[[++cultureKey]]` &namespace=`project_name` &topic=`default`]]
</a>
```

**EDIT**:
Observed on Modx 2.7.1-pl with Fred 1.1.0 RC3

**Comment by theboxer** [comment]
These attributes are actually just for the RTE, they are not there to create a link editor.
