### ISSUE TITLE
Fred not including call to script file on element

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#289]
Hi,

I am facing issues when creating a fred element using this logic:
https://github.com/modxcms/fred/blob/9bb3b56daa9e92a337b4baeb2a02d04e86f311a7/docs/themer/elements/js_events.md

The two javascript file calls on the element are simply not included on the code by Fred. Meaning that this only works when I am viewing the site as visitor (without fred enabled).

Javascript included on the template head:
```

function EnableCircleElement(Element, phrase, phrase2)
{
	if(Element === undefined) {
		  Element = false;
	   }
	if(phrase === undefined) {
		  phrase = '';
	   }
	if(phrase2 === undefined) {
		  phrase2 = '';
	   }	   
	
	$(Element).circleProgress().on('circle-animation-progress', function(event, progress, stepValue) {
		$(this).find('strong').text(String((Math.round(100*stepValue)).toFixed(0)) + "%");
		if(phrase!='')
		{
			if(phrase2=='')
			{
				text = "<b>" + phrase + "</b>";
				$(this).find('small').css('top', '110px');
			}
			else
			{
				text = "<b>" + phrase + "</b><br/>" + phrase2;
				$(this).find('small').css('top', '97px');
			}
		}
		$(this).find('small').html(String(text));
	});	
}

```

Optionset:
```

{
  "remote": true,
  "settings": [
    {
      "name": "thinbar_logo_type",
      "label": "Left object type",
      "type": "select",
      "options": {
        "image": "Static Image",
        "graph": "Circular Graph"
      },
      "value": "graph"
    },
    {
      "group": "Left Object (Image Config)",
      "settings": [
        {
          "name": "left_pane_logo",
          "label": "Logo",
          "type": "image",
          "mediaSource": "Mediasource",
          "value": "{{theme_dir}}images/promo.png"
        }
      ]
    },
    {
      "group": "Left Object (Graph Config)",
      "settings": [
        {
          "name": "round_graph_value",
          "label": "Percentage (1 to 100)",
          "type": "slider",
          "min": 0,
          "max": 100,
          "step": 1,
          "value": 99
        },
        {
          "name": "round_graph_text1",
          "label": "Graph Text - Line 1",
          "type": "text",
          "value": "Text 1"
        },
        {
          "name": "round_graph_text2",
          "label": "Graph Text - Line 2",
          "type": "text",
          "value": "Text 2"
        }
      ]
    }
  ]
}

```

Element:
```

		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-circle-progress/1.2.2/circle-progress.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.appear/0.4.1/jquery.appear.min.js"></script>
		<script>
		    var $circle_bar = function(){
			    phrase = '{{ round_graph_text1 }}';
    			phrase2 = '{{ round_graph_text2 }}';
    			elid = '#{{ id }}';
    			v=false;
    			$(elid).appear();$('body').on('appear', elid, function(event, $all_appeared_elements){v ? v : EnableCircleElement(elid, phrase, phrase2);v=true;});
			};
			
			
			document.body.addEventListener("FredElementDrop", function(){
			  EnableCircleElement('#{{ id }}', '{{ round_graph_text1 }}', '{{ round_graph_text2 }}');
			});
			
			document.body.addEventListener("FredElementSettingChange", function(){
			  EnableCircleElement('#{{ id }}', '{{ round_graph_text1 }}', '{{ round_graph_text2 }}');
			});
			
			$(document).ready(function(){
			  // page is now ready, initialize the calendar...
			  $circle_bar();
			});
		</script>
		
        <section class="container-fluid blue-on-white py-5">
			<div class="container">
				<div class="row">
						{% if thinbar_logo_type == "image" %}
					<div class="col-12 col-lg-2">
						<img class="d-block mx-auto mx-lg-0 mb-4 mb-lg-0" src="{{ left_pane_logo }}" alt="Promo">
					</div>
						{% elseif thinbar_logo_type == "graph" %}
					<div class="col-12 col-lg-3 my-auto">
						<div
							class="circle mx-auto mx-lg-0"
							id="{{ id }}"
							data-start-angle="-1.55"
							data-size="200"
							data-value="{{ round_graph_value/100|round }}"
							data-thickness="6"
							data-empty-fill="rgba(0, 0, 0, 0)"
							data-fill="{
								&quot;color&quot;: &quot;rgba(255, 255, 255, 1)&quot;
							}">
							<strong></strong>
							<small></small>
							
						</div>
					</div>
						{% endif %}
					
				</div>
				
			</div>
		</section>

```

In theory, when Fred element is dropped, the circle bar script is already loaded and the call to the existing script (included on head) would be used.
Even if I include the script file (that is called on the head) directly on the fred element, nothing changes. Same problem.

What am I doing wrong?

Current environment:
Modx 2.7.1-pl + fred 1.1.0 RC3

Thanks in advance.

**Comment by theboxer** [comment]
@JANogueira the last commit should resolve your issue, will you be able to build the JS and test it?

Few points to your setup:
- Why do you use `remote: true`, when you are not using any MODX tags in the element? It's unnecessary XHR
- Both events `FredElementDrop` and `FredElementSettingChange` are triggered on any element, which seems like not necessary for your case. Why it should re-render this element when you change setting for some other on the page? I'd recommend either verifying in these events that you dropped/changed this element (or some other that is relevant for making this one to re-render) - you can access the changed/dropped element title in `event.detail.fredEl.title` or use [data-fred-on-setting-change](https://github.com/modxcms/fred/blob/9bb3b56daa9e92a337b4baeb2a02d04e86f311a7/docs/themer/elements/attributes.md#data-fred-on-setting-change) and [data-fred-on-drop](https://github.com/modxcms/fred/blob/9bb3b56daa9e92a337b4baeb2a02d04e86f311a7/docs/themer/elements/attributes.md#data-fred-on-drop) attributes
- What's the point of creating a listener for `FredElementDrop` inside the element? In most cases it won't trigger for the same element where you define it
- When you add a listener to `FredElementDrop` and `FredElementSettingChange` inside the element's code, if you'll drop the element twice in the page, those listeners will get called also twice, which is not wanted I'd say
- You are using global events, but forcing them to use local variables instead of using data that are passed to the events.

**Comment by JANogueira** [comment]
Hi John,

Many thanks for your quick answer.
I am still discovering these details. First time trying to use them (Except remote) :)

Let me try to test your change and make some readjustments based on your tips and I will share the outcome.

Cheers

**Comment by JANogueira** [comment]
Hi John,

Apologies for my ignorance, but how can I build the JS?
I am still not used to composer and similar compiling tools. Still quite new for me as I was away from WebDev for about 5 years.

Thanks

**Comment by theboxer** [comment]
Can you ping me on community slack? I'll send you the built JS, can't attach it here as JS is not supported file type :/

**Comment by JANogueira** [comment]
Yes, sure. Many thanks!

**Comment by JANogueira** [comment]
@theboxer it works perfectly.
I tried adding two different element having a similar approach and it worked flawlessly.
Many thanks!

Answering directly to your questions:

- Why do you use remote: true, when you are not using any MODX tags in the element? It's unnecessary XHR
`Because I have some sections that include lexicons like this (otherwise the lexicons won't render):`
```
{% if panel_published == 0 %}
	<div class="position-absolute alert alert-danger text-center" role="alert" style="width:300px;bottom:0;left:50%;margin-left:-150px">[[!%patraomor.fred.panel_not_visible? &language=`[[++cultureKey]]` &namespace=`project` &topic=`fred`]]</div>
{% endif %}
```

- Both events FredElementDrop and FredElementSettingChange are triggered on any element, which seems like not necessary for your case. Why it should re-render this element when you change setting for some other on the page? I'd recommend either verifying in these events that you dropped/changed this element (or some other that is relevant for making this one to re-render) - you can access the changed/dropped element title in event.detail.fredEl.title or use data-fred-on-setting-change and data-fred-on-drop attributes
`Followed your suggestion and indeed solved other headache I was facing as well. Many thanks for the tip! It was just perfect`

- What's the point of creating a listener for FredElementDrop inside the element? In most cases it won't trigger for the same element where you define it
`On this specific situation the objective is to trigger the circle bar animation as soon as the element drop is done so the end user can see what the visitors will see. Site admins insisted on this situation as they want to see the things happening just like the visitors. Here worked just fine. By adding this to the main div:`
```
<div data-fred-on-drop="circle_bar_fred_activate" data-fred-on-setting-change="circle_bar_fred_activate">
```
`with this function:`
```
function circle_bar_fred_activate(){
	EnableCircleElement('#{{ id }}', '{{ round_graph_text1 }}', '{{ round_graph_text2 }}');
}
```

- When you add a listener to FredElementDrop and FredElementSettingChange inside the element's code, if you'll drop the element twice in the page, those listeners will get called also twice, which is not wanted I'd say
`Exactly. What I did above following your tips, just solved that unwanted behavior.`

- You are using global events, but forcing them to use local variables instead of using data that are passed to the events.
`It was indeed bad idea. After checking your tips I understood what I was doing. Many thanks for your time and patience.`


Many thanks once again John.

**Comment by theboxer** [comment]
👍
