### ISSUE TITLE
Only sudo users have access to Fred. Perhaps a new 'use_fred' permission could be good.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#29]
At the moment it appears only sudo users have access to Fred. 
Even users in the administrator group without sudo don't seem to be able to access Fred.

Would it be possible to replace this requirement with a permission such as 'use_fred' that could be applied to a policy for user groups?

**Comment by theboxer** [comment]
Not at this moment, currently sudo flag is required for user to see Fred. Permissions will come in one of the next releases.
