### ISSUE TITLE
Javascript errors when processing document ready verification on fred

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#295]
Hi,

Since Fred 1.1.0-pl upgrade, all Fred blocks having `$(document).ready(function(){` are thowing javascript errors:
![image](https://user-images.githubusercontent.com/22750391/63463078-44147880-c454-11e9-8b1d-bfb5301fbea5.png)

![image](https://user-images.githubusercontent.com/22750391/63460931-6b1c7b80-c44f-11e9-9283-9679c6900822.png)

![image](https://user-images.githubusercontent.com/22750391/63460986-8c7d6780-c44f-11e9-9874-a49fd686a921.png)

This does not happen when you drop the fred element.
This happens when refreshing the page after fred save. You will see the javascript error. for regular visitors, all just fine.

here is an extract of the element:
```
		<section class="container-fluid py-5">
			<div class="container">
				<h4 class="sr-only">section</h4>
				
				[[migxLoopCollection?
					&packageName=`books`
					&classname=`LibraryLocations`
					&where=`{"published":"1","deleted":"0"}`
					&sortConfig=`[{"sortby":"pos","sortdir":"ASC"}]`
					&tpl=`LocationsAndContactsHeaderLinks`
					&wrapperTpl=`LocationsAndContactsHeaderLinksWrapper`
					&outputSeparator=``
					&debug=`0`
					&addfields=`locationsandcontacts_uid:{{ id }}`
				]]
				
				
				[[migxLoopCollection?
					&packageName=`books`
					&classname=`LibraryLocations`
					&where=`{"published":"1","deleted":"0"}`
					&sortConfig=`[{"sortby":"pos","sortdir":"ASC"}]`
					&tpl=`LocationsAndContactsBodyLinks`
					&wrapperTpl=`LocationsAndContactsBodyLinksWrapper`
					&outputSeparator=``
					&debug=`0`
					&addfields=`locationsandcontacts_uid:{{ id }}`
				]]
				<script>
        			$(document).ready(function(){
        			  generateGoogleMaps();
        			});
                </script>
                
			</div>
			
		</section>
```
Optionset only has remote:true

**Comment by JANogueira** [comment]
Hi,

Another Example of Fred Element showing this error as described above:

```
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{ id }}_modal" data-fred-render="false">
     Open Modal
    </button>
<div class="modal fade" id="{{ id }}_modal" tabindex="-1" role="dialog" aria-labelledby="{{ id }}_modalLongTitle" aria-hidden="true" data-fred-render="false">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="{{ id }}_modalLongTitle">Title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Modal example
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save</button>
      </div>
    </div>
  </div>
</div>
<script>
    $(function () {
        $("#{{ id }}_modal").appendTo("body");
    });
</script>
```

Again, when performing drag and drop, all OK. After saving and hitting F5, problem will appear:
Try to click on the button to open the modal and you will see that the script will throw an error.
![image](https://user-images.githubusercontent.com/22750391/63621507-02b6d100-c5ec-11e9-82dd-e225f808dd05.png)


Thanks again

**Comment by theboxer** [comment]
This is actually not an issue introduced in 1.1.0-pl, it has been present probably since the beginning and it's caused by loading scripts in the template after the whole page (including all elements) finishes rendering. Which means your jQuery dependency is not loaded yet when the element loads.

**Comment by JANogueira** [comment]
Hi John,

If fact I only started exploring this now, this is why I am only reporting this now (sorry).
I tried jQuery on head or on the body (at the end) and still same result. Seems that the order of the scripts is changed when Fred is loaded, as the problem is not seen when page is loaded as anonymous visitor, or when dragging and dropping to the placeholder (when Fred is loaded).

**Comment by theboxer** [comment]
It doesn't matter if you put the script tags on head or body, fred is extracting them and loading one at a time in the order you have them, but after all elements are rendered. 

I'm working on a fix, but it'll take some more time :)

**Comment by JANogueira** [comment]
Ok many thanks for the clarification and for the fix! Cheers

**Comment by JANogueira** [comment]
Hi John,

Many thanks for your fix.
Do you think that a Fred 1.1.1-pl Package would make sense?
This fix might positively affect several people and even more people over the time as the usage of Fred increases (and the number of downloads speak for itself).

Thanks in advance for your consideration about this.
Cheers

**Comment by theboxer** [comment]
Hey they'll be 1.1.1-beta this week to test it out

**Comment by JANogueira** [comment]
Incredible! 👍 Thank you very much! I'll give you my feedback as soon as the package is released.
Cheers

**Comment by JANogueira** [comment]
Hi @theboxer , just to update you on this:
- Fred 1.1.1-beta solved this issue. Everything is working perfectly. No single change on my code. Just Fred 1.1.1 update.
- elFinder bugs are also fixed (related mainly with capitalized extension and visual glitches).
- I could notice that Dropzones are behaving better, including nested dropzones;

I know this is all on the 1.1.1 change log, but I wanted to share also my point of view as a user so you can also have external feedbacks.

Many thanks for your hard work with Fred! 👍

**Comment by theboxer** [comment]
thank you for the feedback!
