### ISSUE TITLE
Content not saved if element has same id

### ISSUE THREAD

**Issue by NatemcM** [modxcms/fred#296]
Issue: 
The following code prevents any page created with Fred from saving the content to the resource. You can not have any other element with the same ID as the dropzone.

```
<div id="main">
  <div data-fred-dropzone="main">
    [[*content]]
  </div>
</div>
```

Fix: A warning on the Fred editor if a duplicated ID is found - or simply state this in the docs

**Comment by theboxer** [comment]
I'm not sure I understand. The code you posted is incorrect for saving to resource's content as you wrongly named your dropzone.

If you want to save to resource's content, in the template you have to have a dropzone with `data-fred-dropzone="content"`

**Comment by NatemcM** [comment]
Ahh ok, I re-read the docs... forgive my stupidity!

I confused the fact that in Fred elements we can create a dropzone and name it whatever and it works fine.
