### ISSUE TITLE
document.write JS messed up FRED

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#298]
For a Theme I use this framework:
https://codyhouse.co/ds/docs/framework

It checks for Progressive enhancement using **window && CSS.supports** and **document.write** specific stylesheets:

    <script>
    if('CSS' in window && CSS.supports('color', 'var(--color-var)')) {
      document.write('<link rel="stylesheet" href="assets/components/any-codyhouse-framework/codyhouse-framework/assets/css/style.css">');
    } else {
      document.write('<link rel="stylesheet" href="assets/components/any-codyhouse-framework/codyhouse-framework/assets/css/style-fallback.css">');
    }</script>

But this break FRED totally.

I tried `data-fred-render=true` but that does not work.

> Any idea how to get this working? or Not run this script when FRED is active?

**Comment by theboxer** [comment]
You are calling document.write on the closed document (it already rendered) - this is due to how fred delays applying all scripts after all fred elements are rendered.

You can use appendChild instead of document.write to add the styles.

```
var link = document.createElement('link');
    link.setAttribute('rel', 'stylesheet');
    link.setAttribute('href', 'assets/components/any-codyhouse-framework/codyhouse-framework/assets/css/style.css');
    document.head.appendChild(link);
```
