### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Electrica** [modxcms/fred#30]
When i setup Fred 1.0.0-beta4 i had error:

2018/08/25 21:40:21 [error] 884#884: *1674 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Moontoast\Math\bcadd() in /home/electrica/www/mustexpert.local/www/core/components/fred/model/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php:506
Stack trace:
#0 /home/electrica/www/mustexpert.local/www/core/components/fred/model/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php(62): Moontoast\Math\BigNumber->setValue('153521162159972')
#1 /home/electrica/www/mustexpert.local/www/core/components/fred/model/vendor/ramsey/uuid/src/Converter/Number/BigNumberConverter.php(49): Moontoast\Math\BigNumber->__construct('153521162159972')
#2 /home/electrica/www/mustexpert.local/www/core/components/fred/model/vendor/ramsey/uuid/src/Generator/CombGenerator.php(72): Ramsey\Uuid\Converter\Number\BigNumberConverter->toHex('153521162159972')
#3 /home/electrica/www/mustexpert.local/www/core/components/fred/model/vendor/ramsey/uuid/src/UuidFactory.php(235): Ramsey\Uuid\Generator\CombGenerator->generate(16)
#4 /home/electrica/www/mustexper" while reading response header from upstream, client: 127.0.0.1, server: mustexpert.local, request: "POST /connectors/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-mustexpert.sock:", host: "mustexpert.local", referrer: "http://mustexpert.local/manager/?a=workspaces"
![image](https://user-images.githubusercontent.com/3878386/44620037-c012c980-a8af-11e8-9afe-41944620cfbc.png)

**Comment by theboxer** [comment]
Seems like you are missing bcmath (http://php.net/bcmath) extension.
