### ISSUE TITLE
Option to define Fred activation status for fred editors

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#308]
Hi,

I've been looking around for an option that would allow to define the default Fred activation status, but it seems it does not exist yet.

What I mean with Fred activation status is about the way Fred is delivered to the Fred editor as soon as the Login is performed: If Fred should be disabled as default (same as going to "More" - "Disable Fred", keeping the Modx button that would allow you to enable fred), or if Fred editor should be enabled by default when a Fred editor is logged on (Like it is happening today).

This can be useful if a content editor wants just to navigate with the site as default action, instead of editing the content.

Do you think this would make sense?
Thanks in advance

**Comment by theboxer** [comment]
You mean something like `fred.default_enabled` system setting?

**Comment by JANogueira** [comment]
sort of, yes

**Comment by theboxer** [comment]
so what's the difference?

**Comment by JANogueira** [comment]
Oh! I see. It exists already. I was not understanding. Now I saw it and tested it. This is exactly what I was looking for.

Many thanks.
