### ISSUE TITLE
MODX tag not parsed in attribute value

### ISSUE THREAD

**Issue by Boddlnagg** [modxcms/fred#312]
I have a Fred element with `<form action="[[~123]]" ...>` and `"remote": true` enabled.

It renders as `<form action="%5B%5B~123%5D%5D" ...>`. When I put the MODX tag inside a `<p>` element, it renders correctly.
I assume this is because the Twig parser runs first and turns `[[~123]]` inside the attribute into `%5B%5B~123%5D%5D`, which MODX then doesn't recognize any more?

**Comment by matdave** [comment]
Which version of Fred are you running?

**Comment by Boddlnagg** [comment]
1.1.0 ... your comment made me realize that there's 1.1.1 now. Is this fixed there?

**Comment by theboxer** [comment]
I got this issue only when saving the resource from manager, from frontend it worked fine.

**Comment by Boddlnagg** [comment]
@theboxer Yes, I should have mentioned that I was editing an element in the manager.
