### ISSUE TITLE
Could not find action file at: controllers/default/mgr/elements/update.php

### ISSUE THREAD

**Issue by catfrance** [modxcms/fred#314]
I have recently installed v1.1 on a new site.

When I create a new element and hit save, I get this error in the center of the manager:

`Could not find action file at: controllers/default/mgr/elements/update.php`

The element has been created but I have to manually go back into Extras > Fred. If I then go back into element and save, there is no error. It only happens on the first save of a new element.

I have another site which is on v1.0 which doesn't have this issue.

I have tried uninstalling and re-installing.

**Comment by theboxer** [comment]
1.1.0 or 1.1.1? I can't reproduce this issue...

**Comment by theboxer** [comment]
Hmm, I still can't reproduce.
I create fresh MODX Cloud, installed Fred 1.1.1, created a test category and element. No errors...

**Comment by rthrash** [comment]
What version of PHP is your server running, and any other details about the server and MODX version?

**Comment by catfrance** [comment]
PHP 5.5.38
Windows Server 2012 R2, IIS 8.5
MODX 2.7.1

I also tried removing all other packages and still got the issue.

**Comment by theboxer** [comment]
Fred requires PHP version 7.1.3 or later to run with support for the php-bcmath extension. PHP 5.5.9 or later should work, but is not officially supported, and we strongly recommend using non-EOL versions of PHP. (as stated in [docs](https://modxcms.github.io/fred/getting_started/))

I'm not 100% sure it's causing this particular issue you are having, but will cause other issues for sure.
