### ISSUE TITLE
Error buililding theme

### ISSUE THREAD

**Issue by uwunderli** [modxcms/fred#315]
If I want to pack a theme, the routine breaks off with an unknown error.
![theme_building_error](https://user-images.githubusercontent.com/55878516/65765218-f57b8d80-e127-11e9-80d8-23958517413b.png)

**Comment by rthrash** [comment]
What version of PHP is your server running?

**Comment by uwunderli** [comment]
7.2.19 with Apache2 web server (7.2.19-0ubuntu0.18.04.2)

**Comment by rthrash** [comment]
That should be fine. Any PHP errors or errors in the dev tools console? And just to make sure, which version of Fred is running?

Would it be possible to get access to the install to debug?

**Comment by uwunderli** [comment]
You can already have access. To which address should I send the access data?

**Comment by uwunderli** [comment]
The error that appears in the log file is...

`[2019-09-27 19:16:27] (ERROR @ /core/xpdo/xpdo.class.php : 644) Could not load class: xPDOScriptVehicle from transport.mysql.xpdoscriptvehicle.`
