### ISSUE TITLE
elFinder thumbnails listing problem

### ISSUE THREAD

**Issue by JANogueira** [modxcms/fred#318]
Hi,

While generating thumbnails for the elFinder, these are stored on the .tmp folder, depending on the project directory.

But while accessing to the elFinder files view that are images, the thumbnails are never generated, unless if these lines are commented on the Modx base directory .htaccess:

```
# Prevent dot directories (hidden directories like .git) to be exposed to the public
# Except for the .well-known directory used by LetsEncrypt a.o
RewriteRule "/\.|^\.(?!well-known/)" - [F]
```

Touching the base modx htaccess can be a bad idea as it would be lost on every Modx upgrade.
Is there any way to address this point? Maybe _tmp instead of .tmp, for instance? Same with quarantine folder?

Thanks in advance.
Cheers

**Comment by matdave** [comment]
Even if you upload the entire contents of the MODX download it wouldn't be touched during install. The file is called ht.access in the MODX download folder because it's expected people will alter it.  

You could change it to something like: 
```
RewriteCond %{REQUEST_URI} !(^|/)\.tmp
RewriteCond %{REQUEST_URI} !(^|/)\.well-known [NC]
RewriteRule "(^|/)\." - [F]
```

**Comment by JANogueira** [comment]
You are right. I forgot that the modx installer was having the .htaccess files as ht.access.
many thanks @matdave . this worked perfectly.
Cheers

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/fred-image-browser-no-thumbnails/2330/4

**Comment by lottaar** [comment]
I think there's a typo above – it should be tmb, not tmp. This works for me:

```
RewriteCond %{REQUEST_URI} !(^|/)\.tmb
RewriteCond %{REQUEST_URI} !(^|/)\.well-known [NC]
RewriteRule "(^|/)\." - [F]
```
