### ISSUE TITLE
Fred+Formit+Ajaxform

### ISSUE THREAD

**Issue by ivan-kuzin** [modxcms/fred#319]
Hi, I have a problem with Fred. Formit+AjaxForm don't works with Fred. Site goes into white screen when fred and ajaxform are active. And it normal works when Fred is deactivated.
And also you have a problem in Russian translete. Button Open Setting (on the frontend of blocks) dont translate. It must be "Открыть настройки" (open settings), or "Перейти к настройкам" (go to settings), "Настройки блока" (block's settings)

**Comment by theboxer** [comment]
Duplicate of #290
