### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by ozmaat** [modxcms/fred#32]
I tried to install the package several times but installation hangs and had to close the installation box. 

And it caused php error at the line below in cache files. 

$corePath = $modx->getOption('fred.core_path', null, $modx->getOption('core_path', null, MODX_CORE_PATH) .

Browser error was.

"This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 520"

Manager works but resource editing throw the above error, after a while site was down.

Removing the package from modx doesn't help, and also doesn't clear the modx DB.

I disabled the plugin from DB to get rid of the problem. 

Version - MODX Revolution 2.6.5-pl

**Comment by rthrash** [comment]
Which version were you trying to install? Which version of PHP and MySQL? Web server?

**Comment by ozmaat** [comment]
Hi,

Details below.

Fred version - 1.0.0-beta4
Apache - Apache/2.4.6 (CentOS) 
PHP/5.4.16
MySQL - 5.5.60

**Comment by theboxer** [comment]
You need php 7.1 for the latest build, I'm sorry about that... The next release will support php 5.4 again
