### ISSUE TITLE
Failed install fred

### ISSUE THREAD

**Issue by CrazyBoy49z** [modxcms/fred#329]
Installation error fred-1.1.1-pl from modx.com

> PHP extension "bcmath" is not loaded, but it is required by Fred.
> Requirements not met. Fred can't be installed.
> xPDOVehicle validator failed: type php (modx/core/packages/fred-1.1.1-pl/modCategory/a0c65c1d03f40c1e1b0da04250246d94.requirements.validator.validator)
> Vehicle 10c345be1b22b72d77e978727e5e654f in transport fred-1.1.1-pl failed to install and indicated the process should be aborted.

**Comment by theboxer** [comment]
As it says in the error message you posted. PHP extension “bcmath” is required.
