### ISSUE TITLE
Duplicating a resource from Fred doesn't add an entry to the manager log

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/fred#337]
When duplicating a resource with Fred it doesn't add the "duplicate_resource" action to the manager log.

**Comment by theboxer** [comment]
That's correct, it's not a manager action.

**Comment by JoshuaLuckers** [comment]
Yes it's not an actual manager action but I believe it would be good to threat it as one and log it anyways. This to keep it easier to audit.

**Comment by theboxer** [comment]
ok, in that case feel free to submit pr :)

**Comment by matdave** [comment]
This will be working in the next version
