### ISSUE TITLE
Option to add Template variables to Advanced settings for a page

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/fred#340]
I would like to have the option to add Template Variables to the **Advanced settings** on the FRED front-end for a resource.

The current use I have is the **Social Media image** for a page, I have a TV and use pthumb to created the meta tags for social images.
It is not really front-end content, but it would be nice to be able to update this TV using FRED on the front-end.

**Comment by matdave** [comment]
This is currently available by editing the default properties of the Template Variable

**Property 1**
Name: fred
Type: Yes/No
Value: 1

**Property 2**
Name: fred.type
Type: text
Value: image

**Property 3 (optional)**
Name: fred.mediaSource
Type: text
Value: Name of the media source

**Comment by DESIGNfromWITHIN** [comment]
Thanks that works great!
Will those properties be packed in when I create the FRED theme?

**Comment by theboxer** [comment]
yup
