### ISSUE TITLE
Feature Request: Inverse of "data-fred-class"

### ISSUE THREAD

**Issue by robcarey** [modxcms/fred#342]
I'd love to see a new attribute option added with the inverse behaviour of "data-fred-class"

Use case: I have found it sometimes finicky  getting things lined up in a dropzone.  The cursor jumps and in cases where there are multiple dropzones close by it's hard to identify and target the actual dropzone desired.  Having a class that is active ONLY when Fred is loaded would allow the ability to maybe add a red border to highlight the dropzone, or a shaded background.  These visual cues could assist in the user experience while editing.

When Fred is not active, the class would not be applied.  Make sense?

**Comment by matdave** [comment]
When Fred is active the <html> tag gets a "fred--active" class added. You can use this to create Fred override styles. Fred adds additional classes to the wrappers and containers of all Fred elements based on their active/inactive state that could be targeted in a user generated stylesheet if you wish to customize the look of your editor experience.

**Comment by robcarey** [comment]
Awesome - thanks for the education @matdave !  Keep doing your awesome work!

**Comment by robcarey** [comment]
@matdave Just want to follow up on this as I'm not seeing the behavior you described above.  The dropzones themselves don't seem to get any classes applied to them while Fred is active.   I'm specifically looking for a means to highlight dropzones so that users can easily identify where to attempt content insertion as it's a little finicky dragging and dropping blindly in white areas.

![Annotation 2020-02-08 225702](https://user-images.githubusercontent.com/3990764/74095977-adea1280-4ac6-11ea-88cc-a0f7c90dabe2.png)
