### ISSUE TITLE
Rebuild causes error that is unclear

### ISSUE THREAD

**Issue by robcarey** [modxcms/fred#345]
I'm encountering an error that I can't seem to track down or track to a specific resource or element
 On rebuilding Fred resoureces, I get the following output - scroll down to see the errors inline:

Console running...
Refreshing Resource ID 26
Refreshing Resource ID 27
Refreshing Resource ID 28
Refreshing Resource ID 31
Refreshing Resource ID 32
Refreshing Resource ID 33
Refreshing Resource ID 34
Refreshing Resource ID 35
Refreshing Resource ID 36
Refreshing Resource ID 37
Refreshing Resource ID 38
Refreshing Resource ID 39
Refreshing Resource ID 40
Refreshing Resource ID 41
Refreshing Resource ID 42
Refreshing Resource ID 43
Refreshing Resource ID 45
Refreshing Resource ID 46
Refreshing Resource ID 47
Refreshing Resource ID 48
Rebuild Completed
PHP warning: Couldn't fetch DOMElement. Node no longer exists
PHP notice: Undefined property: DOMElement::$ownerDocument
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: Couldn't fetch DOMElement. Node no longer exists
PHP notice: Undefined property: DOMElement::$ownerDocument
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: Couldn't fetch DOMElement. Node no longer exists
PHP notice: Undefined property: DOMElement::$ownerDocument
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
PHP warning: DOMElement::hasAttribute(): Couldn't fetch DOMElement
Refreshing Resource ID 1
Refreshing Resource ID 3
Refreshing Resource ID 4
Refreshing Resource ID 5
Refreshing Resource ID 6
Refreshing Resource ID 7
Refreshing Resource ID 8
Refreshing Resource ID 9
Refreshing Resource ID 10
Refreshing Resource ID 11
Refreshing Resource ID 12
Refreshing Resource ID 13
Refreshing Resource ID 14
Refreshing Resource ID 15
Refreshing Resource ID 16
Refreshing Resource ID 17
Refreshing Resource ID 18
Refreshing Resource ID 19
Refreshing Resource ID 20
Refreshing Resource ID 21
Refreshing Resource ID 22
Refreshing Resource ID 23

**Comment by robcarey** [comment]
I'm going to update this in that I was able to resolve these issues after going over line by line all my elements.  I did find a double quote that could have contributed to this as well as I adjusted all my twig if/else/endif blocks to include spaces between opening and closing brackets and use single quotes instead of double quotes:

i.e.  I changed {%if exampleVar =="foobar"%}{{showVar}}{%endif%}
to
{% if exampleVar == 'foobar' %}{{showVar}}{% endif %}

The combination of all the above eventually cleared rebuild errors.  If there was anything to wish for from this is that errors could have been more informative as to which element or which resource contained the issues - would have been a big help.

**Comment by robcarey** [comment]
Ok - sorry for confusion, but this has come back.  I have isolated it to a specific element which has A LOT of options and functionality.  It's a bootstrap card element, and the element itself is working great.  Something in it however makes Fred puke on rebuild.  I suspect it's the if blocks for hiding/showing the card header and footer.

Any insight?

`<div class="d-flex" data-fred-block-class="col-{{baseCol}} col-sm-{{baseCol}} col-md-{{mdCol}} col-lg-{{lgCol}}">
    <div class="card flex-fill {% if boxshadow is not empty %} {{boxshadow}}{% endif %}{% if boxhovershadow %} hovershadow{% endif %} {{rounding}} mt-{{marginTop}} mb-{{marginBottom}} ml-{{marginLeft}} mr-{{marginRight}} pt-{{paddingTop}} pb-{{paddingBottom}} pl-{{paddingLeft}} pr-{{paddingRight}}" style="background:{# FOREGROUND-IMG #}{% if fg_image_picker %}url({{fg_image_picker}}){% if fg_image_repeat %} {{fg_image_repeat}}{% endif %}{% if fg_image_position_val %} {{fg_image_position_val}}{% else %}{% if fg_image_position %} {{fg_image_position}}{% endif %}{% endif %},{% endif %} {# /FOREGROUND-IMG #}linear-gradient({{gradient_angle}}deg, {{gradient_first_colour}} {{gradientoffset}}%, {{gradient_second_colour}}){# BACKGROUND-IMG #}{% if bg_image_picker %}, url({{bg_image_picker}}){% if bg_image_repeat %} {{bg_image_repeat}}{% endif %}{% if bg_image_position_val %} {{bg_image_position_val}}{% else %}{% if bg_image_position %} {{bg_image_position}}{% endif %}{% endif %}{% endif %}{# /BACKGROUND-IMG #};background-size:{% if fg_image_picker %}{% if fg_image_size_val %}{{fg_image_size_val}}{% else %}{% if fg_image_size %}{{fg_image_size}}{% endif %}{% endif %},{% endif %}auto{% if bg_image_picker %}, {% if bg_image_size_val %}{{bg_image_size_val}}{% else %}{% if bg_image_size %}{{bg_image_size}}{% endif %}{% endif %};{% endif %}" {% if enableAOS %} data-aos="{{AOStype}}" data-aos-duration="{{AOSduration}}" data-aos-offset="{{AOSoffset}}" data-aos-easing="{{AOSeasing}}" data-aos-delay="{{AOSdelay}}" data-aos-anchor-placement="{{AOSanchor}}" data-aos-once="{{AOSonce}}"{% endif %}>
        {% if cardHeader %}
        <div class="card-header {%if cardHeaderBg%}border-0{%endif%}" {%if cardHeaderBg%}style="background:none;"{%endif%} data-fred-name="cardHeader" data-fred-rte="true" data-fred-rte-config="basic"><h5 style="padding: 0px; margin: 0px; text-align: center;"><strong>Featured</strong></h5></div>
        {% endif %}
        {% if imgPos =="top" %}
        <div class="text-center"><img src="{{cardImg}}" class="card-img-top w-{{cardImgWidth}}{% if rounding=='rounded-0' %} rounded-0{%endif%} pt-{{paddingCardImgTop}} pb-{{paddingCardImgBottom}} pl-{{paddingCardImgLeft}} pr-{{paddingCardImgRight}}" alt="{{imgAlt}}" style="opacity:.{%if image_opacity < 10%}0{%endif%}{{image_opacity}};"></div>
        {% endif %}
        {% if cardBody %}
        <div class="card-body" data-fred-name="cardBody" data-fred-rte="true" data-fred-rte-config="basic">
            <h5 class="card-title" data-fred-name="cardTitle">Title</h5>
            <p class="card-text" data-fred-name="cardText">Body Text</p>
        </div>
        {% endif %}
        {%if imgPos =="bottom"%}
        <div class="text-center"><img src="{{cardImg}}" class="card-img-bottom w-{{cardImgWidth}}{% if rounding=='rounded-0' %} rounded-0{%endif%} pt-{{paddingCardImgTop}} pb-{{paddingCardImgBottom}} pl-{{paddingCardImgLeft}} pr-{{paddingCardImgRight}}" alt="{{imgAlt}}" style="opacity:.{%if image_opacity < 10%}0{%endif%}{{image_opacity}};"></div>
        {% endif %}
        {% if cardFooter %}
        <div class="card-footer {%if cardFooterBg%}border-0{%endif%}" {%if cardFooterBg%}style="background:none;"{%endif%} data-fred-name="cardFooter" data-fred-rte="true" data-fred-rte-config="basic"><p style="text-align: center; margin: 0px; padding: 0px;"><a class="btn btn-cyber-light-blue" href="#">Button One</a>&nbsp;&nbsp;&nbsp;<a class="btn btn-cyber-light-blue" href="#">Button Two</a></p></div>
        {% endif %}
    </div>
</div>`

**Comment by robcarey** [comment]
Insights - I have zeroed this in to be due to the nested data-fred-name elements on line 11 and 12 of the above image.  Removing their data-fred-names resolved the issue, and I'm thinking this was user error on my end to have these nested like this?  I'll leave it to you awesome devs to decide :)

**Comment by theboxer** [comment]
Nesting fred-name attrs is not really supported - as this attr makes the element editable. So it'd mess with anything under it.
