### ISSUE TITLE
Permissions issue? Using fred in the chunk

### ISSUE THREAD

**Issue by erimeilis** [modxcms/fred#347]
Hello! I'm using fred for building a form, so adding editable strings to chunk.
Works smooth, but:
- if i'm logged in, i see all changes made
- if i'm not, i see hardcoded items
Any workaround?

**Comment by matdave** [comment]
Sorry to hear you are having issues. We have used Fred with both forms and Chunk references. I am not sure I'm fully grasping the issue you have run into. 

Would you please supply some more explicit detail about what is happening with some code examples and possibly screenshots?

**Comment by erimeilis** [comment]
Okay, i use fred block, that contains {include 'ajaxreg'}, which contains FormIt form, and finally in the chunk tpl.AjaxForm.Reg, used by form, i have stings like <img class="logo12" src="https://via.placeholder.com/40x30" data-fred-name="logo1">,  for example.

So, when i look at the pagel like unlogged user, i see these ..placeholder.com/40x30.
When i log in, i'm able to upload real images instead of them and it saves them in the place.

**Comment by theboxer** [comment]
That seems like a fenom syntax. Fenom is not supported in fred.
