### ISSUE TITLE
Downloading a builded theme shows "blank" page

### ISSUE THREAD

**Issue by bYemma** [modxcms/fred#35]
When I create a build and want to download it, the Page (?a=theme/download&theme=2&namespace=fred) is just empty. That meens topbar and resource tree are there, but the content area is empty. No download is starting...

Using Firefox: No console or HTTP errors.
Serverside: vServer, PHP 7.1.22, MySQL 5.5.61
Entry in the MODX error log: `[2018-10-03 22:33:29] (ERROR @ /var/www/[...]/modx/core/xpdo/xpdo.class.php : 644) Could not load class: xPDOScriptVehicle from transport.mysql.xpdoscriptvehicle.`

It was my first try to build a theme, so I can't say if it was working with another version...

**Comment by bYemma** [comment]
Following the MODX setup with fresh files from modx.com doesn't help. The same with reinstalling Fred.

**Comment by theboxer** [comment]
Could you check if the transport file was created under `core/packages`? It should be named as `name-version-release.transport.zip`

**Comment by bYemma** [comment]
Yes, there it is: `test-1-2.transport.zip`.
It contains 3 folders: FredTheme, xPDFFileVehicle and xPDOScriptVehicle each with files in it. And there is the manifest file.

**Comment by theboxer** [comment]
could you create me an admin user on your site? my email is john@modx.com

**Comment by bYemma** [comment]
You should get a email.

**Comment by theboxer** [comment]
Got it, the theme name in the build window has to be lowercase, it's name just for the file, I'll fix that in the next build so it's required :)

Also good version number is in format X.Y.Z (for example 1.0.0) and release should be something like pl (for public launch), beta, alpha or something similar.
