### ISSUE TITLE
How to make a element with global data?

### ISSUE THREAD

**Issue by esshevelev** [modxcms/fred#352]
Hi guys! I recently found out about your product and admire it! This is exactly what I was looking for a long time. I will popularize it in Russia and use it in all new projects.
I found solutions for almost all my tasks with the help of Fred. But I cannot realize one task. I want to make the site header and footer editable through Fred, but not unique for each page, but the same for everyone. These elements must be editable on any page and the changes apply to the entire site. I could not find a solution for this task yet. Perhaps you will tell me it. I do not need detailed instructions, just tell me which direction to dig. Thanks in advance, Evgen.
P.S. I could help translate Fred into Russian. Now this is not perfect.

**Comment by theboxer** [comment]
Unfortunately it's not possible right now, but seems like a good addition.
