### ISSUE TITLE
How to use snippets and chunks in Elements?

### ISSUE THREAD

**Issue by esshevelev** [modxcms/fred#353]
Hi guys! I am trying to add snippets like phpthumbof or pdotools, and chunks to Elements. When Fred editor is active this code is shown as plain text. When I turn off the Fred editor on the page with such an element (in the "More" menu item), everything works well. Can this be somehow corrected or is it just necessary to reconcile?

**Comment by wallacio** [comment]
You probably want to add remote: true to your element's settings:
https://modxcms.github.io/fred/themer/options/settings/#remote
