### ISSUE TITLE
How to preserve ClientConfig settings on theme upgrade

### ISSUE THREAD

**Issue by lottaar** [modxcms/fred#354]
What's the correct code for Extract Template when building a Fred theme if I want to preserve the settings in ClientConfig upon upgrade? At the moment all my ClientConfig settings are restored to default when upgrading to the latest theme build. This is what I've got at the moment:

```
{
  "packages": [
    {
      "name": "clientconfig",
      "class": "ClientConfig"
    }
  ],
  "vehicles": [
    {
      "object": {
        "class": "cgGroup",
        "graph": {
          "Settings": []
        }
      },
      "attributes": {
        "preserve_keys": true,
        "update_object": true,
        "unique_key": "label",
        "related_objects": true,
        "related_object_attributes": {
          "Settings": {
            "preserve_keys": true,
            "update_object": true,
            "unique_key": [
              "key",
              "group"
            ]
          }
        }
      }
    }
  ]
}
```

Do I need to add all my keys where it currently says "unique_key" somehow? An example would be great!

**Comment by Mark-H** [comment]
I don't know what this does in Fred but maybe set update_object on the settings to false?

**Comment by lottaar** [comment]
That seems to have done the trick, thanks Mark! I changed update_object to false in both places and now the ClientConfig settings are still in place after an update of the theme.

I'd tried setting preserve_keys to false previously but I'm not sure what that does. I'm not sure what will happen if I add new ClientConfig settings or groups to the next version of the theme though. Things turned a real mess last time I tried...

At least this preserved the values of the settings which I'm happy with for the moment:

```
{
  "packages": [
    {
      "name": "clientconfig",
      "class": "ClientConfig"
    }
  ],
  "vehicles": [
    {
      "object": {
        "class": "cgGroup",
        "graph": {
          "Settings": []
        }
      },
      "attributes": {
        "preserve_keys": true,
        "update_object": false,
        "unique_key": "label",
        "related_objects": true,
        "related_object_attributes": {
          "Settings": {
            "preserve_keys": true,
            "update_object": false,
            "unique_key": [
              "key",
              "group"
            ]
          }
        }
      }
    }
  ]
}
```
Some documentation on this would be great :)

**Comment by Mark-H** [comment]
Those attributes are the same as what you'd have in a standard build script, so this section may be of use for a bit more background on what they mean: https://docs.modx.com/current/en/extending-modx/transport-packages/build-script#packaging-in-objects

That doc uses the constants instead of the string (e.g. `xPDOTransport::UPDATE_OBJECT` instead of `update_object`) but those act the same.

**Comment by lottaar** [comment]
Thanks @Mark-H! Being a front-ender I started to feel slightly nauseaous just looking at that page, but at least now I know where to look if I become desperate ;)
