### ISSUE TITLE
How to include system settings in transport package

### ISSUE THREAD

**Issue by lottaar** [modxcms/fred#355]
Is there any way to include system settings in the transport package? It would be great if settings such as fe_editor_lang for example could be included somehow. Also fred specific settings such as fred.element_sort and fred.element_group_sort etc if you want it to be set to rank instead of name would be handy.

**Comment by theboxer** [comment]
This can be done through a custom resolver, there's no plans on supporting this out of the box.

More info on how to write a resolver can be found in the [Developing an extra](https://docs.modx.com/current/en/extending-modx/tutorials/developing-an-extra) MODX tutorial.
