### ISSUE TITLE
Symlink to Fred resource - fingerprint not provided

### ISSUE THREAD

**Issue by wallacio** [modxcms/fred#358]
It doesn’t seem possible to create a symlink to a Fred resource. Using the same Fred template and entering a resource ID of an existing Fred resource, saving the page gives the error “No fingerprint was provided.”

I can’t see any reference to handling symlinks in Github other than a commit by @matdave  instructing Fred not to load on symlink resources in the manager.

Is this a missing feature or user error?

(previously asked on MODX Community, apologies for duplication but no responses there)

**Comment by theboxer** [comment]
@wallacio the commit from matdate resolves the issue you have. It will be included in 1.2.0 release.
