### ISSUE TITLE
Fred does not run on another context

### ISSUE THREAD

**Issue by tanzirev** [modxcms/fred#36]
Fred is not initialized on the frontend if it is run from another context (other than the 'web' context).

No errors in the console

**Comment by theboxer** [comment]
Does your user have mgr session or session in that another context?

**Comment by tanzirev** [comment]
The user has an mgr session. 
The user (admin) - sudo.

**Comment by theboxer** [comment]
Can you create me a sudo user in your site to investigate? My email is john@modx.com

**Comment by tanzirev** [comment]
ok. few moments a latter

**Comment by tanzirev** [comment]
Done

**Comment by theboxer** [comment]
So yeah, it's as I said, you don't have mgr/context session.

I suppose you're logging to the manager via `http://k44781s2.beget.tech/manager` which won't give you session for other domains. If you want to be able to see Fred for example here: `http://crm.k44781s2.beget.tech/` you either have to have frontend login or you need to login to manager from this domain.

Btw. you are using very old version of Fred.

**Comment by tanzirev** [comment]
Thank you! Understood!

**Comment by bYemma** [comment]
I have Fred on a site with two domains. Maybe you are interested in this bootstrap4 frontend login modal code:
`<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="/manager/" method="post">
          <div class="modal-body">
            <div class="form-row align-items-center">
                <div class="col-auto">
                  <input type="text" name="username" class="form-control mb-2" placeholder="Username" required>
                </div>
                <div class="col-auto">
                  <input type="password" name="password" class="form-control mb-2" placeholder="Passwort" required>
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary mr-auto" data-dismiss="modal">Schließen</button>
            <button type="submit" class="btn btn-primary" name="login" value="1">Login</button>
          </div>
          <input name="rememberme"  value="1" type="hidden">
          <input name="login_context" value="mgr" type="hidden">
          <input name="returnUrl" value="/" type="hidden">
          <input name="modahsh" value="" type="hidden">
      </form>
    </div>
  </div>
</div>`
It logs the user in and returns him to to root "/".
Open the modal with a simple Login link:
`<a href="javascript:void(0);" data-toggle="modal" data-target="#loginModal">Login</a>`
