### ISSUE TITLE
 [Feature Request] Keep Preview mode enabled once clicked

### ISSUE THREAD

**Issue by qodo** [modxcms/fred#361]
One thing I would like is for Fred to be disabled "most of the time" as the layout is slightly affected and hard to really get a picture of how it looks. One thing I'd like to request is that when you click to preview mode it stays on when you navigate around the site and/or refresh the page.

This means I would only need to click to activate Fred when I want to made edits.

Or maybe this would be a "Click to edit" type button with Fred disabled by default?

Thoughts welcome!

Thanks,

**Comment by theboxer** [comment]
Preview mode is meant to preview the current page without a need of saving it first. Once you'd navigate outside you'd loose all the changes.

To disable fred you can use `Disable Fred` under `More` menu. That will disable fred until you enable it again.
