### ISSUE TITLE
Make sidebar sub-menu items appear behind its parent instead of on-top?

### ISSUE THREAD

**Issue by qodo** [modxcms/fred#364]
When opening sub-menus would it be possible to make the sub-menu items appear behind its parent as currently, as its opening, it appears above. For third level items this means it comes all the way in from the left of the screen and feels like it's not connected to the parent menu item.

![image](https://user-images.githubusercontent.com/3908836/82665040-dbe50400-9c2a-11ea-8e95-a04dd920a591.png)

Thanks,

**Comment by matdave** [comment]
Unfortunately, this is not currently possible.
