### ISSUE TITLE
Can't save the element

### ISSUE THREAD

**Issue by esshevelev** [modxcms/fred#365]
After uploading the site from local hosting to virtual, the elements ceased to be saved. Moreover, existing elements can be edited and saved, but no new ones. I fill in the fields, click the "Save" button and nothing happens. There is no new item in the list. New MODX resources are created without problems. On a local hosting, everything works well. What could be the problem?

**Comment by matdave** [comment]
Without knowing any errors reported in your environment it would just be a slew of guesses. I am guessing it is that your virtual environment is not properly configured or differently configured than your local environments server. If you can locate a server error being reported during save, that will likely give you or us something to go one.

**Comment by esshevelev** [comment]
ModX Error log:

INSERT INTO `mysite_fred_elements` (`name`, `uuid`, `description`, `image`, `category`, `rank`, `option_set`, `options_override`, `content`) VALUES ('Test', 'f9d29f6e-e997-4f57-88cd-90a816049a62', '', 'https://via.placeholder.com/300x150?text=Test', 2, 10, 0, '', '')
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '0' for key 'PRIMARY'
)
