### ISSUE TITLE
Quick disable Fred option

### ISSUE THREAD

**Issue by robcarey** [modxcms/fred#367]
Near the top of my "simple" productivity wishlist:  It would be awesome to have a single click way to disable Fred editing mode.  As it is now, it's a tedious three click buried item.

1. Open sidebar
2. Click more
3. Click Disable Fred

When heavily testing designs I am constantly going in and out of editing mode to make sure I'm getting the desired results.  While the preview mode is handy, it's not always/frequently ideal for battle testing designs.

A single click method to disable Fred would be very handy.

**Comment by esshevelev** [comment]
I use spy mode in the browser for these purposes. This is easier than turning Fred off every time.

**Comment by rthrash** [comment]
@esshevelev by spy mode, do you mean a private browser window?

@robcarey where would you propose this be located?

**Comment by robcarey** [comment]
@rthrash - just a quick mockup, but I think a small reduction of the icon size in the three other Fred action buttons would allow for something intuitive like this:

![image](https://user-images.githubusercontent.com/3990764/96166290-c62eee80-0eeb-11eb-9002-ab5f38ec9ca3.png)

**Comment by matdave** [comment]
We have been talking about adding a keyboard shortcut. I like to disable Fred a lot, but I know it could easily be an accidental click or at least not part of the standard workflow. Possibly `Ctrl + Shift + F` to enable/disable Fred?

**Comment by matdave** [comment]
The next version will have the quick disable shortcut `Ctrl + Shift + F`

**Comment by robcarey** [comment]
@matdave Sounds good - I would recommend you keep a visual option on the table for a future release as well.  I'm good with a hot-key.  So are many other people "like us" :)

My clients for whom Fred is designed to be the primary audience?  Not so much :)
