### ISSUE TITLE
HTML tags in text and textarea options

### ISSUE THREAD

**Issue by esshevelev** [modxcms/fred#368]
Hey people. I want to use tags such as br, strong, italic for text in option fields of elements. When saved, tags are visible as plain text. I can’t understand how to make the browser consider them HTML tags. It seems like something like a htmlspecialchars() function is being used.
If it is impossible to use tags in options, then how to make a line brake?

**Comment by zaigham** [comment]
I think you might be looking for https://modxcms.github.io/fred/themer/elements/attributes/#data-fred-rte
