### ISSUE TITLE
Secret xhr signing (fred.secret) not generated

### ISSUE THREAD

**Issue by genkadama** [modxcms/fred#369]
i have 2 different installation with Fred both had fred installed and uninstalled multiple time.
i got multiple problem with doing that but now i'm left with no fred.secret system settings.
i tried a fresh install on a third server and this one work properly.
Anyone got an idea as to why??

**Comment by genkadama** [comment]
how can i get my secret xhr since i don't want to start everything from scrap???

**Comment by theboxer** [comment]
Create a `fred.secret` system setting (if it doesn't exist) and fill it with some random password. It doesn't matter what the value will be. But the system setting should create automatically when an XHR request is made.
