### ISSUE TITLE
Pages' content disappears

### ISSUE THREAD

**Issue by seobeltg** [modxcms/fred#37]
Recently we have installed your plugin. Thanks!
But there is a problem that we can't solve: pages' content disappears.
If any resource made via plugin is edited (absolutely any editing, even the most insignificant, not related to Fred) and saved, everything created with Fred disappears on the front-end of the page (there are only the elements written in the html-template).
Could you tell me how to solve this problem?
Best regards

**Comment by theboxer** [comment]
You'll have to provide more details. What fred version you have, what php version you have, what modx version you have, are you creating and editing fred resources, or are you trying to switch existing resources to fred resources, any errors in error log?

**Comment by seobeltg** [comment]
modx revo version - 2.6.5

php - 7.2.5

fred - 1.0.0-beta7

Templates are made from Fenom. Head and footer - set in a template .html
The resources are assigned the {include 'file: templates / case / CaseOpenTemplate.tpl'} template, and in the * content area are displayed custom Fred chunks. Some resources (services and cases) are implemented using Fred.

**Comment by matdave** [comment]
Just to clarify, the area you are editing is targeting `data-fred-dropzone="content"` and within that wrapper you have the `[[*content]]` called as described here https://modxcms.github.io/fred/gettingstarted/#step-2-set-up-a-template, correct?

**Comment by seobeltg** [comment]
Yes, correctly
We made according to the documentation https://modxcms.github.io/fred/gettingstarted/#step-2-set-up-a-template

**Comment by theboxer** [comment]
Are you creating a new resource or switching existing one?

**Comment by theboxer** [comment]
Update to the newest version.

**Comment by seobeltg** [comment]
the update helped, thanks! But for some reason he can recognize build Fenom:
{$.....} inside tag
for example <a href="{$benefis_title.MIGX_id}">   -   interpret: %7B%24...%7D
but outside the tag (<a href="#">{$.....}</a>) it`s ok

**Comment by theboxer** [comment]
Fenom is not supported. #10
