### ISSUE TITLE
Can't set TV value by data-fred-target

### ISSUE THREAD

**Issue by PawRys** [modxcms/fred#371]
Hello!

I realy don't understand how to set TVs value by data-fred-target. Only instructions in docs are that TV must be prefixed  by "tv_" and it must be text type. Any other core fields work flawlessly but TV simply dosen't. Only working walkaround I found is by adding properties to TV [(link)](https://github.com/modxcms/fred/issues/340#issuecomment-578844297) but it isn't sutable for my project.

So I humbly ask someone to show me how to make  data-fred-target to work on TVs.

**Comment by matdave** [comment]
Your set up sound correct. Just to clarify, the _reference_ to the TV needs to start with "tv_", not the TV itself. For example, if you have a TV named "target" you would add `data-fred-target="tv_target"`. 

Additionally, one of the issues that can come up is if you have multiple elements with that TV target in it. If the last one is empty it could just cause the TV to become empty on save.

**Comment by PawRys** [comment]
_Just to clarify, the reference to the TV needs to start with "tv_", not the TV itself._ 

I have just facepalmed myself :) Its working now. Issue resolved. Thank you very much.
