### ISSUE TITLE
Documentation Typo: Select type option in example

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#377]
At the bottom of this page: https://modxcms.github.io/fred/themer/options/settings/

In the example option set titled "Example Option Set with Settings", the "options" param of the select type is an array which won't work.
```
        {
            "name": "panel_type",
            "label": "Type of Panel",
            "type": "select",
            "options": [{"value":"info", "value":"warn","value":"error"}],
            "value": "info"
        },
```

It should just be an object e.g.
```
"options": {"value1":"info", "value2":"warn","value3":"error"},
```

**Comment by rthrash** [comment]
Fixed in #338 … will be updated online when the next version is released.
