### ISSUE TITLE
Fred does not work on multiple contexts

### ISSUE THREAD

**Issue by whitegg-x** [modxcms/fred#38]
Hi,
I have installed Fred on MODx instance with multiple contexts. It works on first default context, however does not work on another contexts on same MODx instance.
Please advise,
Vit

**Comment by theboxer** [comment]
Other contexts than web is not yet supported. I hope we'll get there soon though.

**Comment by whitegg-x** [comment]
thanks for info :)
will wait for good news in next releases

**Comment by theboxer** [comment]
I did some tests and it seems like we got different contexts covered already, or at least things I tried.

Could you please be more specific in what is not working for you?

**Comment by whitegg-x** [comment]
the back-end part works, but for the frontend it do not show the controls. and when looking into web page source code using browser, it seems no scripts were loaded

**Comment by whitegg-x** [comment]
I just did a test and you are right. When I login with the same url it works. You saved my day. Thanks a lot.

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/is-there-a-magic-button-for-fred-contexts/3760/7
