### ISSUE TITLE
All elements appear in all categories

### ISSUE THREAD

**Issue by robcarey** [modxcms/fred#382]
With the Fred 1.2 update, I am finding all my elements are now not respecting their element categories.

Every element appears in every element category listing despite being assigned to different categories:

Was working fine prior to update.

![image](https://user-images.githubusercontent.com/3990764/98688263-a77c1600-2338-11eb-92f3-20d3650ee35e.png)

**Comment by robcarey** [comment]
OK - I was able to resolve this by going through every element and every element category and assigning a template to them.

I could see this being a bit of a chore on sites where I have dozens of elements, but I see where you are going with this and it's a great way to limit and organize only those needed elements and blueprints for various templates.

Perhaps some way to be able to bulk-assign/manage elements and blueprints?  i.e. With checked, assign template XXX?

**Comment by theboxer** [comment]
This is a bug for sure, let me fix that asap. Thanks for reporting it
