### ISSUE TITLE
Focused select in settings is white-on-white?

### ISSUE THREAD

**Issue by martinf55** [modxcms/fred#386]
After clicking an option in the Fred settings panel, it is focused, and invisible, because the foreground and background colors are both white.

_forms.scss:167

```
  input[type="text"], input[type="date"], textarea, select, .choices {
    background-color: $offwhite;
...
    &:focus {
      background-color: $white;
```

and later at :372 or so

```
select{
...
  &:focus, &:active{
    color: $white;
```

**Comment by matdave** [comment]
this is fixed in PR #408
