### ISSUE TITLE
Element Templates Drop-down

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#390]
The Element Templates drop-down does not save the selected value on first save. The page refreshes after saving the Element, and the drop-down is empty. Select the Template again, and this time it saves it when the Element is saved again.

I'm not sure what exactly happens if an Element is used without a template being selected, but in any case that's not the expected behavior of a select drop-down.

<img width="200" alt="select-drop-down" src="https://user-images.githubusercontent.com/1073780/106349101-c523a080-62d3-11eb-8259-7d6d066ead13.png">

**Comment by sottwell** [comment]
I checked the database, and the modx_fred_element_template_access really isn't there after the first, create, save. It is there after the second, update, save.

**Comment by sottwell** [comment]
I see that all of the other Fred create and update processors where templates are assigned have an afterSave function that deals with the templates, but the element's create processor does not. I rather imagine this is why the templates field is not saved on first creating a new element.

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/element-templates-drop-down-not-saving/3581/1

**Comment by sottwell** [comment]
Um... that's my link to this issue.

**Comment by sottwell** [comment]
I found the "relevant details" in the core/components/fred/processors/mgr/elements/create.class.php, it's missing the afterSave function.

**Comment by sottwell** [comment]
`    public function afterSave()
    {
        $templates = $this->getProperty('templates');
        $templates = array_map('intval', $templates);
        $templates = array_filter($templates);

        foreach ($templates as $template) {
            $categoryTemplate = $this->modx->newObject('FredElementTemplateAccess');
            $categoryTemplate->set('element', $this->object->id);
            $categoryTemplate->set('template', $template);
            $categoryTemplate->save();
        }

        return parent::afterSave();
    }
`

**Comment by sottwell** [comment]
At the end of the processor, that solves the issue.

**Comment by sottwell** [comment]
Well, it may solve the issue of not saving the templates on the first save, but it breaks Fred altogether. That JSON must have gotten scrambled.
