### ISSUE TITLE
UI issue with 1.2.2

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#393]
A minor issue with UI appearance - the Preview button does not look right. It still works as expected.

<img width="90" alt="Screen Shot 2021-02-07 at 22 17 05" src="https://user-images.githubusercontent.com/1073780/107158439-98861d80-6992-11eb-8d53-f67a6d332288.png">

**Comment by sottwell** [comment]
There's also a flash of the preview's X close button slightly offcentered over the save check mark after clicking on the Preview button before the Preview opens.

**Comment by matdave** [comment]
Have a feeling this was just part of a bad CSS compile.

**Comment by sottwell** [comment]
fixed with 1.2.3
