### ISSUE TITLE
Element titles are displayed

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#394]
The Fred element titles are displayed, in some cases causing HTML layout to break. This isn't critical, as it's only in the Fred edit view, in normal views they are gone. Or is it supposed to do that?

<img width="1063" alt="Screen Shot 2021-02-07 at 22 20 33" src="https://user-images.githubusercontent.com/1073780/107158488-13e7cf00-6993-11eb-942f-af6214ca6bc7.png">

**Comment by matdave** [comment]
If this was fred 1.2.2 there was an issue with my version of yarn that caused the CSS to compile incorrectly. I updated and rebuilt it. Please see if this still persists in 1.2.3

**Comment by sottwell** [comment]
Solved with 1.2.3
