### ISSUE TITLE
Image paths not correct

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#395]
Fred 1.2.2 update

The situation where {{theme-dir}}path/to/image.jpg is missing the {{theme-dir}} part is still a problem. It looks OK in editing mode, but in preview mode or in normal view the theme's path is missing.

<img width="230" alt="Screen Shot 2021-02-07 at 22 26 16" src="https://user-images.githubusercontent.com/1073780/107158557-a4beaa80-6993-11eb-9d75-c2f70752e1d8.png">

<img width="548" alt="Screen Shot 2021-02-07 at 22 27 06" src="https://user-images.githubusercontent.com/1073780/107158560-aa1bf500-6993-11eb-9c4b-8825358eb5ce.png">

**Comment by matdave** [comment]
Can you confirm what is being actually put into the content area on the resource?

**Comment by sottwell** [comment]
Fixed with 1.2.3
