### ISSUE TITLE
Element toolbar premature menu display

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#396]
Version 1.2.2 - the Fred Element toolbars pop up on hover with the menu fully displayed, without clicking on the gear icon.

<img width="200" alt="Screen Shot 2021-02-09 at 16 41 21" src="https://user-images.githubusercontent.com/1073780/107380025-2e868900-6af6-11eb-9f04-d827f910638c.png">

**Comment by sottwell** [comment]
Unfortunately it also won't go away, leaving an Element's content virtually un-editable.

<img width="250" alt="Screen Shot 2021-02-09 at 18 37 57" src="https://user-images.githubusercontent.com/1073780/107396132-259db380-6b06-11eb-8176-3a8bdcdcc72c.png">

**Comment by sottwell** [comment]
I had thought that perhaps all of these oddities with 1.2.2 were because of conflicts with the themes I was trying to use, but it is doing the same odd things in the Creative One Page theme too.

<img width="250" alt="Screen Shot 2021-02-09 at 18 43 40" src="https://user-images.githubusercontent.com/1073780/107397137-11a68180-6b07-11eb-93c1-96e05b06e174.png">

**Comment by matdave** [comment]
This should be fixed with the latest (re)build.
