### ISSUE TITLE
Element and Drop Zone Menus Overlap

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#397]
Version 1.2.2 - Element and Dropzone menus overlap. 

<img width="150" alt="Screen Shot 2021-02-09 at 17 53 28" src="https://user-images.githubusercontent.com/1073780/107390104-06038c80-6b00-11eb-9cfe-80913bf59601.png">

**Comment by matdave** [comment]
This should be fixed with the latest (re)build.
