### ISSUE TITLE
Errors Building Theme

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#399]
Version 1.2.2 - with the previous version the theme builds without error.

The build fails with simple "Error" javascript message.
<img width="289" alt="Screen Shot 2021-02-10 at 14 18 29" src="https://user-images.githubusercontent.com/1073780/107509211-dfe6f680-6baa-11eb-89ec-1f62b2aeb6e3.png">

MODX error log shows 

`[2021-02-10 14:18:22] (ERROR @ /paas/c0235/www/core/xpdo/xpdo.class.php : 644) Could not load class: xPDOScriptVehicle from transport.mysql.xpdoscriptvehicle.
`

**Comment by matdave** [comment]
There's a broken dependency issue. This will be fixed in the next release.
