### ISSUE TITLE
Element names not showing in Firefox.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#4]
Works fine in Chrome but the element names are not showing in Firefox. (In the sidebar)

Moving the mouse over where the invisible element is still shows the tooltip description and you can still grab the element to drop it.

![screenshot_2018-07-09 home - modx revolution](https://user-images.githubusercontent.com/5160368/42429842-38041eba-836e-11e8-9e04-5f71506b6ccc.png)

**Comment by digitalpenguin** [comment]
Update: Works fine if you've got an image set for the element. It's just if you don't, nothing shows.

**Comment by theboxer** [comment]
New build will have default images in case there's none defined :)
