### ISSUE TITLE
Sidebar slow inside blueprint menu on Firefox.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#40]
This only appears to be an issue in Firefox. Chrome works as expected.

When opening the blueprints menu option in the Fred sidebar, it can take up 5-10 seconds for the category to recognise it's been hovered over. 
Works as expected in the elements menu section. It only affects blueprints.

See attached gif:
![giphy](https://user-images.githubusercontent.com/5160368/47400515-16956a80-d770-11e8-9789-35f95dc27ee0.gif)

Using: Fred beta 8, MODX 2.6.5, Firefox 63.0

**Comment by theboxer** [comment]
Ah, thanks - it re-requests all assets cause it's loading the preview so it can do a screenshot for whole page blueprint. I deferred this process after you click the create blueprint button. Hopefully it resolved this issue.
