### ISSUE TITLE
data-fred-min-height not working

### ISSUE THREAD

**Issue by sottwell** [modxcms/fred#400]
version 1.2.2

The data-fred-min-height attribute isn't working. The drop zone between the menu bar and the footer is not given a height.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/1073780/107537663-cefaad00-6bcb-11eb-88f5-ea7a8fd50549.png">

Previous version:
`<div data-fred-dropzone="content" data-fred-target="content" data-fred-min-height="500px" style="min-height: 500px;">`

1.2.2
`<div class="container" data-fred-dropzone="content" data-fred-min-height="500px">`

**Comment by matdave** [comment]
it works, just not universally supported yet. The suggested fallback is to use regular "min-height" style property, or you can create a style in your css for "*[data-fred-dropzone] { min-height: 500px }"

**Comment by sottwell** [comment]
It works now with the 1.2.3 update. Thank you!
