### ISSUE TITLE
Hovering over top element in menu causes other elements to flash in a cycle.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#41]
This affects both Firefox and Chrome.

If you have more than one element in a category, and you hover the cursor over the title of the top element, the other elements all start flashing as though they're being hovered over.

It only occurs with the top element. Others work as expected.

See attached gif:
![giphy2](https://user-images.githubusercontent.com/5160368/47400923-c6b7a300-d771-11e8-946d-15e122d1b09b.gif)

Using Fred beta8, MODX 2.6.5, Firefox 63.0 / Chrome 70.0

**Comment by matdave** [comment]
Thanks, fixed it.
