### ISSUE TITLE
Min-width on fred--toolbar handle class not wide enough for small elements.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#43]
For a narrow element it seems the min-width on the fred--toolbar handle class isn't wide enough so the menu items wrap around out of view.

![screenshot from 2018-10-25 15-46-19](https://user-images.githubusercontent.com/5160368/47484280-e633f600-d86d-11e8-9dcf-431498b43978.png)

This makes it impossible for an end-user to delete the element.

Currently min-width is set to 172px. Setting it to 300px fixes it.

Fred 1.0.0-beta8

**Comment by matdave** [comment]
Thanks, fixed it.
