### ISSUE TITLE
Feature Request: Cached & Resized Images with phpthumbof

### ISSUE THREAD

**Issue by reikotec** [modxcms/fred#47]
Hi, :-)
I've build a custom Image Element that resizes and caches the Image. No Problem! But _when I rebuild the Ressources or update a TV the Images disappear in the Frontend,_ because the snippet phpthumbof is not called?

**Frontend Source Code:**
`<img src="%5B%5B!phpthumbof?%20&amp;input=%60/assets/images/...%60%20&amp;options=%60&amp;h=200&amp;w=800&amp;zc=%60%5D%5D" alt="" class="img-responsive">`

**My Element Markup:**
`{% if link %}<a href="{{ link }}" {{ target }}>{% endif %}<img src="[[!phpthumbof? &input=`{{ img }}` &options=`&h={{ height }}&w={{ width }}&zc={{ zc }}`]]" alt="{{ alt }}" class="img-responsive">{% if link %}</a>{% endif %}`

After opening the Page in Fred and saving, the Images are displayed but changed in the Position....

Is that my fault, a Problem with Fred / Twig or with pthumb?
It would be nice if in the future version the standard image element can be resized and creates thumbnails on its own.

**Comment by theboxer** [comment]
Does your element use option set or option override with remote: true?

**Comment by reikotec** [comment]
Yes, editing and saving in Fred is no Problem. Only if I rebuild the ressources or update a TV for example, the Images disappear. 

**The Options:**
`{
  "remote": true,
  "settings": [
    {
      "name": "img",
      "label": "Bild",
      "type": "image"
    },
    {
      "name": "alt",
      "label": "Alt Text",
      "type": "text"
    },
    {
      "name": "width",
      "label": "Breite",
      "type": "slider",
      "min": 800,
      "max": 1920,
      "step": 10,
      "value": 800
    },
    {
      "name": "height",
      "label": "Höhe",
      "type": "slider",
      "min": 100,
      "max": 1080,
      "step": 10,
      "value": 600
    },
    {
      "name": "zc",
      "label": "Zoom Crop",
      "type": "toggle",
      "value": true
    },
    {
      "name": "link",
      "label": "Link",
      "type": "text"
    }
  ]
}`

**Comment by theboxer** [comment]
Ah, that's the auto encoding for image's src...

**Comment by reikotec** [comment]
I'm sorry but I have no idea how to fix it.... :(

Feature Request:

>  It would be nice if in the future version the standard image element can be resized and creates thumbnails on its own.

**Comment by theboxer** [comment]
Next release should fix the issue
