### ISSUE TITLE
Double Gear Icon when updating 

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#478]
When editing in 3.0.x, a double gear icon is shown:

<img width="665" alt="Screenshot 2023-05-02 at 3 43 29 PM" src="https://user-images.githubusercontent.com/234237/235781971-da8f2b8a-dcc1-4f94-b4b9-13eed9daa5c0.png">

**Comment by theboxer** [comment]
@rthrash When editing what?

![CleanShot 2023-05-03 at 10 17 24](https://user-images.githubusercontent.com/845220/235864567-064b2392-cdac-43a1-9ddf-1ccb1b7b5627.png)

**Comment by rthrash** [comment]
Closing since unable to reproduce lately
