### ISSUE TITLE
Thumbnails in new Media Browser not working

### ISSUE THREAD

**Issue by neoneddy** [modxcms/fred#487]
FRED and MODX updated to latest.

I'm expecting thumbnails for these.  Image preview works fine, but no thumbnails.

![image](https://github.com/modxcms/fred/assets/819083/cc4d2095-bd73-436f-abda-392b235e573c)

**Comment by matdave** [comment]
Thanks for reporting. I've got a new push that fixes this. I'll get a release out ASAP.
