### ISSUE TITLE
Allow sorting by rank on elements (not just categories)

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#49]
Currently you can set a system setting to sort element categories by rank, but not the elements themselves.
They don't seem to be sorting by either rank or name at the moment. Perhaps id?

**Comment by rthrash** [comment]
IMO they should sort by rank first, with an option to sort alphanumeric. I agree it’s likely by ID.

**Comment by rthrash** [comment]
(Hello drag to order in the manager component!)
