### ISSUE TITLE
FRED Not saving links

### ISSUE THREAD

**Issue by DmitryFX** [modxcms/fred#490]
I have an element with custom RTE config to easily edit links.

![image](https://github.com/modxcms/fred/assets/17983905/a5199c44-4115-4c2e-887d-17335e35468d)

```
{
  "theme": "modern",
  "inline": true,
  "menubar": "link",
  "plugins": "link",
  "toolbar": "link",
  "forced_root_block": "",
  "allow_unsafe_link_target": true,
  "target_list": [
    {
      "title": "В той же вкладке",
      "value": "_self"
    },
    {
      "title": "В новой вкладке ",
      "value": "_blank"
    }
  ]
}
```

The link attributes are updated, when closing RTE editor:

```
<a href="https://avan.ru" class="btn btn_simple js-tabs__tab is-active mce-content-body mce-edit-focus" data-fred-name="link_adress" data-fred-rte="true" data-fred-rte-config="Fred_RTE_Link" data-fred-editable="true" contenteditable="true" id="mce_3" style="position: relative;" spellcheck="false" data-mce-href="https://avan.ru" target="_self">ЧТО ВЗЯТЬ С СОБОЙ</a>
```

But not saved after saving the page and refreshing or viewing it in the regular web context. Href attr is switched back to default empty state:

```
<a href="" class="btn btn_simple js-tabs__tab is-active">ЧТО ВЗЯТЬ С СОБОЙ</a>
```

**Comment by matdave** [comment]
You can't put `data-fred-name="link_adress"` and `data-fred-rte="true"` on an anchor as that will trigger two different behaviors. You would need to do one or the other. 

If you want the link to be fully editable with MCE, how I will generally set that up is something like

```
<span data-fred-name="link" data-fred-rte="true" data-fred-rte-config="cta"><a href="example.com">Insert Link</a></span>
```

Then I will set the CTA RTE Config up like this example:

```
{
  "theme": "inlite",
  "inline": true,
  "plugins": "link contextmenu code",
  "selection_toolbar": "bold italic | link | code",
  "valid_elements": "a[href|target|class],br,strong,em,span"
}
```
