### ISSUE TITLE
PHP warning: Undefined array key "modifyPermissions"

### ISSUE THREAD

**Issue by lottaar** [modxcms/fred#491]
Every time a page with a Fred template is loaded the following error is generated twice in the MODX error log:

`[2023-11-08 07:47:25] (ERROR @ /var/www/vhosts/mydomain.com/httpdocs/core/cache/includes/elements/modx/revolution/modplugin/13.include.cache.php : 205) PHP warning: Undefined array key "modifyPermissions"
`

MODX 3.0.4-pl
Fred 2.1.4-pl
PHP 8.2.12

**Comment by bwente** [comment]
Did you install any other Fred components?

Ace?
TinyMCE?
FontAwesome?

**Comment by lottaar** [comment]
Yes, all three of them.

**Comment by bwente** [comment]
Hmm. I did the same and I am also getting those errors. I came here to searching for an answer as well.

**Comment by lottaar** [comment]
There seems to be quite a few issues with Fred and MODX 3 unfortunately. I think Fred is a pretty vital extra for MODX – it's awesome when it works – so let's hope someone picks it up.

**Comment by matdave** [comment]
These are warnings and not errors. I've got a fix pushed up for the plugin, though.
