### ISSUE TITLE
Elements side bar animation

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#5]
Currently if you have multiple element categories and you move the mouse over the various categories, the inner element panel shoots off to the side and the new one moves in from the side to replace it.

I understand it's a matter of personal preference but it would be nice to only have this animation when initially opening. When switching categories the inner panel should stay in place and perhaps just quickly fade the content out and in.

Also when the panel does open, it would be nice if it came from *behind* the parent panel rather than appearing on top. This would stop the flicker and make it look more solid.

**Comment by matdave** [comment]
Opening behind isn't possible without a major rewrite, but we can probably look at having a default image if no image is specified. I might play with the animations a bit before PL. I think they animated like that at one point and then went back to full multi-direction fly out.

**Comment by matdave** [comment]
The animation has been updated to only slide out.
