### ISSUE TITLE
Uncaught error when trying to save page with fred template

### ISSUE THREAD

**Issue by HenrikCatch** [modxcms/fred#504]
After installing Fred and assigning the default theme to a template, I get this error when trying to save the resource:

Uncaught Error: Class name must be a valid object or a string in /path/to/site/core/components/fred/src/Traits/Elements/Event/OnDocFormSave.php:23\nStack trace:\n#0......

What can i do to fix this? Version 3.0.0-rc1.

**Comment by matdave** [comment]
Is this on MODX 2.x?

**Comment by matdave** [comment]
Found it, on 3.x check for the fix here: https://github.com/modxcms/fred/commit/a86415bc449edfff3cfe80d9c7faaafb8a1beebb

I'll be including this in a release soon.
