### ISSUE TITLE
PHP warning: Undefined array key "fred"

### ISSUE THREAD

**Issue by lottaar** [modxcms/fred#516]
The MODX error log quickly fills up with warnings like this:
PHP warning: Undefined array key "fred"

Even though MODX system settings logging level is set to 1 (errors).

MODX 3.0.6
Fred 3.1.4
Fred Ace Integration 1.0.0-beta
Fred Font Awesome Icon Editor 1.2.0
Fred TinyMCE RTE 1.2.4
PHP 8.3

**Comment by matdave** [comment]
This as fixed, but I just built a release for it.

**Comment by lottaar** [comment]
Great, thank you!
