### ISSUE TITLE
When Fred is enabled, third party jquery plugins such as slick.js and isotope.js don't inititalise.

### ISSUE THREAD

**Issue by muzzwood** [modxcms/fred#53]
On my current project that uses Fred, I'm using: 
- Slick Slider: http://kenwheeler.github.io/slick/
- Isotope: https://isotope.metafizzy.co/ 
- ImagesLoaded: https://imagesloaded.desandro.com/

These are all common JQuery plugins.
When Fred is enabled, they don't initialise for some reason. When logged out (Fred not enabled) they initialise fine.

**Comment by theboxer** [comment]
You have them in ready callback, or how do you init them?

**Comment by digitalpenguin** [comment]
After a bit more playing around it seems even some basic JQuery manipulations don't work e.g.
```
$( document ).ready(function() {
    // Form Field Label Animations
    $('form input[type=text],form input[type=email]').on('focus', function(e) {
        $("label[for='" + e.target.id + "']").addClass("focused");
    });
    $('form input[type=text],form input[type=email]').on('blur', function(e) {
        if( !$(this).val() ) {
            $("label[for='" + e.target.id + "']").removeClass("focused");
        }
    });
});
```
Yet, Bootstrap works fine.

**Comment by theboxer** [comment]
I tried the slick slider as with same init script as you sent and it works fine...

Could you build the whole theme including the JS and send it to me? Or if you can give me an access to the manager (email: john@modx.com)?

**Comment by digitalpenguin** [comment]
Ah! I worked it out!
It doesn't work when `remote` is set to true in the options.

**Comment by digitalpenguin** [comment]
Email sent with manager access. Cheers @theboxer !

**Comment by theboxer** [comment]
Hey,

thanks for doing more testing on this. I've updated your site with the newest JS file, where I hope it'll work. Could you please try and let me know if the issue is now resolved?

**Comment by digitalpenguin** [comment]
Yes, it looks to be working now! Great stuff. :)
