### ISSUE TITLE
Fred toolbar sometimes inaccessible behind other elements

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#54]
Sometimes the Fred element toolbar is hidden behind other elements and cannot be accessed.
For example in the video below, I have some nested dropzones. I have bootstrap tabs and each tab has its own dropzone. I have a "package" container in that dropzone and then an individual package in that container's dropzone. 

![fred-hiding](https://user-images.githubusercontent.com/5160368/48599406-79aaa380-e9a2-11e8-8823-6ed467d95429.gif)

There's two things going on here. Firstly, the toolbar of the innermost element is blocked by the bootstrap tabs. 
Secondly (not sure if it's by design) a blanked out toolbar of the tabs element is also appearing at the same time. 

(@theboxer I'll upload a copy of this project soon and give you manager access so it's easier to troubleshoot the issues I'm bringing up)

**Comment by theboxer** [comment]
Weird, it seems to work fine for me:
![image](https://user-images.githubusercontent.com/845220/48614291-2fb7c280-e98e-11e8-8d6b-4b5605c27793.png)

**Comment by digitalpenguin** [comment]
Ah I think that's just because the extra text above was added so it wasn't right next to the tabs.
I've removed that now if you want to try again.

**Comment by digitalpenguin** [comment]
It looks like this is because of containing elements and the overflow CSS rule.
It would be great if it could somehow be ignored for the Fred toolbar. If not possible, we'll just have to take that into account I guess :)

**Comment by matdave** [comment]
Right now since the toolbar is an element within the Fred block, it can't override outer elements that have overflow hidden. It is a browser and style limitation. To fix we could made the toolbar independent of the Fred block, but I'm not sure if that is possible with how it interacts with the dropzone system. 

This is probably going to currently linger as a limitation.

**Comment by digitalpenguin** [comment]
Cheers for looking into it @matdave ! No problem, I assumed that would be the case.

**Comment by theboxer** [comment]
Can I close this one? It seems like we won't be able to resolve it...

**Comment by digitalpenguin** [comment]
Sorry, wasn't sure if this was addressed to me or not. But yes, it's fine for me to close. Thanks.
