### ISSUE TITLE
Edit button in sidebar not working unless resource is published.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#56]
I discovered this by going to the "Site" menu in the sidebar, clicking on a page and then clicking on "Create Child Page". 
After filling in the details and clicking "Create Page", I'm redirected to the home page instead of going to the newly created resource. (My home page is still the error_page so it could have been a 404).

In the sidebar menu I navigate to the new page and click Edit but nothing happens. It was only through trial and error I found that publishing it and then refreshing the page allowed the edit button to work.

**Comment by theboxer** [comment]
Does your user has permissions to view unpublished resources?

**Comment by digitalpenguin** [comment]
Yes, sudo user in the administrator group.

**Comment by theboxer** [comment]
That's weird, I just tried the steps you mentioned and it works fine...

**Comment by digitalpenguin** [comment]
Damn haha. OK I'll try and narrow it down.

**Comment by digitalpenguin** [comment]
Yes you've still got access. Although the problem occurred on my local install, I just tested it on the one you've got access to and it happens there too. Try creating a child resource under "Blog" which is under the parent "Barre Social". 
When I try, I'm setting the parent to Blog, the template to "Blog Post" and I'm keeping blueprint empty.

**Comment by theboxer** [comment]
Ok, it seems to be fixed now. Give it a try please.

File I changed: `core/components/fred/model/fred/src/Endpoint/Ajax/GetResourceTree.php`

**Comment by digitalpenguin** [comment]
Wow you're quick :)
Yes that's working for me, although it still redirects to the home page on creation of the new page.
Would it be possible to have it redirect to the newly created page?

**Comment by theboxer** [comment]
yeah, will look at it as well, forgot you mentioned this issue...

**Comment by theboxer** [comment]
So this file changed as well: `core/components/fred/model/fred/src/Endpoint/Ajax/CreateResource.php`

**Comment by digitalpenguin** [comment]
Perfect! Just tested it and can confirm it's working fine. Thanks a lot!
