### ISSUE TITLE
Documentation Request: RTE Configs

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#57]
If possible, could we get an examples of some RTE configs in the docs?

For example I'd like to keep all the current config settings but also make all pasting as plain text.
E.g. 
```
tinymce.init({
    plugins: "paste",
    paste_as_text: true
});
```
I'm just unaware as to what format is needed. Thanks!

**Comment by theboxer** [comment]
You should be fine with creating rte config with this as a content:
```
{
    paste_as_text: true
}
```

**Comment by digitalpenguin** [comment]
Hmm this one doesn't seem to be working for me. I've got the same as you above in a config called `paste_as_test` and the attributes are like this:
```
<div class="rich-text" contenteditable="true" data-fred-name="rich-text-full-width" data-fred-rte="true" data-fred-rte-config="paste_as_text"></div>
```

Pasting in text (with some parts bold and italicised) from another website and I can still see the bold and italics when pasted.

**Comment by theboxer** [comment]
OK, I'll take a look at this. I'm working on a fix from copying from contenteditable area (that doesn't have RTE there) as well.

**Comment by digitalpenguin** [comment]
Thanks, much appreciated!

**Comment by theboxer** [comment]
ok, found it. You have to include `paste` plugin as well, so this is the config you need:
```
{
  "plugins": "modxlink image imagetools media lists paste",
  "paste_as_text": true
}
```

**Comment by digitalpenguin** [comment]
Brilliant. Working thanks!
