### ISSUE TITLE
Element order changes. Images are moved down.

### ISSUE THREAD

**Issue by reikotec** [modxcms/fred#58]
![grafik](https://user-images.githubusercontent.com/41062056/48714478-170c0e80-ec13-11e8-88ce-3d946d4cab5a.png)
Yeah thank you very much! I am at least 42% more happy :dancing_women: , but I still have one issue.

![grafik](https://user-images.githubusercontent.com/41062056/48714040-0f983580-ec12-11e8-8d3a-bb06560bcafd.png)
For Example: 3 images and texts in 3 columns. 
Saving is no problem, the website is updated and displays the 3 cols correctly.

But if I open Fred again, the order is changed. The Images are suddenly moved down under the text.
![grafik](https://user-images.githubusercontent.com/41062056/48714281-a664f200-ec12-11e8-956a-3b5dd9574167.png)

Do you have any idea what's going wrong?

**Comment by digitalpenguin** [comment]
Actually I think I've come across the same thing before. I'll try to track down where it was..

**Comment by digitalpenguin** [comment]
I *think* this is the same problem. @theboxer 
On my dev site you have access to, go to the "Hong Kong Studio" resource (under classes).
On the first tab, there is the gallery slider and underneath that an instagram feed. 
Like @reikotec says, I can order them with the slider above and the feed below, save, and it looks fine when logged out. If I reload the page in Fred, the order is reversed and the feed is now on top.

I had actually forgotten about that (I just made 2 dropzones to temporarily fix it). This is the only place it's happened though and I haven't yet been able to figure out what's causing it.

**Comment by theboxer** [comment]
@reikotec I'll need more details, can you post your markup for elements and template? Including option set/override if used?

@digitalpenguin I can't reproduce it in your site, but I'm probably doing it wrong...

**Comment by theboxer** [comment]
![image](https://user-images.githubusercontent.com/845220/48721257-cf40b380-ec21-11e8-9a9d-f4b69c4267bd.png)
![image](https://user-images.githubusercontent.com/845220/48721304-e97a9180-ec21-11e8-865a-72b87569c01a.png)
![image](https://user-images.githubusercontent.com/845220/48721316-f39c9000-ec21-11e8-813f-09251bb86257.png)

I still don't see a difference there...

**Comment by digitalpenguin** [comment]
Hmmm weird...

**Comment by reikotec** [comment]
My Markups

**2 Columns:**
```
<div class="row">
<div data-fred-dropzone="left" class="{{ aufteilung }}"></div>
<div data-fred-dropzone="right" class="{% if aufteilung == 'col-md-8' %}col-md-4{% elseif aufteilung == 'col-md-4' %}col-md-8{% else %}col-md-6{% endif %}"></div>
</div>
```
Options:
`{
  "remote": true,
  "settings": [
    {
      "name": "aufteilung",
      "label": "Aufteilung",
      "type": "select",
      "options": {
        "col-md-8": "2-1",
        "col-md-4": "1-2",
        "col-md-6": "1-1"
      },
      "value": "col-md-6"
    }
  ]
}`

**Text:** 
`<div data-fred-name="rte-content" contenteditable="true" data-fred-rte="true" data-fred-rte-config="reikotec_default">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. </div>`

**Image:**
`{% if link %}<a href="{{ link }}" {{ target }}>{% endif %}<img src="[[phpthumbof? &input=`{{ img }}` &options=`&h={{ height }}&w={{ width }}&zc={{ zc }}`]]" alt="{{ alt }}" class="img-responsive">{% if link %}</a>{% endif %}`
Options:
`{
  "remote": true,
  "settings": [
    {
      "name": "img",
      "label": "Bild",
      "type": "image"
    },
    {
      "name": "alt",
      "label": "Alt Text",
      "type": "text"
    },
    {
      "name": "width",
      "label": "Breite",
      "type": "slider",
      "min": 800,
      "max": 1920,
      "step": 10,
      "value": 800
    },
    {
      "name": "height",
      "label": "Höhe",
      "type": "slider",
      "min": 100,
      "max": 1080,
      "step": 10,
      "value": 600
    },
    {
      "name": "zc",
      "label": "Zoom Crop",
      "type": "toggle",
      "value": true
    },
    {
      "name": "link",
      "label": "Link",
      "type": "text"
    }
  ]
}`
