### ISSUE TITLE
Tagger filtering not working when Fred enabled.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#59]
While Fred is enabled, clicking on a Tagger tag results in the filter being ignored and all resources under the current parent are displayed.
Works as expected when Fred is not enabled.

**Comment by theboxer** [comment]
Do you have this set up in the site I have access to? If yes, could you please point me to the resource where it is? Thank you

**Comment by digitalpenguin** [comment]
Only on my local install. I'll get it uploaded in a couple of hours for you. Thanks!

**Comment by theboxer** [comment]
OK, thank you

**Comment by digitalpenguin** [comment]
Hi @theboxer - sorry for the delay. It's up now. Go to the blog index page which is under "Barre Social".
Try clicking on the tag "FitFam" for example as that is only related to one of the posts.

There is also an issue with JQuery form animations not working on the newsletter subscribe box in the right column while Fred is enabled. This is the same thing that was happening with #53. (I applied the fix, it works on other pages). If I remove the "Blog Listing" Fred element from the left column, it starts working again. This element has remote enabled and contains a pdoResources snippet call with TaggerGetResourcesWhere included.

Finally there is the ordering issue in #58 happening in the right column. The tags should be at the top but on load the newsletter subscription box appears above. (I haven't applied your fix for this one though - just thought I'd mention it to cover all bases.)

Thanks!

**Comment by theboxer** [comment]
Try the tagger now please
