### ISSUE TITLE
Fred renders all html source code Scandinavian letters like ä,ö in umlauts

### ISSUE THREAD

**Issue by tassu** [modxcms/fred#60]
This happen **only when you are logged in** and viewing source code. When logged out all Scandinavian letters are ä,ö and so on in source code.

**Comment by theboxer** [comment]
Hello @tassu, I'm not sure I understand the issue here. Could you please help me replicate the process by sharing exact steps? Also, could you please briefly explain why this is an issue when it's happening?

Thank you

**Comment by tassu** [comment]
1. View pages source code when not logged in all those letters are like written (ä,ö,etc).

2. Log in and view pages source code. All mentioned letters are umlauts in source code. 

I can live with that, but source code is not the best to view that way.

Biggest issue is that when for example you create link to page in fred RTE (I`ve made a topic Fred RTE also if it is more related with that). If link word has mentioned letters user sees them with umlauts. In screenshot i trying to make a link word "käytössä" and link text is with umlauts. Not nice for any user.

![rte-editorview](https://user-images.githubusercontent.com/1112163/49093868-b3668e80-f26d-11e8-8b94-9c319bf96067.JPG)

**Comment by theboxer** [comment]
Could you please try and replace file `assets/components/fredrtetinymce/web/fredrtetinymce.min.js` with the one attached to this comment and let me know if it fixed the issue you are having with the link to dialog (I had to zip the file as github doesn't support JS file as an attachment)?

[fredrtetinymce.min.js.zip](https://github.com/modxcms/fred/files/2623742/fredrtetinymce.min.js.zip)

**Comment by tassu** [comment]
Now "link to" window text is ok. 

Source code of the page is still umlauts. But as I said no problem to me. Wondering that why source code changes when logged in?

**Comment by rthrash** [comment]
Since the distracting bug is sorted out, going to close this as fixed. Please feel free to re-open if you have other feedback or notice other areas with the same issue.
