### ISSUE TITLE
Preview mode has double scrollbar and cuts off the bottom of the page by 51px

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#61]
Preview mode has a double scrollbar. One for the iframe and one for the parent window. The parent scrollbar should be hidden when activating preview mode.

Also the iframe has a CSS rule `margin: 51px auto 0;` (in fred.css line 15) which allows for the toolbar at the top but this effectively cuts off the bottom 51px from the page. The height of the iframe should be increased by 51px too.

**Comment by matdave** [comment]
Thanks for reporting. This was fixed in d747651
