### ISSUE TITLE
Preview double scrollbar still in beta11

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#62]
Great work on releasing beta11! 

Unfortunately the double scrollbar issue in preview mode seems to have persisted.
Related to https://github.com/modxcms/fred/issues/61

See screenshot:
![screenshot from 2018-11-29 00-12-55](https://user-images.githubusercontent.com/5160368/49165415-1a6a6d00-f36c-11e8-9c45-696bda5acd31.png)

**Comment by theboxer** [comment]
@digitalpenguin Could you please try and use the two minified files from this commit 576ce2b490677e8231ed75d1d49f14cb71acdb0e (fred.css & fred.min.js) and try if the issue was resolved?

**Comment by digitalpenguin** [comment]
Sorry I didn't have a chance to try until now. I can confirm it's fixed in beta12! Thanks very much.
