### ISSUE TITLE
'Enable Fred' button appearing even when logged out and in private/incognito window.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#63]
Of course a user who doesn't have manager access should not be able to see anything to do with Fred. :)

beta11

**Comment by neoneddy** [comment]
Can confirm this

**Comment by bYemma** [comment]
Same here

**Comment by matdave** [comment]
d'oh, we'll get a patch pushed out ASAP

**Comment by matdave** [comment]
fixed in eeb881bf if you want to soft-patch the plugin.

**Comment by digitalpenguin** [comment]
Thanks for getting it fixed so quickly @matdave ! I can confirm the soft-patch works fine.
