### ISSUE TITLE
Empty page for not logged in users

### ISSUE THREAD

**Issue by bYemma** [modxcms/fred#64]
After updating to MODX 2.7 and Fred beta11, a guest can not see any content on a Fred Site.

I can edit the content, save it, no problems. When I visit the page with another browser there's only a "Enable Fred" Button ( Issue #63 ), but no content.

Rebuilding Fred pages and clearing the cache does not help. No entry in the error log.

**Comment by matdave** [comment]
Can you verify two things:

1) When you view the resource in the MODX manager, is there static HTML representing the Fred output?

2) Is [[*content]] being called on the page?

**Comment by bYemma** [comment]
> Is [[*content]] being called on the page?

You are kidding... That was the problem. Why did it work before without it?
