### ISSUE TITLE
Fred fails to install though Package Manager

### ISSUE THREAD

**Issue by tommyboylab** [modxcms/fred#65]
The current beta of Fred (12) is failing to complete installation on a new instance of ModX (2.7.0). Here's the output of the Package Manager during installation:

```Console running...
Attempting to install package with signature: fred-1.0.0-beta12
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Created table `modx_fred_blueprint_categories` SQL: CREATE TABLE `modx_fred_blueprint_categories` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `uuid` VARCHAR(36) NOT NULL, `rank` INT(10) unsigned NOT NULL DEFAULT '0', `theme` INT(10) unsigned NOT NULL, `public` TINYINT(1) NOT NULL DEFAULT '0', `createdBy` INT(10) unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`id`), UNIQUE INDEX `uuid` (`uuid`)) ENGINE=InnoDB 
Created table `modx_fred_blueprints` SQL: CREATE TABLE `modx_fred_blueprints` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `uuid` VARCHAR(36) NOT NULL, `description` VARCHAR(255) NOT NULL DEFAULT '', `image` TEXT NOT NULL, `category` INT(10) unsigned NOT NULL, `rank` INT(10) unsigned NOT NULL DEFAULT '0', `complete` TINYINT(1) unsigned NOT NULL DEFAULT '0', `public` TINYINT(1) NOT NULL DEFAULT '0', `createdBy` INT(10) unsigned NOT NULL DEFAULT '0', `data` MEDIUMTEXT NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `uuid` (`uuid`)) ENGINE=InnoDB 
Created table `modx_fred_element_categories` SQL: CREATE TABLE `modx_fred_element_categories` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `uuid` VARCHAR(36) NOT NULL, `rank` INT(10) unsigned NOT NULL DEFAULT '0', `theme` INT(10) unsigned NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `uuid` (`uuid`)) ENGINE=InnoDB 
Created table `modx_fred_elements` SQL: CREATE TABLE `modx_fred_elements` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `uuid` VARCHAR(36) NOT NULL, `description` VARCHAR(255) NOT NULL DEFAULT '', `image` TEXT NOT NULL, `category` INT(10) unsigned NOT NULL, `rank` INT(10) unsigned NOT NULL DEFAULT '0', `option_set` INT(10) unsigned NOT NULL DEFAULT '0', `options_override` MEDIUMTEXT NOT NULL, `content` MEDIUMTEXT NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `uuid` (`uuid`)) ENGINE=InnoDB 
Created table `modx_fred_element_option_sets` SQL: CREATE TABLE `modx_fred_element_option_sets` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(128) NOT NULL, `description` VARCHAR(255) NOT NULL DEFAULT '', `complete` TINYINT(1) unsigned NOT NULL DEFAULT '0', `theme` INT(10) unsigned NOT NULL, `data` MEDIUMTEXT NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB 
Created table `modx_fred_element_rte_configs` SQL: CREATE TABLE `modx_fred_element_rte_configs` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(128) NOT NULL, `description` VARCHAR(255) NOT NULL DEFAULT '', `theme` INT(10) unsigned NOT NULL, `data` MEDIUMTEXT NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB 
Created table `modx_fred_themes` SQL: CREATE TABLE `modx_fred_themes` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `theme_folder` VARCHAR(255) NOT NULL DEFAULT '', `uuid` VARCHAR(36) NOT NULL, `description` VARCHAR(255) NOT NULL DEFAULT '', `config` MEDIUMTEXT NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `uuid` (`uuid`)) ENGINE=InnoDB 
Created table `modx_fred_themed_templates` SQL: CREATE TABLE `modx_fred_themed_templates` (`template` INT(10) unsigned NOT NULL, `theme` INT(10) unsigned NOT NULL, PRIMARY KEY (`template`)) ENGINE=InnoDB ```

**Comment by theboxer** [comment]
Hello,
I've just tried fresh Revo 2.7.0 + Fred beta12 downloaded from package manager and everything works as expected.

The log you sent doesn't contain any error as well.

**Comment by tommyboylab** [comment]
That's what interesting, It completes the installation and the packages appear in on the server in the right places, but I am unable to check "Ok" after the installation completes, as well as the package is still marked as uninstalled by the Package Manager. Is there a way to get Revo to recognise Fred manually?

**Comment by rthrash** [comment]
Do you have any more details on your server or environment. Did you clear your browser cache after upgrading to 2.7, if it was an upgrade?

**Comment by rthrash** [comment]
I suspect this is environment related. Can you try 664 file permissions? 

Are you running suhosin or modsecurity?

**Comment by tommyboylab** [comment]
I currently have the Folder permissions of 775 and File permissions of 644, I've checked for mod-security and no suhosin as I'm running PHP 7.2.

Being as the installation seems to have been a success, I am now just looking to configure Modx manually to recognise the installation of Fred. If I can manage that then updating will be easy (as it seems any update will run as planned).

**Comment by digitalpenguin** [comment]
I think rthrash wants you to try 664 instead of 644. ;)

**Comment by tommyboylab** [comment]
Will do, I'll change them this evening after work and update this comment with the result.

**Comment by rthrash** [comment]
Any luck?

**Comment by morelmm** [comment]
I've just got similar problem, updating or installing Fred failed silently, after creating tables - package remained uninstalled. Lowering PHP from 7.0 to 5.6 made install working

**Comment by tommyboylab** [comment]
@rthrash I've been moving my website to a new VPS over the Winter Holidays. I've managed to successfully install Fred on my local environment and migrate the install (with the packages) over to the new environment by way of migrating. I cannot be sure what caused the problem with the previous install but it is the same problem @morelmm had; the package installed silently after creating the tables, though was not accessible to the manager.

**Comment by rthrash** [comment]
Hi @morelmm and @tommyboylab ,

Since this seems to be very environment specific (and with an unsupported version of PHP 7.0.x), I'm going to close this. If you can replicate the issue on PHP 7.1+ environments, please let us know and re-open this issue. Thanks!
