### ISSUE TITLE
Fred fails (2) to install though Package Manager

### ISSUE THREAD

**Issue by alipang** [modxcms/fred#69]
I believe my problem is unrelated to the other issue in the list as I come further. My installation stalls after preserving package. I think the next step would be adding the menu. I realize I have the same problem while upgrading FileAttach, where the minor change is said to be about the menu.

This is for rc1, MODX 2.7, php-fpm 7.2, Ubuntu 18.04.1, MariaDB 10.3. On a much cleaner setup I didn't have the problem.

**Comment by rthrash** [comment]
Hi. If it's failing on one setup and not the other, it seems to point to a possible config issue of MODX itself on the one where it's failing. Can you provide any more details that would point to an issue with Fred itself?

**Comment by alipang** [comment]
You are probably correct. I'll close this soon, and then study what changed between FileAttach versions and possibly find what stalls my installation of Fred.

**Comment by alipang** [comment]
I just discovered I have this issue on an almost brand new installation too. It turns out my 2 failing sites use the advanced MODX version, and the succesful use the traditional.

**Comment by alipang** [comment]
I discovered a mistake in my 2 packages on 3 installations conclusion. FileAttach on clean MODX 2.7 advanced actually works fine. Not much help in pinpointing from there.
