### ISSUE TITLE
Unique identifier within Fred Editor for elements

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#72]
Currently each Element has an unique ID. However if you have that Elements multiple times placed in on your page, the ID is no longer unique.

Currently I'm trying to manipulate the DOM of Fred Elements. In order to do this and save related Data from this in a Database, I have to link the Data to an Element. Since I cannot use the Unique ID (since they aren't really unique), I cannot do this.

What I'm looking for is that, on the moment you drop an element in a dropzone, it shows a unique ID. This can be both front end and back end (back end as in the Fred Editor). This way I can manipulate DOM elements that are triggered by going into the Fred Editor mode.

Also this might be handy for Front End usage? Visual Composer does this, that way you can potentially style certain rows/items, based on their unique class.

**Comment by rthrash** [comment]
Can you share an actual example of what you’re trying to do also, to help us understand it more clearly?

**Comment by kars-springbok** [comment]
So in my use case I want to create a comment. For example I want to post a comment on a row. In order to link the comment data to the element I have to link them. Currently I have everything in place to create a comment etc. However I cannot link the data to the element since there is no Unique ID for each Fred Element.

**Comment by theboxer** [comment]
I believe this won't be needed once we get #73 done
