### ISSUE TITLE
Hooks to hook into sidebar and fred--toolbar

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#73]
Hey,

It would be useful to be able to hook into the sidebar of Fred and the fred--toolbar that appears when you hover over elements. This way it is easier to implement customisations without touching the core. This means that it would be very easy to upgrade without loosing such customisations.

**Comment by rthrash** [comment]
The Fred sidebar now allows plugins to register new menus. Test build here: https://github.com/modxcms/fred/blob/b11b5d50bf84260829eae4902c5aed0769660b11/_packages/fred-1.1.0-alpha.transport.zip
