### ISSUE TITLE
Snippets in Fred Elements

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#74]
Hey,

Currently I'm trying to load a snippet within a Fred Element, to display current user info for example. However it returns the actual snippet code. So I get [[snippet]] instead of the info the snippets returns. 

On the documentation I couldn't find anything related to snippets in Elements so I assume it is not implemented. However, it would most definitely enhance the power of Fred Elements if it would allow the usage of Snippets. 

Maybe a good feature to have?

**Comment by kars-springbok** [comment]
So I read on Slack that I need to set remote to true in the option set. (https://modxcms.github.io/fred/themer/elements/option_sets/) This show the snippet. However, my goal is to save the content of the snippet as HTML in the Database. 

Use case:
A user drops an element with user info, username + profile pic. He drops it in and saves. Now I wanted his profile pic and username to be saved in the Database. 

Currently if I log in and drop in the element it works for my user info. However if I log in with another user that info is displayed, since the snippet is being saved and not the output of the snippet.

**Comment by sjmclean24** [comment]
@rthrash might be a solution if there an option is introduced : saveAsHtmlRendition (or a similarly named option).

This would allow snippets to load content dynamically and then save as rendered in the HTML, rather than back as the snippet call to re-render on the next call.
