### ISSUE TITLE
Trigger OnDocFormSave

### ISSUE THREAD

**Issue by sjmclean24** [modxcms/fred#75]
We have VersionX which triggers on the OnDocFormSave hook. When saving a resource with Fred, it appears that this hook is not being triggered.

The combination of Fred + VersionX would make it very powerful.

Functionality We Are After : We are developing a customised tab containing history versioning within Fred, whereby having VersionX would make it easier to go between versions.

Is this something that can be looked into?

**Comment by Mark-H** [comment]
Hey @theboxer - while this was closed with the addition of a new event, any chance fred will simply fire the standard OnDocFormSave?

**Comment by theboxer** [comment]
Unfortunately it can't, as it doesn't have all fields and details as it does from manager...

**Comment by Mark-H** [comment]
[Docs only lists $id, $resource, and $mode](https://docs.modx.org/current/en/extending-modx/plugins/system-events/ondocformsave) - so wouldn't you only need to add mode? That would make Fred play nice with other extras out of the box..

**Comment by theboxer** [comment]
Yup, the issue is not in these params, but in the content of `$resource` object, as from mgr it has all TVs in a specific format (generated from ext and custom renderers) and other custom properties generated from other addons (tagger is one of them too) and they rely on what is rendered on the mgr form. I can't simulate all of this on frontend and not passing these props in the resource object may result in saving incorrect data for other plugins.

**Comment by JANogueira** [comment]
Hi All,

I have assigned VersionX plugin to the system events FredOnBeforeFredResourceSave and FredOnFredResourceSave but it seems not to be working.
Used a different user for frontend editing only, changed the resource and saved. Nothing was registered.

**Comment by JANogueira** [comment]
Hi Guys,

This is still not working properly with Fred 1.1.1-pl using these Plugin events for VersionX:
![image](https://user-images.githubusercontent.com/22750391/68111772-d40c7f00-fee7-11e9-992d-3b777746499c.png)


Is there any workaround for this?
This would be just great if VersionX could work with Fred, as sometimes content editors can mess the things up a bit, and VersionX would be an incredible help to recover data and for versions auditing.

Thanks in advance.

**Comment by theboxer** [comment]
It's not supposed to work out of the box. You need to create a custom plugin and trigger version x on your own. Something like:
```
<?php
$path = $modx->getOption('versionx.core_path', null, MODX_CORE_PATH . 'components/versionx/');
$versionx = $modx->getService('versionx', 'VersionX', $path . 'model/');
if (!$versionx) {
    $modx->log(modX::LOG_LEVEL_ERROR, 'Could not load VersionX from ' . $path);
    return;
}
switch ($modx->event->name) {
    case 'FredOnFredResourceSave':
        if ($modx->context->key === 'mgr') break;
        if ($modx->getOption('versionx.enable.resources',null,true)) {
            $result = $versionx->newResourceVersion($resource, 'upd');
        }
        break;
}
return;
```

**Comment by JANogueira** [comment]
Hi John,

I tried to adapt your code and while trying to get current resource ID on the new plugin, this seems to be impossible.
So, I created the plugin, docked into FredOnFredResourceSave, but never gets the resource id when saving a page on fred.

Are you aware of any limitation on getting current resource ID from plugin? (**Alert**: Modx plugin n00b here 😋).

Code:
```

<?php
$path = $modx->getOption('versionx.core_path',null,$modx->getOption('core_path').'components/versionx/');
$versionx = $modx->getService('versionx', 'VersionX', $path . 'model/');
$resource = $modx->resource->id;

if($resource == '' || $resource == false)
{
    $modx->log(modX::LOG_LEVEL_ERROR,'[FredVersionxTrigger] Not possible to retrieve current Resource ID');
    return;
}

if (!$versionx) {
    $modx->log(modX::LOG_LEVEL_ERROR, '[FredVersionxTrigger] Could not load VersionX from ' . $path);
    return;
}

$eventName = $modx->event->name;
switch ($eventName) {
    case 'FredOnFredResourceSave':
        if ($modx->context->key === 'mgr') break;
        if ($modx->getOption('versionx.enable.resources',null,true)) {
            $result = $versionx->newResourceVersion($resource, 'upd');
        }
        break;
}
if (isset($result) && $result === true)
    return;
elseif (isset($result)) {
    $modx->log(modX::LOG_LEVEL_ERROR,'[FredVersionxTrigger] An error occured. Event: '.$eventName.' - Error: '.($result === false) ? 'undefined error' : $result);
    return;
}

```

Error message with Debug:
```

[2019-11-04 20:51:48] (WARN @ D:\xampp\htdocs\core\cache\includes\elements\modplugin\29.include.cache.php : 4) PHP notice: Trying to get property 'id' of non-object
[2019-11-04 20:51:48] (ERROR @ D:\xampp\htdocs\core\cache\includes\elements\modplugin\29.include.cache.php : 8) [FredVersionxTrigger] Not possible to retrieve current Resource ID


```

**Comment by theboxer** [comment]
I'm using the plugin I sent you and it's working fine. `$resource` is passed in `$scriptProperties` to the plugin, you can't grab it from `$modx->resource`.

**Comment by JANogueira** [comment]
Hi John,

Many thanks. it is confirmed that works.
Can I suggest to add this on the Fred documentation as an example for the Fred events triggering? At the same time, you would me "solving" a very requested feature for Fred users with VersionX.

Many thanks in advance.

**Comment by Mark-H** [comment]
I'll add that into VersionX.

**Comment by Mark-H** [comment]
FYI, this has been added to VersionX 2.4.
