### ISSUE TITLE
Breadcrumb to reach overlapping elements

### ISSUE THREAD

**Issue by sebclemens** [modxcms/fred#76]
If an element overlaps another, I can't select it anymore. A breadcrumb solution would be perfect. I would implement this by myself and create a PR but need help for the best approach.

What do you think about this?

**Comment by rthrash** [comment]
Hi @sebclemens … could you add a mockup or screenshot sketch to illustrate the issue and proposed solution?

**Comment by matdave** [comment]
We would need something like the content tree on Neos CMS, but I'm not sure where it would live. 
![image](https://user-images.githubusercontent.com/2213127/51924284-5ba1ec00-23b2-11e9-994f-093cabdbad0e.png)
