### ISSUE TITLE
Disappearing nested flyout in Safari

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#78]
A [commit to address flatpicker issues](https://github.com/modxcms/fred/commit/bbae53eff11af6e39f8e1b7f2f6fc41c421adc3d#diff-fefe453cf1cf475ea152dd7e1f10989b) added `overflow-y: auto` to the `.fred .fred--panel` Sass. This has the side effect of making nested groups disappear in Safari, which I really think is a bug in webkit as it doesn't make sense. Anyway … 

@matdave can the two overflow rules be merged into a single `overflow: visible`, which fixes the problem in Safari?

**Comment by matdave** [comment]
This was fixed in the sidebar, but not in the panel.  I've pushed a fix.
