### ISSUE TITLE
elFinder error

### ISSUE THREAD

**Issue by guelu63** [modxcms/fred#8]
Accesing elFinder  to find images, get  'errConf' + 'errNoVolumes'
![captura](https://user-images.githubusercontent.com/29445187/42538960-bfbaa33e-8499-11e8-93c8-d945b79ff654.JPG)

**Comment by guelu63** [comment]
Sorry.... media sources fred property bad configured.
Amazing extra!

**Comment by Electrica** [comment]
Shom ne please your config. I have this error.

**Comment by Electrica** [comment]
@guelu63

**Comment by Electrica** [comment]
Create in mediaSource option fred and value option true
![image](https://user-images.githubusercontent.com/3878386/42582884-eeebd142-8551-11e8-9b54-6057e253db5d.png)
See this:

https://github.com/modxcms/fred/blob/master/assets/components/fred/web/elfinder/connector.php#L44
