### ISSUE TITLE
Specific Category & Element Limitations via ACL

### ISSUE THREAD

**Issue by sjmclean24** [modxcms/fred#80]
Is it possible to have an option to allow the visibility of specific Category/ies and Component/s via the MODX ACL?

This means that specific components can be available for usage on the Front End Editor for specific Roles assigned to them.

**Comment by rthrash** [comment]
This has definitely been discussed and should be done. Sorting out when. How critical is this (and yes excluding #82) for your use case?

**Comment by sjmclean24** [comment]
Due to the use of User Roles, where we only want to allow particular User Roles to only be able to edit their areas, it is critical.

An extended idea would also be to lock components already placed from being removed or edited.

We have created a workaround this with custom js to hide a category based on its name by manipulating the DOM. We still had a small issue on when to fire the script as the elements themselves do not load with page load, but it's almost solved I believe.
