### ISSUE TITLE
Allow Use of Template Variable as Elements

### ISSUE THREAD

**Issue by sjmclean24** [modxcms/fred#82]
The benefits of having this is that:

- They give more options, including the Input Options - which is essential to manage a Content Creator/Editor on what he/she inputs (Min Length, Max Length, Regex Validation etc);

- Be able to control which Elements display according to the set template;

- Reduce the importance of having the feature within Issue #80 , since now this is achievable via this;

- TVs and Custom TVs are inhereted, meaning that they are not required to be rewritten in Fred, freeing time for the Dev team to concentrate their efforts on other enhancements/issues.

What do you think @rthrash ?

**Comment by rthrash** [comment]
They would need to be re-implemented, b/c ExtJS. This would make sense, but some may not be as feasible to do. We've discussed this, along with validation some but love to hear more thoughts and specific priorities for TV types to convert. Have not discussed the inherited aspect.

**Comment by sjmclean24** [comment]
Would suggest to start with the current Fred HTML Elements available, extending later with the other TV types which come out of the box in MODX.

Maybe would be possible to recreate the render in jQuery for the Fred front-end and use the MODX Processors to obtain the TV properties. Custom TVs would then become the responsibility of their author to make them Fred compatible.

This functionality works great in MIGX, although I understand re the use of extJS within the context. That is why I suggested previously the consideration of creating the front-end render in HTML with jQuery, but retaining default MODX behaviour through Processors, or similar behaviour.

Maybe an even quicker solution is to allow the option to include attributes within an HTML element. So if I want to set an input filed of type text with a min and max character length, I can include the pattern attribute  ex: _<input pattern=".{5,10}">_.

Regardless of the unpopularity of this suggestion, I feel that the best solution is to have the option to extend Fred with extJS and append the necessary files when this is selected to render extJS objects, in this case TVs. Fred itself at the end of the day is still part of the MODX ecosystem, so it has to feel like a natural extension of the CMS itself. It should inheret the functionality that developers and users are used to. This done, whilst retaining the jQuery base which opens Fred to a wider developer user group who want to add their customisations.

Choices have to be made at this stage, taking into consideration that MODX3 will still be based on extJS. It would be better to focus dev time on new issues and enhancements, rather than writing developing the same item twice in two different languages.

**Comment by theboxer** [comment]
Thank you for the suggestion, we're not going to follow the path using TVs as elements. Fred uses a different data structure that wouldn't work with with TVs. Additionally, TVs go beyond the ones that ship with MODX, so it would be impossible to recreate options for each scenario. 

However, we'll try to add support for more alternatives to Fred that extend past the content area. For example, you can currently use text TVs as additional dropzones.

There is no plan for Fred to be extended with ExtJS, jQuery or other libraries, because we want to keep it light and don't want to cause conflict with a site's code.
