### ISSUE TITLE
Quick update bugs for Fred-powered pages

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#83]
1. The content is not blocked from editing in the quickupdate content area. 
2. I tried hiding from menu via quickupdate and got the "No fingerprint was provided" error" 
<img width="355" alt="editing test page meet fred the friendly editor for modx 2019-01-07 15-59-53" src="https://user-images.githubusercontent.com/234237/50795905-61b21a80-1295-11e9-8453-22664a4e4cef.png">

**Comment by theboxer** [comment]
You can't do quick update on fred resources.
