### ISSUE TITLE
Add "file" type to settings

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#85]
I understand it's not in the docs yet but I can't get the "file" type to work. This is what I have in an option set:
```
{
  "settings": [
    {
      "name": "file_select",
      "label": "Select File",
      "type": "file",
      "value": "assets/pdfs/menu.pdf",
      "mediaSource": "Media"
    }
  ]
}
```

In the fred sidebar, all I get is a plain text field. There is no file picker displaying.

**Comment by rthrash** [comment]
You can work around this with an image type and disable the preview. A real fix will be our duplicating the image type for just files.

```{
  "settings": [
    {
      "name": "file_select",
      "label": "Select File",
      "type": "image",
      "showPreview": false,
      "value": "assets/pdfs/menu.pdf",
      "mediaSource": "Media"
    }
  ]
}
```

**Comment by digitalpenguin** [comment]
Thanks @rthrash I'll give that a try!

**Comment by theboxer** [comment]
It's not in docs cause the "file" type doesn't exist :)))
I'll make sure it gets added.

**Comment by digitalpenguin** [comment]
Haha no problem. Thanks @theboxer
