### ISSUE TITLE
Backspace Issue on Fred

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#86]
[See video. ](http://springbokhost.com/fred-issue.mov)

If you hit backspace on an input field it removes the input field and you're typing in the Fred Toolbar.

**Comment by matdave** [comment]
Do you have content-editable set on your dropzone? It shouldn't be if it is.

**Comment by kars-springbok** [comment]
I work with rows of columns

`<div class="row" data-fred-name="row">
    <div class="col-12" data-fred-dropzone="12">
        
    </div>
</div>`

This is the structure I use for my rows + columns. 

This is my text input block element:
`<div contenteditable="true" data-fred-name="text_block"  data-fred-rte="true">
    Type text here..
</div>`

Now, if I drop the text block in a column and do backspace (as seen in the video) then I get the bug. If I however drop the text block in nothing, just the normal fred dropzone and hit backspace, I do not get the bug.

Hope this helps.

@matdave  To respond to your question, the row/column does not have content-editable set on its dropzone. Is it possible this bug is caused by something different related to my dropzones? For instance the data-fred-name or data-fred-dropzone?

**Comment by kars-springbok** [comment]
@matdave could it be since the .row uses data-fred-name (which triggets content-editable) bugs with the inner .col-12 (which is not content editable)? So if I place something within .col-12 Fred thinks its content-editable since it is within a content-editable element?

Btw does data-fred-dropzone trigger content-editable? It doesn't say on the documentation but I assume it doesn't? Else that could cause the issue.

**Comment by matdave** [comment]
Anything that exists within a dom element with the attribute contenteditable will be editable. Check your dropzone layering to make sure you haven't accidentally given a dropzone a data-fred-name or a contenteditable attribute. 

Data-fred-dropzone does not trigger contenteditable, only data-fred-name.

**Comment by kars-springbok** [comment]
Oke then the issue is caused by the row with data-fred-name="row". However is it intended that if you hit backspace on a Element, with a parent that has content-editable, that it types into the fred-toolbar? I assume it would just lock out, so the content in the row is editable but there is nothing to add. I wonder why it writes into the fred-toolbar.

**Comment by matdave** [comment]
This is browser behavior. It's unfortunately not anything we have control over. Any and all elements within a "content editable" wrapper are editable.
