### ISSUE TITLE
Allow switching between contexts/languages in the "Site" section of the Fred sidebar

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#88]
It would be great to add a select box to the top of the "Site" section of the Fred sidebar.

The select box would list approved contexts and allow an editor to switch between contexts/languages with ease. On selection the list of pages shown would be replaced with pages from the newly selected context.

Of course if only one context is approved, the select box would not appear.

**Comment by digitalpenguin** [comment]
After a bit more playing around with a Fred multi-lingual site, don't worry about putting this feature request as a high priority.
Most multi-lingual sites have their own language switcher and that works fine as an alternative to a switcher within the sidebar itself.

(It would still be a nice addition at some point though).

**Comment by theboxer** [comment]
As each multilingual plugin has it's own way of linking translated resources, it'll have to be a standalone extra done as an integration for example between babel and fred. I don't think this feature should be directly implemented in fred's core...
