### ISSUE TITLE
Saving only works in dropzones

### ISSUE THREAD

**Issue by bYemma** [modxcms/fred#9]
At the moment Fred only saves data only in dropzones. So the following usecase ist not supported:
Defining "fixed" elements in the template, so clients can not remove them from the site.

For example a first headline: `<h1 contenteditable="true" data-fred-name="title">Hello, world!</h1>`
Or think of an article picture or something else that should stay on the site in any case. This would be very helpful to guide the (unaware) editors in the "right direction" when they're filling the page.

**Comment by theboxer** [comment]
Yes, Fred doesn't support using fred element's outside of main dropzone and it's not a planned feature right now.

For the h1 tag, I'd recommend using classic MODX templating for it `<h1>[[*pagetitle]]</h1>`, users can change page title through Fred page settings.

FYI: We'll be working towards some rules of using elements (like mandatory element, maximum number of occurrences for element and such).

**Comment by JANogueira** [comment]
Hi All,
"FYI: We'll be working towards some rules of using elements (like mandatory element, maximum number of occurrences for element and such)."

Any idea when this will be available? This will be very interesting addition.
Thanks
