### ISSUE TITLE
data-fred-name within <svg>

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#91]
```
<svg>
<text transform="matrix(1 0 0 1 621 171)" class="st2 st3 st4" data-fred-name="title1">TEXT 1</text>
<text transform="matrix(1 0 0 1 621 228)" class="st2 st3 st4" data-fred-name="title2">TEXT 2</text>
</svg>
```

In a project we are working with text within SVGs to make pretty images with background images. However this text (which gets filled) is changeable. If I add data-fred-name to it, I cannot click on the actual text and change this.

Is this because it is within <svg> or is just not supported (yet, I hope)?

**Comment by matdave** [comment]
The contenteditable attribute on SVGs is not supported in that method. It would be better to use an option set 
```
<svg>
<text transform="matrix(1 0 0 1 621 171)" class="st2 st3 st4">{{title1}}</text>
<text transform="matrix(1 0 0 1 621 228)" class="st2 st3 st4">{{title2}}</text>
</svg>
```
