### ISSUE TITLE
Different Background for child dropzone

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#92]
So I have a div which is nicely formatted and within that div I want to drop additional Elements (they are child elements of that div). 

Currently if you drop an Element that has a dropzone within itself the color of the dropzone is the same as the regular dropzone. So it is very hard to see if you are dropping in the Fred Dropzone or if I'm dropping in the dropzone of my Div.

Would be handy to have a different color for inner dropzones/child dropzones.

**Comment by kars-springbok** [comment]
Maybe something like data-fred-dropzone-background="COLORNAME" could be useful? We can already set the height (which doesn't work for me however), what if we can customise dropzones even more? Even things like inner margin etc could be useful.

**Comment by matdave** [comment]
The dropzones are opaque, and gradually darken as they layer. We are discussing an option to define a custom CSS path if you want to apply your own styles, or you can currently inject a stylesheet using a plugin that checks if $_SESSION['fred'] == 1 during OnWebPagePrerender.
