### ISSUE TITLE
data-fred-min-height not working?

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#93]
```
<ul class="solution-sub-domain-tile-sub-domains" style="display: block;" data-fred-dropzone="content" id="sub-domains" data-fred-min-height="250px;">
</ul>
```

I have set the data-fred-min-height to 250px. But if I drop this Element on my page it does not show the height of 250px. Is data-fred-min-height not working accordingly or did I not use it correctly?

I assume the end result would look like an empty dropzone box that is at least 250px in height?

**Comment by matdave** [comment]
You can't have the semi colon, and unfortunately this is still an experimental CSS feature not supported by all browsers. We are working on a JavaScript fallback, though. With the current release, the best method is setting style="min-height: 250px;"

**Comment by kars-springbok** [comment]
Solved my issue! ; just broke it for me. So it works in Chrome 👍
