### ISSUE TITLE
Rich Text Editor buggy

### ISSUE THREAD

**Issue by kars-springbok** [modxcms/fred#94]
[See video.](http://springbokhost.com/cant-hit-enter.mov)

You cannot see it but at the beginning and at the end of the video I'm also trying to hit enter to continue typing on a new line, however it is not possible to this?

Also H2/H3/H4 doesn't trigger unless I change the selected string to bullet list or numbered list first. B, I, Stroke all work fine.

**Comment by rthrash** [comment]
`Hx` tags and line-breaks/paragraphs require the RTE be in a `<div>`—required by Tiny. So … closing.
