### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#96]
We're seeking help with the Dutch translation for Fred. You're free to create a Pull Request, or to just download the English base files from https://github.com/modxcms/fred/tree/master/core/components/fred/lexicon/en and to reply to this with them attached when done. Thank you!

**Comment by joeke** [comment]
I'll help with the Dutch translations. Will be finished somewhere this week :).

**Comment by rthrash** [comment]
Thank you @joeke!

**Comment by rthrash** [comment]
@joeke any luck so far?

**Comment by joeke** [comment]
@rthrash Haven't had the time for it yet unfortunately. Hopefully I can squeeze it in during work hours today.. will keep you posted.

**Comment by joeke** [comment]
@rthrash And finally, here they are: https://github.com/modxcms/fred/pull/118

**Comment by rthrash** [comment]
Hi @joeke thanks! We now have Crowdin set up to make keeping up with translations easier and more automatic: https://crowdin.com/project/fred … would you want to be a proofreader there?

**Comment by joeke** [comment]
@rthrash Yeah of course, no problem. I'd like to be a proofreader :).
