### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#97]
We're seeking help with updating the Russian translation for Fred since the lexicon files have grown since the original translation. 

You're free to create a Pull Request, or to just download the existing files and reply to this issue with the new files attached:

1. Get the latest English base files from https://github.com/modxcms/fred/tree/master/core/components/fred/lexicon/en, 
2. merge them with the existing Russian files from https://github.com/modxcms/fred/tree/master/core/components/fred/lexicon/ru
3. Reply to this issue with the updated files attached when done. 

Thank you!

**Comment by Ibochkarev** [comment]
@rthrash Transfer the translation of lexicons to https://crowdin.com. Manual translation is difficult!

**Comment by rthrash** [comment]
I don't think we'll be able to get that set up ahead of release. Would it be possible to work with a standard PR or attach the files for the first release? Thanks!

**Comment by Ibochkarev** [comment]
@rthrash I will try to find time to translate.

**Comment by rthrash** [comment]
We got Crowdin set up: https://crowdin.com/project/fred … I hope this helps!

**Comment by rthrash** [comment]
Russian translation progress here: https://crowdin.com/project/fred/ru#
