### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by rthrash** [modxcms/fred#98]
We're seeking help with updating the German translation for Fred since the lexicon files have grown since the original translation.

You're free to create a Pull Request, or to just download the existing files and reply to this issue with the new files attached:

1. Get the latest English base files from https://github.com/modxcms/fred/tree/master/core/components/fred/lexicon/en,
2. Merge them with the existing German files from https://github.com/modxcms/fred/tree/master/core/components/fred/lexicon/de
3. Reply to this issue with the updated files attached when done.

Thank you!

**Comment by bYemma** [comment]
I did the existing translations. When I find the time I can do the update!

**Comment by rthrash** [comment]
Thank you @bYemma!

**Comment by bYemma** [comment]
#101 is ready to go :)
