### ISSUE TITLE
Fred ignores current context when using a context setting tag.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/fred#99]
In my Fred element, I have the remote option enabled and I have a tag for a context setting.
e.g. `[[++site_start]]`
In my `web` context settings, `site_start` is set to `1`.
In my `zh` context settings, `site_start` is set to `2`.
In my `ja` context settings, `site_start` is set to `3`.

The tag will *always* return `1` no matter which context it is loaded from.

When not using Fred it works as expected.

**Comment by bYemma** [comment]
Does the uncached version `[[!++site_start]]` make a difference?

**Comment by digitalpenguin** [comment]
Tried that - unfortunately no difference.

**Comment by theboxer** [comment]
Ah, right, cause the endpoint inits `web` context by default... I'll figure this one out, it's pretty critical to get it done correctly :)

**Comment by digitalpenguin** [comment]
Here's my quick fix until @theboxer can do a proper solution:

I added the following code to line 63 of core/components/fred/model/fred/src/Endpoint/Ajax.php

```
        if($action == 'RenderElement') {
            $resource = $this->modx->getObject('modResource',[
                'id'    =>  $payload['resource']
            ]);
            $context_id = $resource->get('context_key');
            $this->modx->switchContext($context_id);
        }
```

**Comment by digitalpenguin** [comment]
Thanks for fixing this @theboxer !
Will this also resolve the problem with the rebuild button not processing the context settings tags?

**Comment by digitalpenguin** [comment]
Example: 
I have a resource on each context and I have a context setting on each with the id of the resource as the value. i.e. `booking_id`

In a Fred element I have a link to the resource:
`<a href="[[~[[++booking_id]]]]">Link</a>`
With the temporary fix I posted above, this works fine and resolves to the URL `https://mysite.local/en/booking.html`

However, if I use the rebuild button in the Fred CMP, then the context setting tag is not resolved and the link would show as: 
`https://mysite.local/en/[[~[[++booking_id]]]]`


This could be an entirely separate issue, I just assumed it was related. If it isn't related I can create another issue if you like.

**Comment by theboxer** [comment]
Where do you get the link in format `https://mysite.local/en/[[~[[++booking_id]]]]` ?

**Comment by digitalpenguin** [comment]
It appears on the page (when Fred is not active) after running rebuild. 
If I load the page in Fred it works fine and saving it fixes the problem. 
But of course I then need to load each page individually and save them to fix each page.
